### ISSUE TITLE
Durchschnittsberechnung und Ausschlagen: Vergesslichkeiten

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#100]
2 Bugs:
1. Wird im Tab (Reiter) Ausrüstung eine andere Durchschnittsberechung der letzten Sude gewählt als die maximale Anzahl, vergisst der KBH diese Einstellung spätestens beim Neustart und wählt wieder die maximale Anzahl.
2. Wird im Tab (Reiter) Rezept im Tab Hopfen ein Hopfen beim Ausschlagen mit Minuswert gewählt und bei Menge (g) eingetragen, vergisst der KBH diese Einstellung bpätestens beim Neustart und wählt wieder den Wert 0, rot hinterlegt für alle Felder des Hopfens.

**Comment by BourgeoisLab** [comment]
1. erledigt mit edabf78.
2. bereits erledigt.
