### ISSUE TITLE
Klickempfindlichkeit Schaltflächen Buttons, Widgets

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#102]
<img width="1022" alt="Pop-up" src="https://user-images.githubusercontent.com/51321250/86173007-8b14d500-bb1f-11ea-850a-a80cb118ffed.png">
<img width="225" alt="Widget" src="https://user-images.githubusercontent.com/51321250/86173018-90721f80-bb1f-11ea-997c-e1fe602cdd08.png">

Alle Pop-up-Fenster und Widgets lassen sich in der Beta-Version 2.2.0 Mac nur mit mehrmaligen Versuchen aktivieren. Meist ist es nur ein Bruchteil des üblichen als sensitive Schaltfläche definierten Bereichs. Genauer: immer nur die Sektion links oben. Alle anderen Bereiche im möglichen Bereich des Mauszeigers sind "blind".

Damit ein Pop-up oder Widget sich öffnet, genügt kein kurzer Klick. Vielmehr ist ein Klick mit 1,5-2sec Dauer nötig.
Speziell die Pop-ups im Tab Rezept in den Subkategorien Malz, Hopfen, etc. sind nahezu "taub". Der auslösende Bereich ist auf einem Retina-Bildschirm kleiner als 1,5mm!

**Comment by BourgeoisLab** [comment]
Das scheint ein Qt Bug zu sein.
Workaround: Umstellung auf Fusion Style.

Es wird zunächst auf die nächste Qt Version abgewartet, bevor hier etwas unternommen wird.
