### ISSUE TITLE
Wasseraufbereitung Einheiten

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#103]
Die Einheiten Kilogramm und Liter sind im Bereich Wasseraufbereitung des Tabs Rezept praxisfern. Sie sollten entfernt werden. Bei der Wasseraufbereitung wird im Mengenbereich von Milligramm, Millillitern und Gramm gearbeitet, selbst wenn man mit Mengen im Hektoliterbereich braut.  Die voreingestellte Maßeinheit kg verwirrt.

**Comment by BourgeoisLab** [comment]
Prinzipiell kann bei der Wasseraufbereitung irgendetwas angegeben werden. Es muss nicht aus der Auswahl sein. Wenn alle Einheiten angeboten werden, schränke ich den Benutzer nicht unnötig ein. Ich habe jetzt auch kein Beispiel in kg, aber das soll nicht heissen, dass es das nicht gibt.

**Comment by Rasinari** [comment]
Servus Frédéric,

Du hast natürlich vollkommen Recht. Ich habe bei meinen Überlegungen Sauermalz vollkommen übersehen, ein Fall, den es real gibt.

Best
Radulph
