### ISSUE TITLE
Gärverlauf, Messung wird zugefügt trotz Abbruch

### ISSUE THREAD

**Issue by ivh** [kleiner-brauhelfer/kleiner-brauhelfer-2#105]
Wenn man im Gärverlauf aufs + drückt, um eine Messung zuzufügen, öffnet sich der Dialog, wie gewünscht, aber im Hintergrund wird die Messung gleich in die Liste eingefügt. Dort bleibt sie auch, wenn man im Dialog "Cancel" klickt.

**Comment by BourgeoisLab** [comment]
Erledigt mit 39b9c34c8c12835c64114c2b6be8ca6f68e3931d.
