### ISSUE TITLE
Chargennummer bei Rohstoffen

### ISSUE THREAD

**Issue by hkristen** [kleiner-brauhelfer/kleiner-brauhelfer-2#113]
Zuerst mal vielen Dank für die stetige Weiternetwicklung des KBH ... in letzter Zeit sind wirklich viele, sehr geniale Funktionen hinzugekommen!!  Speziell die integrierte Wasseraufbereitung ist extrafein ... jetzt sind diese Informationen endlich auch direkt im KBH vorhanden und müssen nicht extern bezogen werden (z.B. bei MuM).

Wir nutzen den KBH nicht für die Braurezepte und die Dokumentation des Gärverlauf sondern auch für die Rohstoffverwaltung. Hier fehlt uns ein Reiter bei der Rohstoffliste, nämlich die "Chargennummer". Mit dieser kann bei jedem Sud rückverfolgt werden welche Charge der einzelnen Rohstoffe im Endprodukt gelandet ist, sollte es mal zu einem Rückruf von Seiten des Herstellers kommen. 

Wäre es möglich diesen Reiter, gerne auch als optionales Feld, einzubauen? 

Bierige Grüße
Harald

**Comment by BourgeoisLab** [comment]
Ich glaube, es ist nicht ganz so einfach wie man es sich vorstellt. Vor allem wenn Chargen aufgebraucht und gemischt werden.

Du kannst es im Moment so lösen, dass du für jede Charge einen neuen Eintrag in der Rohstoffliste machst.

**Comment by hkristen** [comment]
Danke für die Antwort, hatte ganz vergessen zurückzuschreiben - als Workaround nutze ich die von dir vorgeschlagene Methode, bin gespannt ob da noch eine bessere Lösung gefunden werden kann :)

**Comment by Rasinari** [comment]
Die Chargennummer ist nur auf Säcken vorhanden, nie aber aus abgefüllten Tüten der Shops. Das Feld Bemerkung ist hier das Mittel der Wahl.
Die Chargennummer sagt selbst noch nicht viel über die Jahrgangsqualität eines Malzes aus. Das erfährt man erst durch die Malzanalyse im Labor der Mälzerei. Mälzereieen veröffentlichen diese Ergebnisse fast nie. Zugang haben dazu nur die B2B-Kunden. Erst im Zusammengang mit der Laboranalyse wäre eine Chargennummer von Interesse.

Derzeit bietet eine Chargennummer im Hobbybereich keinen Mehrwert.
