### ISSUE TITLE
Inkonsistenter Wert für Alkoholgehalt

### ISSUE THREAD

**Issue by michluk** [kleiner-brauhelfer/kleiner-brauhelfer-2#114]
Hi,

Ich nutze das Tool zwar erst seit kurzem, aber ich denke ich habe eine Inkonsistenz bei der Berechnung des Alkoholgehalts festgestellt. Ich hoffe natürlich auf ein Irrtum meinerseits 👍 

Es geht um darum, dass bei mir im Tab "Gärverlauf" ein anderer Alkoholgehalt berechnet wird, als im Tab "Abfülldaten":
<img width="691" alt="Bildschirmfoto 2020-07-26 um 23 18 50" src="https://user-images.githubusercontent.com/32687706/88489750-97614600-cf96-11ea-8c2a-b5528f8d2b17.png">

<img width="1059" alt="Bildschirmfoto 2020-07-26 um 23 18 42" src="https://user-images.githubusercontent.com/32687706/88489753-9c25fa00-cf96-11ea-992d-f66d22157d67.png">
 
Mit anderen Berechnungstools bekomme ich auch den Alkoholgehalt von ca 3,8% ausgerechnet, ich frage mich nur, warum im Tab "Abfülldaten" der Wert rechts abweicht. 

Womit könnte das zusammenhängen? In beiden Übersichten ist ja ersichtlich, dass prinzipiell die selben Ausgangsdaten verwendet wurden.

Viele Grüße
Lukas

**Comment by michluk** [comment]
Ich habe mich dann auch mal in den Code eingelesen und bei dem Alkoholgehalt wird wohl bereits der Zucker bzw die Speisegabe mit eingerechnet. Damit macht der Wert von 4,3% hier natürlich Sinn. In dem Sinne also kein Issue (sorry dafür)...

Ich möchte nur vielleicht anmerken, dass man diesen Hinweis vielleicht in die Info Box mit einbringen könnte 👍

**Comment by BourgeoisLab** [comment]
Genau das habe ich vermutet. Und auch an der Infobox mit der Erklärung hatte ich gedacht.

**Comment by michluk** [comment]
Alternativ könnte man auch ein weiteres Feld mit dem Alkoholgehalt ans Ende der Übersicht (nach Zucker/Speise) setzen, dann ist es auch klarer vielleicht. Mir war unklar, dass Werte von "unten nach oben" mit eingerechnet werden.

Im ganzen Tool ist ja relativ straightforward alles von "oben nach unten" strukturiert.


Nichtsdestotrotz: Das Tool ist einfach Klasse!

**Comment by BourgeoisLab** [comment]
Guter Hinweis. "Von oben nach unten" ist schon die Idee. Das jetzige Feld wird neu nur die Gärung berücksichtigen und weiter unten wirds ein neues Feld geben, welches auch die Karbonisierung berücksichtigt.
