### ISSUE TITLE
Vergärungsgrad verknüpfen

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#115]
Ich möchte vorschlagen den Vergärungsgrad im Tab Rezept mit dem Wert **Vergärungsgrad** im Reiter **Hefe** im Tab Rohstoffe zu verknüpfen.

Wird im Reiter Hefe bei Rohstoffe ein Vergärungsbereich angegeben, etwa 77%–83%, so wird der erste Zahlenwert als niedrigster Wert herangezogen.

**Alternative:** Stehen bei Hefe zwei Werte, so wird im Tab Rezept automatisch ein Mittelwert gebildet. Im Beispiel also 80%.

**Comment by BourgeoisLab** [comment]
Erledigt mit 5d74d1d.
