### ISSUE TITLE
"Rückbau" der eingeschränkten Eingabemöglichkeiten bei den Messwerten

### ISSUE THREAD

**Issue by nufer** [kleiner-brauhelfer/kleiner-brauhelfer-2#118]
Die neue Funktion mit "+" und "-" beim Gärverlauf finde ich sehr übersichtlich. das Poppup sollte aber erweitert werden.

- Datum und Uhrzeit **frei** definierbar, ev. farbliche Warnung wenn der Messwert in der Zukunft liegt
- Eingabe von Temperatur und Messwert in °Plato respektive g/ml ohne Umrechnung, also extern berechnet. (Aktuell kann ich bereits Temperaturkorrigierte oder anders geeichte Messwerte nicht eingeben) 

Funktionierte mit der "alten" Variante (Eingabefelder unter der Liste) gut, nun nicht mehr.

**Comment by BourgeoisLab** [comment]
Punkt 2 habe ich bereits umgesetzt und kommt in der nächsten Version.

Für ein workaround siehe https://hobbybrauer.de/forum/viewtopic.php?p=389761#p389761

**Comment by BourgeoisLab** [comment]
Erledigt mit 67b84dc9190f5340a56de92e9177638b33ea7abb.
