### ISSUE TITLE
Verdampfungsrate verstellt sich

### ISSUE THREAD

**Issue by kentakit** [kleiner-brauhelfer/kleiner-brauhelfer-2#123]
Nachdem ich die Füllhöhen vor und nach dem Kochen und die Kochzeit eingegeben habe, erhalte ich eine Verdampfungszeit. Die ändert sich aber sofort wieder, sobald ich woanders hinklicke. Anscheinend überschreiben irgendwelche voreingestellten Werte meine Werte.

**Comment by kentakit** [comment]
Das Programm ist wirklich super und macht auch optisch was her. Ich habe es heute erst runtergeladen und kenne auch die Vorgängerversion nicht, deswegen mache ich vielleicht auch was falsch. Ich habe mir die aktuelle portable Verison 2.2.1 runtergeladen und wollte "Ausrüstung" meine Brauanlage einrichten. Dort kann man die Verdampfungsrate einstellen, indem man die Füllhöhe bei Kochbeginn und -ende mit der Kochdauer eingibt. Die daraus errechnete Verdampfungsrate (3,2 l/h) verstellt sich nur leider bei mir immer wieder auf 2,9 l/h, ohne dass ich etwas anderes ändere, sobald ich abspeichere und anschließend das Programm neu starte.

**Comment by BourgeoisLab** [comment]
Das sollte eingentlich nicht passieren. Wenn du das Dialog zumachst, steht bei Ausrüstung 3,2l? Bist du sicher, dass die Datenbank überhaupt abgespeichert wird? Hast du versucht andere Änderungen zu machen?

**Comment by kentakit** [comment]
Ich habe möglicherweise das "Problem" gefunden. Wenn ich einstelle, dass der Durschnitt über die letzten Sude = 0 ist und ich dann etwas ändere (zB Höhe des Maischekessels), stellt er sofort nach der Änderung den Durchschnitt über die letzten Sude auf 1 (ich habe aktuell einen eigenen Sud eingespeichert). Und übernimmt auch die Werte des letzten Sudes für die Ausbeute und Verdampfungsrate. 
Speichern ist auch unter "Datei" ausgegraut, wenn ich nur die Verdampfungsrate ändere.
Unter Durchschnitt bei Verdampfungsrate steht jetzt 2,8 (warum es vorher immer 2,9 war weiß ich nicht). Wenn ich dann auf den Brechnungsbutton drücke, wird mir interessanterweise eine neue Verdampfungsrate von 1,3 l/h angeboten, wenn ich ok drücke. Sobald ich aber wieder auch nur einen anderen Wert wie zB die Höhe des Maischekessels ändere, ändert sich auch wieder der Wert der Verdampfungsrate auf 2,8. Möglicherweise ignoriert er die manuelle Eingabe und springt automatisch auf den Durchschnitt des letztes Sudes zurück. Wie geschrieben, auch wenn ich den Schieberegler auf 0 steht.

Der Schieberegler scheint sich auch etwas seltsam zu verhalten. Wenn er rechts ist und da eine 1 steht und ich ihn nach ganz links ziehe, steht da immernoch 1. Dann ändere ich die Höhe des Maischekessels und der Regler bleibt links aber die Zahl daneben ändert sich zu 0. Dann schiebe ich nach rechts, der Wert bleibt 0. Außer ich ändere die Höhe des Maischekssels, dann ist der Wert eine 1.

Als Datenbank habe ich kb_daten.sqlite abgespeichert und alle sonstigen Werte werden auch ohne Probleme übernommen.

**Comment by BourgeoisLab** [comment]
Erledigt mit 68b7063.
