### ISSUE TITLE
Schieberegler Sudauswahl ohne Effekt

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#124]
Der Schieberegler unten/mitte rechts im Tab Sudauswahl ist in der Version Mac v2.2.0 wirkungslos.
<img width="223" alt="Bildschirmfoto 2020-09-02 um 18 15 36" src="https://user-images.githubusercontent.com/51321250/92009414-c6fb2f00-ed48-11ea-820d-1797617398d8.png">

<img width="275" alt="Bildschirmfoto 2020-09-02 um 18 16 12" src="https://user-images.githubusercontent.com/51321250/92009433-cbbfe300-ed48-11ea-9ae1-ba0d25cf22be.png">

**Comment by BourgeoisLab** [comment]
Erledigt mit f606761.
