### ISSUE TITLE
IBU, Farbe und ggfs. weitere Werte beziehen sich nicht auf angestellte Würzemenge

### ISSUE THREAD

**Issue by patman081** [kleiner-brauhelfer/kleiner-brauhelfer-2#125]
Die Werte IBU, Farbe und ggfs. Alk% werden m.E. nicht korrekt berechnet, da sich diese anhand der abgefüllten Liter berechnen und nicht anhand der angestellten Würzemenge, bzw. Würzemenge vor dem Hopfenseihen.

Beispiel:
20 Liter werden angestellt, der IBU Wert ist zu diesem Zeitpunkt 30. Abgefüllt werden allerdings nur 15l, da z.B. eine große Menge Hopfen gestopft wurde und sehr viel zwischendurch abgezwickt wurde. Der IBU werd, wird nun nachdem der Sud als abgefüllt markiert wird, auf 45 korrigiert.
Gleiches gilt für den Farbwert und ggfs. weitere Werte.

**Comment by BourgeoisLab** [comment]
Gute Beobachtung.

**Comment by BourgeoisLab** [comment]
Es ist nicht ganz eindeutig, mit welcher Würzemenge gerechnet werden soll.
"Würzemenge vor dem Hopfenseihen" wäre vom Brauprozess her logischer. Aber unter Umständen wird danach noch mit Wasser verdünnt (wenn die Stammwürze nicht stimmt, oder bei High-Gravity). "Anstellmenge" ist auch nicht ganz korrekt, weil die Speisemenge dort abgezogen wird. Am ehesten wäre die "Gesamtwürzemenge beim Anstellen" zu nehmen. Dafür werden Verlustmengen zwischen Kochende und Anstellen nicht berücksichtigt. Aber es ist sicher richtiger als die Abfüllmenge zu nehmen.

**Comment by patman081** [comment]
Es ist tatsächlich ein wenig schwieriger.
Ich habe mal ein wenig auf den Code geguckt und wie es scheint, kann man keinen der bisherigen Werte hernehmen, sondern muss eine Zwischenrechnung machen.
Wie bereits von dir beschrieben, wäre es korrekt die Würzemenge vor dem Hopfenseihen zu nehmen und hier dann jedoch noch den High-Gravity Faktor bzw. die Menge des verdünnten Wassers hinzuziehen.

**Comment by BourgeoisLab** [comment]
Eben nicht nur. Der Nutzer darf verdünnen, unabhängig vom HGF (z.B. wenn die Stammwürze aus irgendeinem Grund zu hoch ist).
Neu wird es anhand der Anstellemenge + Speisemenge berechnet.
Erledigt mit 4fbf344.

**Comment by patman081** [comment]
Danke 👍
