### ISSUE TITLE
Version 2.2.2 crasht auf macOS

### ISSUE THREAD

**Issue by realholgi** [kleiner-brauhelfer/kleiner-brauhelfer-2#128]
Egal ob von github Actions oder selbst gebaut. Crasht direkt nach dem Start...

Investigating... Hmmm...

> Application Specific Information:
> abort() called
> 
> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
> 0   libsystem_kernel.dylib          0x00007fff6b08433a __pthread_kill + 10
> 1   libsystem_pthread.dylib         0x00007fff6b140e60 pthread_kill + 430
> 2   libsystem_c.dylib               0x00007fff6b00b808 abort + 120
> 3   org.qt-project.QtCore           0x000000010e41b239 0x10e403000 + 98873
> 4   org.qt-project.QtCore           0x000000010e75ac3e QMessageLogger::fatal(char const*, ...) const + 196
> 5   org.qt-project.Qt.QtWebEngineCore   0x000000011810ceff 0x111292000 + 115846911
> 6   org.qt-project.Qt.QtWebEngineCore   0x00000001113313d5 0x111292000 + 652245
> 7   org.qt-project.Qt.QtWebEngineCore   0x000000011132d03d 0x111292000 + 634941
> 8   org.qt-project.Qt.QtWebEngineCore   0x000000011132c8f5 0x111292000 + 633077
> 9   org.qt-project.QtWebEngineWidgets   0x000000010cacba3c 0x10cac2000 + 39484
> 10  org.qt-project.QtWebEngineWidgets   0x000000010cace7a0 QWebEnginePage::QWebEnginePage(QObject*) + 48
> 11  com.github.kleiner-brauhelfer.kleiner-brauhelfer-2  0x000000010c86b4c6 WebView::WebView(QWidget*) + 86
> 12  com.github.kleiner-brauhelfer.kleiner-brauhelfer-2  0x000000010c86ca56 Ui_WdgWebViewEditable::setupUi(QWidget*) + 982
> 13  com.github.kleiner-brauhelfer.kleiner-brauhelfer-2  0x000000010c86c132 WdgWebViewEditable::WdgWebViewEditable(QWidget*) + 482
> 14  com.github.kleiner-brauhelfer.kleiner-brauhelfer-2  0x000000010c7cf315 Ui_TabSudAuswahl::setupUi(QWidget*) + 6053
> 15  com.github.kleiner-brauhelfer.kleiner-brauhelfer-2  0x000000010c7cbf95 TabSudAuswahl::TabSudAuswahl(QWidget*) + 85
> 16  com.github.kleiner-brauhelfer.kleiner-brauhelfer-2  0x000000010c731407 Ui_MainWindow::setupUi(QMainWindow*) + 5735
> 17  com.github.kleiner-brauhelfer.kleiner-brauhelfer-2  0x000000010c72eade MainWindow::MainWindow(QWidget*) + 94
> 18  com.github.kleiner-brauhelfer.kleiner-brauhelfer-2  0x000000010c72b3c1 main + 6545
> 19  libdyld.dylib                   0x00007fff6af3ccc9 start + 1
>

**Comment by BourgeoisLab** [comment]
Hängt wahrscheinlich mit https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/issues/124#issue-691162984
Zusammen.

Ich schaue, es mir später an.

**Comment by realholgi** [comment]
Version mit  a635a42 ging noch.

**Comment by realholgi** [comment]
Aus QtCreator gestartet funktioniert es. Hmmmmmm.

**Comment by realholgi** [comment]
Es funktionierte noch mit Qt 5.15.0 und nicht mehr mit Qt 5.15.1!

**Comment by realholgi** [comment]
Problem liegt an macdeploydt im Deployment Script. Das Binary, welches mit qmake/make gebaut wird, läuft. Sobald aber macdeplyqt aufgerufen wird, umd die dynamischen Bibliotheken dazu zu mischen, crasht das Binary.

**Comment by BourgeoisLab** [comment]
Vielleicht werden die falschen Bibliotheken verlinkt? Kann dir leider nicht wirklich helfen.

Die Windows und Linux Versionen sind mit Qt5.15.0 kompiliert.

**Comment by realholgi** [comment]
Grrrrrr, ist ein Bug in QT: https://bugreports.qt.io/browse/QTBUG-86759

**Comment by BourgeoisLab** [comment]
Ok. Ich schlage dann vor, mit Qt5.15.0 zu kompillieren.

Diese WebEngine Sache macht immer wieder Ärger... Leider finde ich keine schönere Lösung.

**Comment by realholgi** [comment]
Habe ich durch die in https://bugreports.qt.io/browse/QTBUG-86759 vorgeschlagene Lösung im Deployment Script gelöst mit  3b59b8b
