### ISSUE TITLE
Spickzettel

### ISSUE THREAD

**Issue by aklier** [kleiner-brauhelfer/kleiner-brauhelfer-2#129]
Beim Update 2.2.2 werden die Vorschauspalte rechts bei der Sudauswahl, sowie Spickzettel und Zusammenfassung nicht mehr angezeigt. Kurzes aufflackern und dann wird's dunkel. 

Mit freundlichen Grüßen, Andreas

**Comment by realholgi** [comment]
Und welches ist das Betriebssystem deiner Wahl?

**Comment by aklier** [comment]
Ups, das ging aber schnell.

Mac OS Catalina
Version 10.15.6

Nochmal freundlich Grüße, Andreas

**Comment by BourgeoisLab** [comment]
@realholgi ich würde wieder auf qt5.15.0 wechseln. So viel entscheidendes hat sich im code ja nicht verändert.

**Comment by aklier** [comment]
Hallo,

Da ich jetzt nicht der Crack bin was Computer angeht, vermute ich mal du empfiehlst mir, bei der vorherigen Version vom Brauhelfer zu bleiben. Wenn ja, so ist dies bereits passiert.  

Grüße und vielen Dank, Andreas

**Comment by realholgi** [comment]
Ich habe eine neue Version mit qt-5.15.0 gebaut und i das Binary in den Releases ausgetauscht (https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/releases/download/v2.2.2/kbh2_v2.2.2_macos.zip)

**Comment by realholgi** [comment]
macOS CI entsprechend angepasst, dass erst einmal immer qt-5.15.0 benutzt wird.

**Comment by aklier** [comment]
Alles gut jetzt. Vielen Dank nochmal!
