### ISSUE TITLE
Malz- und Weitere-Zutaten-Berechnung Maische/Kochen Reiter-übergreifend zusammen berechnen

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#131]
Derzeit wird bei der Rezepterstellung im Reiter Malz 100% vorrausgesetzt, Weitere Zutaten im Tab Rezept, die mit einem im Tab Rohstoff festgelegten Faktor vergären, werden zwar anteilig im Reiter Malz berücksichtigt, aber nicht prozentual ausgewiesen.

Dies hat zur Folge, dass bei der Übernahme von Schüttungen aufwendige manuelle Berechnungen außerhalb des KBH notwendig sind.

Beispiel: Gegeben ist ein Rezept mit Schüttung 86% Basismalz und 8% Karamellmalz und 6% Traubenzucker. Die 6% Traubenzucker können nicht anteilig berechnet werden. Stattdessen muss der Anteil Traubenzucker auf die Schüttung Malz 91,2% und 8,8% umgelegt werden; erst dann kann man den Anteil Weitere Zutaten adäquat von der Schüttungsmasse abziehen.

Es wäre hilfreich, wenn die Gewichtsprozente über die Reiter Malz und Weitere Zutaten anteilig berechnet werden können.

Eine andere Überlegung wäre bei Kochen/Maischen Weitere Zutaten in den Reiter Malz zu integrieren und damit aus Weitere Zutaten Gärung herauszunehmen.

**Comment by LondonRain** [comment]
Das ist hab ich auch schon schmerzlich vermisst für ein DIPA, wo ich 5 Gewichtsprozent der Schüttung in Haushaltszucker haben wollte.

**Comment by BourgeoisLab** [comment]
Eine zusätzliche Prozentangabe für den Extrakt unter Berücksichtigung der weiteren Zutaten lässt sich einfach einbauen.
![grafik](https://user-images.githubusercontent.com/9480307/96339358-9242fd00-1094-11eb-874b-12d069f7b5e5.png)

Was nicht so einfach geht (und ich sehr wahrscheinlich auch nicht machen werde), ist bei Änderung einer Malzgabe die Gabe bei den weiteren Zutaten automatisch anzupassen.

Das Vorgehen wäre also:
1. 6% der gewünschten Stammwürze manuell berechnen
2. Beim Traubenzucker die Menge so einzustellen, bis der Anteil der Stammwürze mit dem berechneten Wert übereinstimmt
3. Bei den Malzgaben beim neuen Prozentfeld 86% bzw 8% eintragen
4. Eventuell Rundungsfehler beim Malz oder WZ korrigieren

**Comment by Rasinari** [comment]
> Eine zusätzliche Prozentangabe für den Extrakt unter Berücksichtigung der weiteren Zutaten lässt sich einfach einbauen.
> Was nicht so einfach geht (und ich sehr wahrscheinlich auch nicht machen werde), ist bei Änderung einer Malzgabe die Gabe bei den weiteren Zutaten automatisch anzupassen.
> 
> Das Vorgehen wäre also:
> 
> 1. 6% der gewünschten Stammwürze manuell berechnen
> 2. Beim Traubenzucker die Menge so einzustellen, bis der Anteil der Stammwürze mit dem berechneten Wert übereinstimmt
> 3. Bei den Malzgaben beim neuen Prozentfeld 86% bzw 8% eintragen
> 4. Eventuell Rundungsfehler beim Malz oder WZ korrigieren

Das hilft schon einmal, ist natürlich noch nicht der große Wurf. Allein dass man bei Übernahme der Schüttungsverhältnisse die Angabe Malz nicht verändern muss, also mit Beispiel 86/8 weiter arbeiten kann, vereinfachte erheblich. Erschwerend kommt ja immer dazu, dass die SHA auch angepasst werden muss. Oft ist die SHA aber unbekannt. 

Mein Vorgehen bei der Rezeptentwicklung ist oft so, dass ich ein Basisrezept nehme und erst dann mit Anpassungen und Änderungen beginne. Ich denke viele handhaben es ähnlich.

**Comment by Rasinari** [comment]
Ich habe heute schon wieder ein Problem mit der fehlenden Funktion: Gegeben ist ein Rezept mit Gewichtsprozenten, aber fehlender Ausbeute Weitere Zutat und fehlender SHA. Die Berechnungen gestalten sich manuell extrem schwer.

Was ist von der Idee zu halten Weitere Zutaten mit Ausbeute ungleich 0 walhlweise direkt in Malz zu übernehmen? Wie gesagt, es fehlt dort eine prozentuale Angabe. Wäre für die Rezeptentwicklung ein großer Gewinn!

**Comment by BourgeoisLab** [comment]
(teilweise) erledigt mit 9f9f40d.
