### ISSUE TITLE
Hopfenstopfgabe Mengeneingabe verschwunden in aktuellem master

### ISSUE THREAD

**Issue by realholgi** [kleiner-brauhelfer/kleiner-brauhelfer-2#134]
Mengeneingabe ist irgendwie bei den Hopfenstopfgaben verschwunden (in commit 5b13c06 minor)

vorher:

<img width="826" alt="vorher" src="https://user-images.githubusercontent.com/980419/97118534-b80e7880-170a-11eb-9062-4005a33e94e2.png">

nachher:

<img width="833" alt="nachher" src="https://user-images.githubusercontent.com/980419/97118537-bd6bc300-170a-11eb-86be-208ef7309af5.png">

**Comment by realholgi** [comment]
in wdgweiterezutatgabe.ui ist alles in wdgZugabezeitpunkt verrutscht.

**Comment by realholgi** [comment]
Fixed mit 387c605d591569493b6d864c4d0f86a0235c984d

Arrgh, ist das ein Gefummel mit dem Qt UI-Editor!

**Comment by BourgeoisLab** [comment]
Ach, so doof von mir. Danke für die Korrektur.
