### ISSUE TITLE
Namen von Rasten – zusätzliche Spezialrasten

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#136]
**Latinisierte Fachbegriffe**
Ich war mehrfach verwirrt wegen der unterschiedlichen Namen von Rasten. 
Würde es nicht Sinn machen dem deutschen den Fachnamen beizustellen?
Beispiel: Gummirast / Glukanrast (35°–40°) – Weizenrast / Ferualsäurerast (45°C)

**Maltaserast (45°)**
Vielleicht sollte auch die Maltaserast aufgenommen werden? Sie ist relativ unbekannt.
http://hobbybrauer-kompendium.de/m/maltaseverfahren/maltaseverfahren.html
https://kraftbier0711.de/das-maischen/

**Beta-Glukanrast (40°-50°)**
Beim Gummirasten mit Gefahr der Läuterkatastrophe, z.B. Kürbis, empfiehlen amerikanische Brauer die sogenannte, temperaturempfindliche **Beta-Glukanrast** bei 40-50°C:
https://beerandbrewing.com/dictionary/1nO559RwFD/
"Adding in a beta glucan rest at 122 °F (50 °C) for 15 minutes to help break those gums down is another helpful trick." (Brew Your Own 2005, Pumpkin Ale)

**Comment by BourgeoisLab** [comment]
Du hast wahrscheinlich mehr recherchiert und auch mehr Erfahrung als ich. Kannst du diese Liste mit deinen Wünsche vervollständigen?

|Name |Temperatur|Dauer|Beschreibung|
|---|---|---|---|
|Gummirast (Glukanaserast)|38|20|Abbau der Glukanen. Empfohlen bei Roggenbier. </br>Temperaturbereich: 35° - 40°</br>Dauer: 20 min - 12 Std|
|Weizenrast (Ferularast)|45|15|Temperaturbereiche: 45° und 48°</br>Dauer: je ca. 15 min|
|Eiweissrast (Proteaserast)|57|10|Temperaturbereich: 50° - 58°</br>Dauer: 10 - 20 min|
|Maltoserast|63|35|Temperaturbereich: 60° - 68°</br>Dauer: 30 - 90 min|
|Kombirast|67|60|Temperaturbereich: 65° - 70°</br>Dauer: 45 - 90 min|
|Verzuckerungsrast|72|20|Temperaturbereich: 68° - 76°</br>Dauer: 15 - 30 min|
|Abmaischen|78|20|Temperaturbereich: 35° - 40°</br>Dauer: mind. 20 min|

Die Spalte Beschreibung wird in zukünftigen Versionen als Tooltip erscheinen. Falls es viele Rasten werden, müsste man eventuell noch die Reihenfolge überlegen. Alphabetisch, Temperatur, Häufigkeit,...

**Comment by Rasinari** [comment]
Ich habe im Forum ausführlich geantwortet.
https://hobbybrauer.de/forum/viewtopic.php?p=401296#p401296

**Comment by BourgeoisLab** [comment]
Erledigt mit b42e6de.
