### ISSUE TITLE
"Neuer Eintrag aus oBraMa" - Fehlermeldung "Die Tabelle xxx konnte nicht heruntergeladen werden"

### ISSUE THREAD

**Issue by Knochi** [kleiner-brauhelfer/kleiner-brauhelfer-2#137]
![grafik](https://user-images.githubusercontent.com/5979046/98944913-16e93580-24f2-11eb-8712-9325a9e0c24e.png)
![grafik](https://user-images.githubusercontent.com/5979046/98944947-1fda0700-24f2-11eb-85de-5caf3827d346.png)
![grafik](https://user-images.githubusercontent.com/5979046/98944959-25375180-24f2-11eb-8905-d5960d918138.png)
![grafik](https://user-images.githubusercontent.com/5979046/98944973-29636f00-24f2-11eb-827b-5bce50482dbb.png)

**Comment by FredericBourgeoisFhnw** [comment]
Das sind Fehlermeldungen und kein Bug.

**Comment by Knochi** [comment]
Ok... wohin kommt dass dann?

**Comment by BourgeoisLab** [comment]
Diese Meldung kommt.... wenn es nicht heruntergeladen werden konnte.
Ohne Details schwierig zu sagen.

**Comment by Knochi** [comment]
Ok was kann ich tun? Die Webseite erreiche ich.. vielleicht kann ich mit
wireshark oder ähnlichem den Zugriff protokollieren.
Reproduzierbar ist es in jedem Fall.

Am Do., 12. Nov. 2020 um 23:48 Uhr schrieb Frédéric Bourgeois <
notifications@github.com>:

**Comment by BourgeoisLab** [comment]
Versuch es zuerst mit dieser EXE hier (ins kbh Verzeichniss kopieren).
[kleiner-brauhelfer-2-obrama.zip](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/5555191/kleiner-brauhelfer-2-obrama.zip)

Im besten Fall funktioniert es (Änderung http statt https) und im schlimmsten Fall gibt es eine detaillierte Fehlermeldung.

**Comment by BourgeoisLab** [comment]
Konntest du die exe testen?
