### ISSUE TITLE
Etikett Vorlagen lassen sich nicht wieder entfernen

### ISSUE THREAD

**Issue by Pitastic** [kleiner-brauhelfer/kleiner-brauhelfer-2#138]
Ich habe einen Bug in der Etiketten-Vorlagen-Verwaltung gefunden, weil ich ein eigenes SVG mit Inkscape entwickelt habe und statt des "Aktualisieren" Buttons (habe ich irgendwie übersehen) immer wieder das zwischendurch geänderte File erneut hinzugefügt habe.

#### Schritte zum Reproduzieren

1. Rezept öffnen > Reiter Etikette _(Etiketten wäre vielleicht besser, wegen der Zweideutigkeit)_
1. Vorlage über Button "Öffnen" hinzufügen
1. Vorlage über Button "Öffnen" hinzufügen (selbe Datei noch einmal wählen)
1. Einer der beiden Einträge auswählen und mit "X" versuchen zu entfernen

#### Auswirkungen:

Es werden mehrere Einträge mit gleichem Namen angelegt, die auch auf das gleiche SVG File zeigen. Keiner dieser Elemente können über "X" wieder entfernt werden. 

Mein Bier schmeckt trotzdem 😀 danke Brauhelfer 👍 

_Edit: Windows 10, KB v2.2.2 - Qt 5.15.0 - Setup x64 Package_

**Comment by BourgeoisLab** [comment]
Der Reiter ist nicht ganz klar. Die Funktion "öffnen" kam erst später. Diese macht eigentlich nichts anderes, als einen Anhang anzufügen (siehe Rezept, Anhänge). Das X-Button hingegen, löscht die "Verknüpfung" zwischen Anhang und Etikette. Es löscht also nicht den Anhang. Dafür musst du ins Rezept Reiter.

Muss mir überlegen, wie man das besser machen kann. Vielleicht mit einder Abfrage, ob man den Anhang auch löschen will.

**Comment by Pitastic** [comment]
Du könntest nach jeder Verknüpfungs-Löschung verwaiste Anhänge selektieren, die (nun) nirgends mehr zugeordnet sind.

Pseudo SQL:
```
SELECT Anhang.id, Rezept.id FROM Anhang
LEFT JOIN Rezept ON Rezept.id=Anhang.rezept_id
WHERE Rezept.id IS NULL;
```

Der Join wird sicherlich über eine Zwischentabelle wegen der Many-To-Many Beziehung gehen und das Statement daher auch anders aussehen...wollte nur das Prinzip verdeutlichen...

**Comment by BourgeoisLab** [comment]
Erledigt mit b714a00.
