### ISSUE TITLE
Zoomregler bei Spickzettel hat keine Auswirkung

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#139]
Er zoomt nur im Programm selbst größer und kleiner. Weder auf das generierte PDF noch auf die Druckvorschau wirkt sich das aus.

KBH 2.2.2

**Comment by BourgeoisLab** [comment]
Siehe #82.
Ich kann den zoom fürs Drucken nicht anpassen (zumindest nicht ohne vernünftigen Aufwand).

**Comment by LondonRain** [comment]
Dann sollte man ihn aber doch lieber wieder ganz ausbauen. So hat er doch einen ziemlich eingeschränkten Nutzen, oder?

Ansonsten kann er vielleicht wenigstens einen Tooltip haben, der erklärt worauf er sich nur auswirkt.

**Comment by BourgeoisLab** [comment]
Je nach Bildschirmgrösse ist es schon sinnvoll für die Darstellung im Programm. Es ist nicht einfach 10zoll und 4k Bildschirme gleich gut abzudecken.

**Comment by LondonRain** [comment]
Okay. Vielleicht trotzdem einen Tooltip der das erklärt, dass es sich nur auf die GUI auswirkt? Das wäre schon mal hilfreich.
