### ISSUE TITLE
Braudaten: Tooltips von Zielstammwürze

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#141]
Die müssten mal kontrolliert werden. Da scheinen nicht immer die korrekten Texte zu dem entsprechenden Element zu stehen.

![grafik](https://user-images.githubusercontent.com/33151586/100542550-e5d76780-324a-11eb-8dfe-aba2205f29f1.png)

Bei dem mittleren Brix (Kochende) steht im Tooltip was von Kochbeginn. Bei dem unteren Brix (Anstellen) steht im Tooltip was von Kochbeginn. Die Platotooltips daneben stimmen aber,

**Comment by Rasinari** [comment]
Wird angepasst. Danke

**Comment by BourgeoisLab** [comment]
korrigiert
