### ISSUE TITLE
CO2 Gehalt beim Erstellen der Etiketten inkorrekt

### ISSUE THREAD

**Issue by Ventusfahrer** [kleiner-brauhelfer/kleiner-brauhelfer-2#142]
![Bildschirmfoto von 2020-12-01 08-59-29](https://user-images.githubusercontent.com/5901190/100713602-d2e0a680-33b4-11eb-9282-76575512db61.png)

Hier wird sie mit 0.0 g/l ausgegeben. Das kann so nicht stimmen. Ohne Berücksichtigung der Zuckergabe wären es aktuell 1,6 g/Liter, mit Berücksichtigung der Zuckergabe 5,0 g/l.

Die Datenbank kann zur Not zur Analyse zur Verfügung gestellt werden.

Danke für's Reinschauen!

**Comment by BourgeoisLab** [comment]
Auf dem Label werden die Ist-Werte angezeigt und nicht die, aus dem Rezept. Du hast wahrscheinlich noch keine Nachgärungswerte eingetragen und es wird entsprechend 0 angezeigt.

**Comment by Ventusfahrer** [comment]
> Auf dem Label werden die Ist-Werte angezeigt und nicht die, aus dem Rezept.

ah, das bringt uns der Ursache schon ein ganzes Stück weiter.

Ich arbeite mit Flaschengärung und hatte in der Vergangenheit noch nie irgendwelche Werte im Gärverlauf - Nachgärung erfasst. Zumindest unter der Version 1.x wurde dann wohl der Wert vom Rezept ausgegeben und nicht der aus dem Gärverlauf.

Ich habe keinen Manometer für eine Gärflasche und kann den CO2 Druck daher nicht messen und damit den Gärverlauf der Nachgärung nicht dokumentieren. Vielleicht sollte man in diesem Fall (kein weiterer Wert in der Nachgärung erfasst) den CO2-Zielwert des Rezepts (ergänzt durch ein **\*** hinter dem Wert) dann ausgeben?

**Comment by BourgeoisLab** [comment]
> Vielleicht sollte man in diesem Fall (kein weiterer Wert in der Nachgärung erfasst) den CO2-Zielwert des Rezepts (ergänzt durch ein * hinter dem Wert) dann ausgeben?

Das will ich nicht machen, nein. Das führt zu noch mehr Verwechslung. Du kannst das Etikette editieren und stattt {{Sud.CO2}}
 {{Rezept.CO2}} verwenden.

> Weiterer Einwurf: Der Alkohol-gehalt auf dem dem Etikette scheint jedenfalls wieder aus dem Rezept und nicht der Gärdaten-Messung zu stammen?

Sehe ich nicht so. Es wird der Wert vom Sud angezeigt. Zumindest auf den offiziellen Etiketten.
