### ISSUE TITLE
Wunschliste:  Vorlagenspezifische Speicherung der Größen-Parameter von Etiketten

### ISSUE THREAD

**Issue by Ventusfahrer** [kleiner-brauhelfer/kleiner-brauhelfer-2#143]
Ich vermute mal, dass die Initialwerte Breite und Höhe der Etikettengröße aus der SVG-Grafik berechnet werden und der horizontale und vertikale Abstand Hardcoded sind.

Jedenfalls wird eine Änderung dieser 4 Parameter Sud-spezifisch gespeichert. 

Ich würde mir eine Vorlagenspezifische Speicherung der Parameter wünschen. Die Parameter beziehen sich auf die Geometrie der Vorlage und haben relativ wenig mit den Sud-spezifischen Werten zu tun. 

Ich jedenfalls renne bei der Verwendung von neuen Rezepten regelmäßig in das Problem, dass ich die Werte wieder manuelle ändern muss, obwohl sie mit dem Rezept selbst eigentlich nichts zu tun haben.

**Comment by BourgeoisLab** [comment]
Der horizontale und vertikale Abstand wird vom letzten (gleichen) Etikett übernohmen. Das könnte ich für die Grösse auch machen.

Eine eigentliche "Vorlagenspezifische Speicherung der Parameter" werde ich sehr wahrscheinlich nicht machen.

**Comment by BourgeoisLab** [comment]
Erledigt mit b714a00.

**Comment by Ventusfahrer** [comment]
Vielen Dank dafür!
Hilft schon enorm!
