### ISSUE TITLE
Wunschliste: Etiketten: "Bearbeiten"-Button zum Bearbeiten mit externem SVG-Editor

### ISSUE THREAD

**Issue by Ventusfahrer** [kleiner-brauhelfer/kleiner-brauhelfer-2#144]
Mit dem aktuellen Editiermodus werden sich vermutlich nur Codier-Spezialisten anfreunden.

Für alle anderen wäre es wünschenswert, ein Etikett optional durch Drücken eines Buttons (Bearbeiten - neben den Öffnen und Aktualisieren Buttons) mit einem externen SVG-Editor ändern zu können. Falls per MIME kein Editor konfiguriert ist, dann wäre eine Dialog-Box mit kopierbarem vollen Pfad der aktuellen Etiketten-SVG-Datei wünschenswert.

Derzeit kommt man auf den Pfad der Datei per Umweg: in Editiermodus wechseln, dann steht der Pfad auf die SFG-Datei ganz unten in der Form, allerdings nicht kopierbar.

**Comment by BourgeoisLab** [comment]
Der Editor ist natürlich kein SVG Editor Ersatz.
Ich glaube, man kann per MIME nicht zwischen öffnen und editieren unterscheiden.
Der Pfad im Editiermodus ist jetzt selektierbar und wenn man darauf klickt wird es mit dem Standardprogramm geöffnet.

**Comment by BourgeoisLab** [comment]
Erledigt mit b714a00.
