### ISSUE TITLE
Subtle bug?

### ISSUE THREAD

**Issue by realholgi** [kleiner-brauhelfer/kleiner-brauhelfer-2#145]
https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/blob/f920ea2994acd16456fd6bad0fd221745816a227/kleiner-brauhelfer-core/proxymodel.cpp#L122

muss das hier nicht `proxyModel` anstatt `model` heissen?

**Comment by BourgeoisLab** [comment]
Sieht so aus ja. Es sollte sogar abstürzen, weil in dem Fall model = NULL ist.

Wie bist du darauf gekommen? Absturz?

**Comment by realholgi** [comment]
Kein Absturz, habe mal Clazy drüber laufen lassen. Das war das auffälligste  ;-)

**Comment by BourgeoisLab** [comment]
Da sieht man, dass ich kein gelernter Programmierer bin. Hatte keine Ahnung was Clazy ist:).
Ich werde es aber auch noch ausprobieren.

**Comment by realholgi** [comment]
fixed with 7409cc4fd820c43ffa907ef10f2e8f6007e26666
