### ISSUE TITLE
Maischplan: Abmaischen ist als "Temperaturrast" kategorisiert.

### ISSUE THREAD

**Issue by Monotom89** [kleiner-brauhelfer/kleiner-brauhelfer-2#147]
Im Maischplan des Rezepts kann "Abmaischen" nur als "Temperaturrast" hinzugefügt werden. Das finde ich verwirrend, da das Abmaischen an sich ja keine Rast ist sondern eben der Abschluss des Maischeprozesses. Es sollte direkt als eigene Kategorie aufgeführt werden, so wie ja auch das Einmaischen. 

<img width="506" alt="Bildschirmfoto 2020-12-28 um 19 06 02" src="https://user-images.githubusercontent.com/9129796/103234550-420fd300-4940-11eb-8eb5-5413a772e9c1.png">
<img width="168" alt="Bildschirmfoto 2020-12-28 um 19 06 09" src="https://user-images.githubusercontent.com/9129796/103234556-45a35a00-4940-11eb-972c-e6dee5d5847d.png">

**Comment by BourgeoisLab** [comment]
Die Kategorie heisst nicht mehr "Temperaturrast", sondern "Aufheizen". Du solltest dein Programm updaten.
