### ISSUE TITLE
Hilfe im Tab Gärverlauf: Im Text sind die Tabs Braudaten und Abfülldaten vertauscht

### ISSUE THREAD

**Issue by riegelbrau** [kleiner-brauhelfer/kleiner-brauhelfer-2#148]
Hallo,
nach meiner Überprüfung muss das umgekehrt lauten:
![grafik](https://user-images.githubusercontent.com/73437730/103465305-7e757180-4d3a-11eb-82f9-790701e5f80e.png)

Gruß Christoph

**Comment by BourgeoisLab** [comment]
Erledigt.
