### ISSUE TITLE
Aktuelles Jahr

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#149]
Auf Anregung von ralfsteck schlage ich einen Schalter "aktuelles Jahr" im Tab Sudauswahl vor, der alle anderen Jahre ausblendet. Ebenfalls würde ein Filter für die Sude eines jeden Jahres Sinn machen.
Diskussion: Schafft Übersicht bei langen Sudlisten.

**Comment by BourgeoisLab** [comment]
Die jetzige Eingabemöglichkeit mit Datum "von" und "bis" ist flexibler. Zusätzliches Eingabefeld bläht die Filtermöglichkeiten nur auf.
