### ISSUE TITLE
Rohstoffe in Rezepten finden und anzeigen

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#152]
Der Kleine Brauhelfer warnt beim Löschen eines Rohstoffes in der Rohstoffliste, dass diese in bestehenden, ungebrauten Rezepten vorhanden ist. Aus der Warnmeldung geht jedoch nicht hervor, in welchem Rezept dies erfolgt.

Um hier einen höhere Informationsqualität anzubieten, wären folgende Verbesserungen denkbar:
1. Die Warnmeldung listet die Rezepte auf, die den zu löschenden Zusatz enthalten
2. Eine zusätzliche Suchfunktion listet die Rezepte auf, in denen der Rohstoff in allen Zuständen (ungebraut/gebraut/ausgetrunken)) verwendet wird
3. Eine zusätzliche Spalte extrapoliert automatisch die Verwendung eines Rohstoffes in einem Rezept in der Rohstoffliste und aktualisiert sich automatisch

**Comment by BourgeoisLab** [comment]
Lösung 1 scheint mir am vernünftigsten.

**Comment by Rasinari** [comment]
> Lösung 1 scheint mir am vernünftigsten.

d'accord. Es sollte NACH dem Löschen aber irgendwie festgehalten werden. Oder nicht? Beware den schnellen Klick

**Comment by BourgeoisLab** [comment]
Nach dem Löschen ist es zu spät. Historien von Veränderungen werden in der Datenbank nicht geführt.
Man kann aber immer alle gemachten Änderungen seit dem Programmstart rückgängig machen. Nachdem aber gespeichert wurde, ist diese Option weg.

**Comment by Rasinari** [comment]
Verstanden: Dann wäre eine Option 5 nützlich, mit der die Zusätze VOR dem Löschen ausgetauscht werden können. Also via dem Popup, das die Rezepte auflistet.

**Comment by BourgeoisLab** [comment]
Erledigt mit 2bf170398c2c34df95265ba5462782d104f5c2af.
Beim Dialog werden jetzt die betroffenen Sude angezeigt. Mehr werde ich im Moment nicht machen. Vielleicht später mal...
