### ISSUE TITLE
Initialwert Abfülldatum

### ISSUE THREAD

**Issue by Ventusfahrer** [kleiner-brauhelfer/kleiner-brauhelfer-2#153]
Hi,
ich habe jetzt schon zwei mal vergessen das Abfülldatum korrekt einzutragen.

Da es leider mit dem Braudatum vorbelegt ist, steht dann ein falsches Datum und ein falsche Uhrzeit in der Datenbank und ist so einfach nicht mehr zu korrigieren.

Ich würde es begrüßen, dass die Vorbelegung des Feldes mit dem aktuellen Datum und Uhrzeit erfolgt, solange der Sud gebraut, aber noch nicht abgefüllt ist. 

Da die Pflege der Abfülldaten normalerweise relativ zeitnah zum Abfüllen erfolgt (ich schaue im Normalfall alleine wegen der Zuckergabe vor dem Abfüllen rein und danach um die abgefüllte Menge zu erfassen), liegt man nicht so weit weg vom Abfüllzeitpunkt wie mit der Vorbelegung durch das Braudatum.

Vielen Dank!

**Comment by BourgeoisLab** [comment]
Das war früher so (Vorbelegung mit aktuellem Datum) und wurde geändert. Wieso weiss, ich nicht mehr genau:). Nochmals umstellen werde ich wahrscheinlich nicht.

`... und ist so einfach nicht mehr zu korrigieren.`
Wenn man weiss wie, ist es einfach:
- Menu Sud/Eingabefelder entsperren
- Datum ändern
- Menu Sud/Eingabefelder sperren

Ich könnte im Bestätigungsdialog beim Klicken auf "Sud abgefüllt" das angegebene Datum anzeigen. Vielleicht bemerkt man dann den Fehler.

**Comment by BourgeoisLab** [comment]
Ich habe mir den Code genauer angeschaut. Es gibt eigentlich keinen Grund den Abfülldatum mit dem Braudatum zu vorlegen.

**Comment by Ventusfahrer** [comment]
Danke, wäre schön, wenn das möglich wäre. Man gewöhnt sich ja an vieles, aber ich denke, dass dieser Bedienungsfehler gerade Neulingen doch öfter passieren wird. Und jedesmal ein Forum bemühen, um auf die Entsperr-Funktion aufmerksam gemacht zu werden...

Der Tip hat mit dem "Entsperren" hat mir schon mal weitergeholfen (nachdem ich das Problem beim ersten Auftreten schon mal mit sqlite3 am Record in der Sud Tabelle gefixt hatte).

Jetzt weiß ich wenigstens, wie ich den C02-Gehalt nach dem Brauen vor dem Abfüllen noch im Rezept ändern kann. Das hätte ich gerne schon mal gebraucht, aber auch hier ist nach "gebraut" keine Änderung mehr möglich. Ich vermute mal, dass die Carbonisierungsberechnung diese Änderung berücksichtigt und keine Dateninkonsistenz erzeugt wird (vor der ja vor der Änderung gewarnt wird).

**Comment by BourgeoisLab** [comment]
Erledigt mit cf7b9998bcde6f3baa199e4a5d1ab33273afdf70.
