### ISSUE TITLE
Export eines Suds (Kleiner Brauhelfer v2.2.2) im Format MaischeMalzundMehr -> 1 Rast zu viel

### ISSUE THREAD

**Issue by BIB2021** [kleiner-brauhelfer/kleiner-brauhelfer-2#154]
Hallo,

beim Export eines Suds (Kleiner Brauhelfer v2.2.2) im Format MaischeMalzundMehr (Jason) wird für das Einmaischen eine zusätzliche Rast mit der Werten des jeweiligen Schrittes im Maischplan erzeugt.

In Version 2.1 3

Beispiel v2.2.2: 
Für die "Infusion_Einmaischtemperatur": "59" wird zusätzlich die Rast 1 erzeugt 

...
    **"Infusion_Einmaischtemperatur": "59",**
    "Infusion_Hauptguss": "12.1",
    **"Infusion_Rasttemperatur1": "59",**
    "Infusion_Rasttemperatur2": "57",
    "Infusion_Rasttemperatur3": "64",
    "Infusion_Rasttemperatur4": "72",
    "Infusion_Rasttemperatur5": "78",
    **"Infusion_Rastzeit1": "0",**
    "Infusion_Rastzeit2": "15",
    "Infusion_Rastzeit3": "40",
    "Infusion_Rastzeit4": "30",
    "Infusion_Rastzeit5": "0", 

ist in v.2.1.3 noch korrekt:

   **"Infusion_Einmaischtemperatur": "59",**
    "Infusion_Hauptguss": "25.9",
    "Infusion_Rasttemperatur1": "57",
    "Infusion_Rasttemperatur2": "64",
    "Infusion_Rasttemperatur3": "72",
    "Infusion_Rasttemperatur4": "78",
    "Infusion_Rastzeit1": "15",
    "Infusion_Rastzeit2": "40",
    "Infusion_Rastzeit3": "30",
    "Infusion_Rastzeit4": "0", 
 
Könnt ihr das bitte korrigieren.

Vielen Dank
Gruß
Uwe

**Comment by BourgeoisLab** [comment]
Für den KBH ist Einmaischen auch eine Rast und hat entsprechend auch eine Zeit. Deswegen taucht es auf. Dass die Formate nicht 100% kompatibel sind, liegt in der Natur der Sache.

**Comment by BourgeoisLab** [comment]
Erledigt mit c59b9be.
