### ISSUE TITLE
kaputtes Bild?

### ISSUE THREAD

**Issue by ivh** [kleiner-brauhelfer/kleiner-brauhelfer-2#156]
Die reichte Spalte bei der Sudauswahl hat bei mir das Symbol eines kaputten Bildes beim Bierfarben-Viereck:
![image](https://user-images.githubusercontent.com/134957/105575971-edf5e400-5d6f-11eb-9d81-c926b7e98156.png)

Der Spickzettel genauso. Wenn ich diese Zeile aus dem Template (resetted) entferne, geht es weg.
`<img class="glas" style="padding:0px;margin:-4px;width:100px;height:100px">`

**Comment by BourgeoisLab** [comment]
Die Pfade haben sich geändert. Du musst die CSS Datei "style_hell.css" zurücksetzen.

**Comment by ivh** [comment]
Ah, danke! Das geht nur einzeln, nicht alle auf einmal, oder?

**Comment by ivh** [comment]
Oh, "Ansicht zurücksetzten" scheint dies zu tun. Never mind. :)

**Comment by BourgeoisLab** [comment]
Genau. Zurücksetzten, setzt nur die aktuell ausgewählte Datei zurück.
