### ISSUE TITLE
Farblegende in der Sudauswahl

### ISSUE THREAD

**Issue by psytrap** [kleiner-brauhelfer/kleiner-brauhelfer-2#158]
Jeder Sud kennt mehrere Stadien: Rezept - Gebraut - Abgefüllt - Verbraucht. Zur schnelleren Orientierung gibt es in der Sudauswahl eine farbliche Codierung. Ohne Legende bleibt dem Nutzer die Zuordnung Farbevs. Stadium ein Rätsel.

Die Änderung würde ich selbst machen und bräuchte nur ein OK, das so eine Funktion erwünscht ist.

Grundsätzlich sehe ich drei Lösungsmöglichkeiten:
1. Die Umstellung von Farbcodierung auf Symbole in der Sudliste
2. Die Checkboxen in der Filterleiste haben die entsprechende Hintergrundfarbe
3. Über der Sudliste liegt rechts unten eine kleine Legendenbox.
Die Option #2 wäre meine Erstewahl.

**Comment by BourgeoisLab** [comment]
Du scheinst die gleichen Gedanken, wie ich zu haben... und zur gleichen Zeit.
Option #2 wurde in 2.2.3 (heute released) umgesetzt.
