### ISSUE TITLE
Falsche Berechnung unter Woche

### ISSUE THREAD

**Issue by markussoeth** [kleiner-brauhelfer/kleiner-brauhelfer-2#159]
Hallo,
vorab.. vielleicht liegt es auch an mir, da ich die Software noch nicht so lange Nutze.
Ich habe das Problem, das bei dem Sud "Helles" hier im Screenshot angezeigt wird, ich wäre in der 2. Woche und müsste noch 30 Tage warten. Abgefüllt wurde am 26.12.2020 als vor 4 Wochen.. 
Liegt da vielleicht ein Berechnungsprolem vor?
![Clipboard 3](https://user-images.githubusercontent.com/306641/105638144-66909980-5e71-11eb-80a0-ee2978d87aa9.png)

**Comment by BourgeoisLab** [comment]
Siehe #87 
Reifezeit/Woche beginnt für den kbh nicht ab abfülldatum, sondern letzte nachgärmessung (=fertig gegärt)

**Comment by markussoeth** [comment]
Ahh OK! Danke für die Info. Dann ist das kein Issue und ich schliesse den nun wieder
