### ISSUE TITLE
Runtime-Error mit Version 2.2.3 auf Linux XUBUNTU 20.04

### ISSUE THREAD

**Issue by schuessm** [kleiner-brauhelfer/kleiner-brauhelfer-2#160]
Hallo,
nach der Installation der neuen Version bekomme ich folgenden Fehler:

./kleiner-brauhelfer-2: symbol lookup error: ./kleiner-brauhelfer-2: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version Qt_5

Ich benutze QT5.15

**Comment by BourgeoisLab** [comment]
Die version 2.2.2 ging/geht noch?

**Comment by schuessm** [comment]
Ja, die geht einwandfrei. Arbeite jetzt mit dem APPIMAGE-File, das funktioniert logischerweise auch. Trotzdem hätte ich es gern installiert

**Comment by BourgeoisLab** [comment]
Der kbh wurde mit Qt 5.15.0 kompiliert. Wahrscheinlich deswegen.

Diese automatisch kompilierte Version wurde mit Qt 5.15.2 kompiliert:
https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/actions/runs/505690427
Ist nicht sehr elegant, aber du könntest die executable einfach ersetzen.

Alternativ die Qt Libraries 5.15.0 installieren...

**Comment by schuessm** [comment]
ok. Danke! Davor hatte ich die 5.15.0, dann dachte ich Du nutzt vielleicht eine neuere Version und habe sie geupdatet ;-). Aber ich teste.

**Comment by BourgeoisLab** [comment]
Genau deswegen habe ich kein update gemacht:). Ich schreibe immer dazu, wenn Qt aktualisiert wird.

**Comment by schuessm** [comment]
So getestet. Der link geht auf das APPImage File vom Samstag!? Habe ich da jetzt was falsch gemacht? Bei starten wollte er zwar einige files ..._nl.html etc ändern, startet aber trotzdem nicht. Das offizielle APPImage File läuft ja auch bei mir nur das deb geht nicht nach der Installation

**Comment by BourgeoisLab** [comment]
Ach sorry. Ich dachte mit dem Link wird das DEB heruntergeladen. Du kannst aber das executable aus der heruntergeladenen AppImage extrahieren. AppImage ist eigentlich ein komprimierter Ordner.

Die AppImage funktioniert, weil Qt 5.15.0 dort eingebunden ist.

**Comment by schuessm** [comment]
Ok. Folgendes Verhalten:
1. mit der Original-2.2.3-deb geht es nicht
2. mit dem Update geht es auch nicht
3. Mit Update ging es nachdem ich den alten .config Ordner gelöscht habe bis auf die DB, dann ging es. Also die bin aus dem APPIMAGE verwendet, damit ging's dann.

Vielen Dank!
