### ISSUE TITLE
Rohstoffe: Hefemengen größer 11/10g Päckchen

### ISSUE THREAD

**Issue by schuessm** [kleiner-brauhelfer/kleiner-brauhelfer-2#163]
Hallo,
es wäre super, wenn man in den Rohstoffen auch Hefemengen pflegen könnte die nicht den Päckchen entsprechen, so z.B. 100g Trockenhefe, davon pro 10l 6g oder so ähnlich. Gewisse Hefe nehme ich immer in größeren Gebinden, daher wäre beides praktisch, man bräuchte ja nur die "Einheit" Päckchen, Gramm, (Kilogramm)), bisher habe ich es halt immer mit den 11g Päckchen gerechnet, d.h. bei 250g habe ich abgerundet  22 Päckchen eingegeben.

**Comment by BourgeoisLab** [comment]
Was hindert dich daran direkt 250 einzugeben (statt 22)? Eine "Einheit" Hefe ist im Programm nicht fix definiert. Bei Würzemenge kannst du dann 0.6 Liter eingeben (10L => 6g, 1L => 0.6g). 
Nur beim Preis kann es ungenau werden, wenn eine Einheit weniger als ein Cent ist.

**Comment by Rasinari** [comment]
Das macht keinen Sinn, da je nach Biertyp die Hefemengen vollkommen unterschiedlich sind. Ein untergäriges Strong Lager benötigt Faktor 2,00, ein einfaches Ale nur Faktor 0,75. Nicht umsonst verweisen fast alle Hefehersteller auf unterschiedlichen Hefemengen bei unterschiedlicher Stammwürze.

Daher gilt die Aussage: Eine Einheit Hefe gibt es nicht.
