### ISSUE TITLE
Etiketten: altes SVG wird nicht mehr geladen, Crash beim PDF-Druckversuch

### ISSUE THREAD

**Issue by Ventusfahrer** [kleiner-brauhelfer/kleiner-brauhelfer-2#164]
ich verwende schon seit langem ein eigenes svg - irgendwann mal aus einer Vorlage an meine Bedürfnisse angepasst und nochmal für die 2er Version modifziert.

Seit 2.2.x wird es plötzlich nach der Auswahl nicht mehr im Fenster angezeigt, beim anschließenden Druck-Versuch ins PDF-File crasht der kb.
Ich arbeite mit dem App-Image auf Ubuntu 20.10 (die Ansprüche an die installierte QT-Version für die Nutzung des Debian Packages ist für meinen Geschmack zu hoch (die in meinem Ubuntu, die aktuellste Version, liegt drunter).
Im Terminal kann man die stdio die Meldung
   Speicherzugriffsfehler (Speicherabzug geschrieben)
sehen. 
Ich habe das SVG-File mal angehängt. 

Wie kann ich euch weiter bei der Fehlerursachenfindung unterstützen?

Beste Grüße

Peter
[7v-svg.zip](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/5922009/7v-svg.zip)

**Comment by Ventusfahrer** [comment]
einen kleine Schritt weiter:

Ursache ist wohl ein dreifaches Klammern der Tags "{{{Sud.Name}}}" statt "{{Sud.Name}}" im SVG-File.

Trotzdem sollte die App nicht crashen und eine Fehlermeldung in Form eines Popups warum nix geladen, angezeigt wird wäre sehr hilfreich.

**Comment by BourgeoisLab** [comment]
Bei mir stürzt es nicht ab. Ich kann etwas einbauen, aber ohne Garantie, dass es funktioniert, da ich es nicht reproduzieren kann.

**Comment by BourgeoisLab** [comment]
Erledigt mit 0670e7901d5f42fb498ef81c0a421ad125ba79ac.
