### ISSUE TITLE
Feste Maßeinheiten bei Wasserzusätzen

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#165]
Die Einheitenwahl im Reiter Wasseraufbereitung wirkt sich nicht nicht auf die Zutat bei der Wasseraufbereitung aus. Es wird kein Unterschied zwischen fest und flüssig gemacht. Chemisch ist dies mitunter falsch. 

Beispiel: Cacliumcholorid Dihydrat hat ein spezifisches Gewicht von 0,83. Der Faktor -0,0927 soll bei g/l 1dH absenken. Dieser Wert ändert sich auch nicht bei mg/l.

Die meisten Brausalze haben flüssig andere Eigenschaften und andere spezifische Gewichte. Ein Beispiel ist wiederum CaCl2, dass in Braushops in 33%iger Lösung angeboten wird.

Vorschlag: Jedem Brausalz und jeder Brausäure soll jeweils eine einzige Einheit zugewiesen werden: Feststoffe g/l, Flüssigkeiten ml/l. Dies entspricht der Braupraxis von Hobbybrauern und Craftbrauereien bis zu 300l-Klasse. Alle anderen Optionen werden zugunsten der Verständlichkeit und der Fehlervermeidung gestrichen.

**Comment by BourgeoisLab** [comment]
Erledigt mit 0670e7901d5f42fb498ef81c0a421ad125ba79ac.
