### ISSUE TITLE
kleiner Verbesserungsvorschlag Import Popup

### ISSUE THREAD

**Issue by Ventusfahrer** [kleiner-brauhelfer/kleiner-brauhelfer-2#166]
man könnte beim Tooltip über dem URL Feld /Download Button ergänzen:

Bei MMM kopiert man die Download-URL indem man mit der rechten Maustaste auf den "JSON Export" Button/Link klickt und dann "Adresse des Links kopieren" wählt. Anschließend den kopierten Link mit Einfügen in das URL-Feld kopieren.

Brewers Friend: Rezept öffnen, Export - Beerxml, auf der nächsten Seite rechtsklick über dem Link, "Adresse des Links kopieren"

**Comment by BourgeoisLab** [comment]
Erledigt mit 0670e7901d5f42fb498ef81c0a421ad125ba79ac.
