### ISSUE TITLE
Automatische Sicherung

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#168]
In den KBH sollte eine automatische Sicherung eingebaut werden. Wünschenswert wären wählbare Zeitintervalle in den Einstellungen.

Diskussion: Das Feature folgt den Erfordernissen von Green IT. Im KBH muss derzeit immer noch manuell gesichert werden. Wird dies vergessen, kann z.B. der Computer in der Nacht nicht herunterfahren. Gleiches gilt für Update-Prozesse in der Nacht.

**Comment by LondonRain** [comment]
Automatisches Speichern find ich nur sinnvoll, wenn es auch einen Undo Redo Mechanismus gibt. Ansonsten eimert man sich da ganz schnell mal Daten. Das wiederum klingt nach ziemlich viel Aufwand. Ich könnte auf beides sehr gut verzichten.

**Comment by Rasinari** [comment]
Deswegen mein Vorschlag die Option an/aus einzubauen. Undo/Redo ist nicht kausal.
