### ISSUE TITLE
Datumsformat einstellen 

### ISSUE THREAD

**Issue by dystechnic** [kleiner-brauhelfer/kleiner-brauhelfer-2#169]
Hallo,

Ich verwende KBH auf einem Linux-System mit Englisch als spracheinstellung. Ich benutze KBH auf Niederländisch.
Wahrscheinlich bekomme ich aufgrund der englischen einstellung des systems alle datumsfelder im englischen format. MM/DD/YY. Dies wird auch auf etiketten in diesem format gedruckt.
Ist es möglich, die darstellung des datums unabhängig von der spracheinstellung des systems zu ändern, auf dem KBH ausgeführt wird? In jedem fall möchte ich das datum im DD/MM/YY Format auf die Etiketten drucken können.

Grüße,

Ed.

**Comment by BourgeoisLab** [comment]
<img width="404" alt="Unbenannt" src="https://user-images.githubusercontent.com/9480307/109383845-8c361600-78e9-11eb-8436-e17dbb693a20.PNG">

Elerdigt mit 4c918f3.
