### ISSUE TITLE
Endvergärungsgradberechnung

### ISSUE THREAD

**Issue by Bohreromir** [kleiner-brauhelfer/kleiner-brauhelfer-2#171]
Der Tooltip des Eingabefeld "Vergärungsgrad" sagt das es sich um den sEVG handelt.
![image](https://user-images.githubusercontent.com/40412303/108207206-b6d4e180-7127-11eb-8b03-bb7ca00377af.png)

Wenn man jetzt im Tab Abfülldaten nachschaut wird dieser auch als "erwartet" übernommen. Um die beiden Werte "erwartet" und "gemessen" vergleichbar machen zu können, würde ich erwarten, das sich beim Gemessenen auch um den sEVG und nicht den tEVG handelt.
![image](https://user-images.githubusercontent.com/40412303/108207139-a1f84e00-7127-11eb-8713-3d46f1f48bc8.png)

Übernommen wird aber anscheinend der tEVG
![image](https://user-images.githubusercontent.com/40412303/108207163-aa508900-7127-11eb-8647-64f2efeebe68.png)

**Comment by Bohreromir** [comment]
Achso, V2.2.3 unter Ubuntu

**Comment by BourgeoisLab** [comment]
Bereits erledigt mit ab5ca10b49865925f53ba84740872c0a46d5dd2f.
