### ISSUE TITLE
Negative Gärtemperatur

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#173]
Ich schlage vor in den KBH eine negative Gärtemperatur einzubauen. Negative Gärtemperaturen kommen beim Hopfenstopfen zum Einsatz. Auch in anderen Bereichen wie Eisbock ist eine praktische Anwendung denkbar.

Derzeit ist bei 0°C Schluss. Damit kann ein Teil einer extrem fruchtigen Kalthopfung, die oft im Bereich von -2°C bis 2°C gefahren wird, im KBH nicht umgesetzt werden. -2°C ist auch im Profibereich sehr beliebt.

**Comment by BourgeoisLab** [comment]
Erledigt mit 4c918f3.
