### ISSUE TITLE
Erweitertete Dokumentationsmöglichkeit

### ISSUE THREAD

**Issue by BourgeoisLab** [kleiner-brauhelfer/kleiner-brauhelfer-2#176]
Freitext mit Formatierung (HTML oder Markdown) inklusive Möglichkeit für Bilder.

**Comment by Rasinari** [comment]
Formatierung mit HTML ist wünschenswert, wenn entsprechende Buttons (Gutenberg) eingebunden sind. Sonst nicht, weil zu wenig anwenderfreundlich.

**Comment by BourgeoisLab** [comment]
Erledigt mit e166e7e06ec5b8b14413339fe6521861bd36ee10.
