### ISSUE TITLE
Spalte "Reif in" Wochen/Tage

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#178]
Im Tab Sudauswahl sollte eine Spalte "Reif in" Wochen/Tagen aufscheinen, die bei reifenden Suden automatisch herunter zählt.

Die Berechnung erfolgt dabei entweder ab 2/3 Hauptgärung, also 2./3. Tag nach Braudatum oder ab Abfülldatum. Dies ist in den Einstellungen oder anderer Stelle wählbar.

**Comment by BourgeoisLab** [comment]
Das gibt es schon länger.

In Version 2.3 kann der Beginn der Reifung selber bestimmt weden. Siehe Reiter Abfülldaten.

**Comment by Rasinari** [comment]
> Das gibt es schon länger.
> 
> In Version 2.3 kann der Beginn der Reifung selber bestimmt weden. Siehe Reiter Abfülldaten.

Sehr schlau. Ein eindeutiger Gewinn. Dann sollte das jetzt nur noch im Tab **Sudauswahl** visualisiert werden

**Comment by BourgeoisLab** [comment]
Wie gesagt, das gibt es schon. Einfach Spalte einblenden.

**Comment by Rasinari** [comment]
I see it. Die Message ist trotzdem noch nicht angekommen. War sie zu verquast formuliert? Derzeit wird nur die gesamte Reifezeit angezeigt, nicht aber die im Tab festgelegte Reifedauer. Aus diesem Wert geht **nicht** hervor, ob das Bier reif ist.

Optimal wäre eine Meldung **reif** und ab da eine Meldung "reif seit xxx Wochen". :-)

**Comment by BourgeoisLab** [comment]
<img width="654" alt="Unbenannt" src="https://user-images.githubusercontent.com/9480307/112746687-d37af980-8fb0-11eb-9454-0aa15ce8c91a.PNG">
Wird doch. Auf den Präfix "reif seit..." habe ich aber verzichtet.

**Comment by Rasinari** [comment]
Bedankt. Dann ist das ein Fehler in der Mac-Version. Da gibt es das nicht. Schade.

**Comment by Rasinari** [comment]
Edit: Fehlerquelle gefunden (Mac-Version):

1. "reif in" wird nur mit angehaktem Button "abgefüllt" angezeigt und abgehakten Button "alle"
2. bei Button "alle" verschwindet "reif in"
3. die Information "reif seit" fehlt in allen Filterungen

**Comment by maxliemant** [comment]
In der Linux-version wird der Wert abgeschnitten, wenn die Spalte zu klein ist und nicht wie bei dir mit einem Zeilenumbruch dargestellt.

![image](https://user-images.githubusercontent.com/45594714/114428921-13e79380-9bbd-11eb-94b5-c1678a81e327.png)

Version 2.3.0 als AppImage
Ubuntu Ubuntu 20.04.2

**Comment by Rasinari** [comment]
Das Verhalten ist in der Mac-Version identisch:
<img width="292" alt="Bildschirmfoto 2021-04-12 um 18 44 49" src="https://user-images.githubusercontent.com/51321250/114430981-485c4f00-9bbf-11eb-8b97-63fe00223a85.png">

In der Mac-Version, vermutlich aber bei allen, ein Plural-Fehler; es muss "Tagen" heißen, nur bei 1 = Tag:
<img width="194" alt="Bildschirmfoto 2021-04-12 um 18 41 46" src="https://user-images.githubusercontent.com/51321250/114431114-6a55d180-9bbf-11eb-8f7f-4a908d6276de.png">

**Comment by BourgeoisLab** [comment]
Ich glaube, das kann man schliessen, oder?

**Comment by Rasinari** [comment]
Ja, in 2.3.2 gefixt.
