### ISSUE TITLE
Beispielsud Verdampfungsrate

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#180]
Derzeit ist im Beispielsud die Verdampfungsrate mit 2,9l/h eingestellt. Das ist zu hoch.
Der Wert soll auf realistische 2,0l/h eingestellt werden.

**Comment by BourgeoisLab** [comment]
Die Verdampfungsrate für den Beispielsud ist bereits auf 2.0l/h. Ich weiss, woher deine 2.9l/h kommen.

**Comment by Rasinari** [comment]
Woher?

**Comment by BourgeoisLab** [comment]
Habe "nicht" vergessen:). 
Ich weiss **nicht**, woher deine 2.9l/h kommen.

**Comment by Rasinari** [comment]
Dann kann das Ticket geschlossen werden :-)
War wichtig für Anfänger.
