### ISSUE TITLE
Links in Tooltips funktionieren nicht

### ISSUE THREAD

**Issue by BurtMC** [kleiner-brauhelfer/kleiner-brauhelfer-2#181]
Bei der Version 2.3 für Linux (AppImage) sind die Links in den Tooltips zwar als Link dargestellt, haben aber keine Funktion.

![grafik](https://user-images.githubusercontent.com/17658461/113352561-b477c100-933c-11eb-8c51-223e53f11c02.png)

**Comment by Rasinari** [comment]
Dieses Verhalten ist auch bei macOS bekannt.

**Comment by BourgeoisLab** [comment]
Erledigt mit a3365267c487806f4f413ca496ad3b9451f96e35.
