### ISSUE TITLE
Links clickable

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#183]
Unter Linux und macOS sind jedwede Hyperlinks sowohl in den Toolips, den Linkfeldern Rohstoffe und den Freitextfeldern nicht clickable.

Sofern es sich um ein Verhalten von QT handelt, sollte dies gefixt werden.

**Comment by BurtMC** [comment]
Im Popup für die Eingabe des Malz-pH-Wertes funktioniert der Link auf die MMuM-Seite.

**Comment by BourgeoisLab** [comment]
In der Rohstoffliste funktioniert der Link mit CTRL+Mousclick.

**Comment by Rasinari** [comment]
> In der Rohstoffliste funktioniert der Link mit CTRL+Mousclick.

Aber nicht unter Mac. CTRL auf Mac ist der Rechtsklick unter Windows. D.h. es kommt das Popup-Menü.

**Comment by Rasinari** [comment]
Lösung für Mac: CMD (Apfel) + alt.
Das sollte man OHNE Tooltips kommunizieren; von allein dürften da wenige drauf kommen.

Vorschlag, da das Feld Link wegen der Einträge sehr breit ist: Sondertasten in der Feldbenennung Link textlich ausweisen. Ggf. sogar mit OS-Logo.
Aternative: 2. Zeile für Reiter

**Comment by BurtMC** [comment]
> In der Rohstoffliste funktioniert der Link mit CTRL+Mousclick.

Unter Linux funktioniert es, wie beschrieben.

**Comment by BourgeoisLab** [comment]
Mit dem Update von heute funktioniert es mit allen Funktionstasten. Der Hinweis gehört in den Tooltips in nicht im Feldname. Das Kontextmenü wird ja auch in den Tooltips erklärt.

**Comment by Rasinari** [comment]
Update für Rohstoffe kommt: Reiter waren bisher nicht drin.

Im Tab Rezept erscheinen die Tooltips rechts unten auch ausgeschaltet. Das ist  für den schnellen Blick hilfreicher als ein schwebendes Fenster, das ggf. manches überdeckt. Wenn es Sinn machen würde, diese Funktionalität auf die anderen Tabs auszudehnen, kann eine Diskussion für ein enhancement aufgemacht werden. Mir selber konfligiert das zu sehr mit dem Ziel einer schlanken Oberfläche.
