### ISSUE TITLE
Links in Tooltips nicht ansteuerbar

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#185]
Links in den Tooltips sind nicht ansteuerbar. Mit der Mausbewegung wird der nächste Tooltip aktiviert.

Vielleicht könnte eine Zeitverzögerung oder eine Tastenkombination Abhilfe schaffen?

Lediglich in den eingespeisten TTs in einigen Tab rechts unten ist dies möglich.

**Comment by BourgeoisLab** [comment]
Aufwand und Ertrag steht in keinem Verhältnis.

**Comment by Rasinari** [comment]
Verhalten wird künftig bei TT mit Links erläutert.
#Closed
