### ISSUE TITLE
Rohstoffe Hefe Sortierung Bug

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#187]
Im Tab Rohstoffe -> Hefe -> Name ist ein Bug in der Sortierung nach Alphabet aufsteigend/absteigend. Der 2. Buchstabe wird nicht richtig sortiert. Beispiel: "WLP" wird vor "Weihenstephan" einsortiert.

**Comment by BourgeoisLab** [comment]
Grossbuchstaben vor Kleinbuchstaben. Das ist ein generelles Verhalten bei Qt.

**Comment by Rasinari** [comment]
Igitt. Das ist falsch.

**Comment by LondonRain** [comment]
Und das kann man nicht beeinflussen? Das macht ja für niemanden außer Linuxnerds Sinn.

**Comment by Rasinari** [comment]
Sehe ich auch so. Das kommt davon, wenn Nerds sich über weltweite Konventionen hinwegsetzen und Fachwissen aushebeln, weil ihre Maschine Benchmark für alles ist. *kopfschüttel*
Ich wunderte mich gerade, warum der Eintrag beim Umbenennen immer verschwand… Das spottet allem, was ich zu wissenschaftlicher Recherche gelernt habe.

**Comment by BourgeoisLab** [comment]
Github ist definitiv die falsche plattform, um auf nerds rumzuhacken.

**Comment by BourgeoisLab** [comment]
Erledigt mit 36565e7.
