### ISSUE TITLE
Korrektur Nachisomerisierung

### ISSUE THREAD

**Issue by BurtMC** [kleiner-brauhelfer/kleiner-brauhelfer-2#191]
Es wäre gut, wenn man am Brautag die Nachisomerisierungszeit ebenfalls anpassen könnte. Ich habe aktuell häufig das Problem, dass Aufgrund von schwankenden Kühlmöglichkeiten die Nachisomerisierungszeit immer etwas von der geplanten abweicht und damit die Bittere nicht mehr stimmt.

**Comment by Rasinari** [comment]
Das ist doch gegeben. Erst mit Sud gebraut werden die Felder gesperrt. Eine Notwendigkeit hier etwas zu ändern, ist nicht ersichtlich.

**Comment by BurtMC** [comment]
Wenn die Nachisomerisierungszeit im Rezept angepasst wird, dann ändern sich auch die Hopfengaben im Rezept. Das ist aber nicht gewollt, da dies dann nicht mehr der Realität entspricht. Zudem ändern sich dadurch nicht IBU für den Sud. 

Ziel ist es einen besseren Vergleich zwischen Rezept und entstandenem Sud zu bekommen. In der Sudauswahl werden ja schließlich beide Werte angezeigt. Für die anderen angegeben Werte funktioniert es ja auch :wink:

![grafik](https://user-images.githubusercontent.com/17658461/114093843-e6989e00-98bb-11eb-977e-d3d6c0d58613.png)

In dem Beispiel müssten es z.B. mehr als 50 IBU sein, da statt der geplanten 5min Nachisomerisierung 10 min draus geworden sind.

**Comment by Rasinari** [comment]
Hopfenberechnung ist ohnehin ein unsicheres Geschäft. Die Angaben sind nur eine grobe Schätzung, da noch von vielen weiteren Faktoren abhängig.

Man soll ein Rezept nach dem Brauen nicht mehr in seinen Grundkonstanten ändern. Das ist Manipulation. So funktioniert Brauen nicht und der KBH ist dafür nicht gemacht. Ein Eingriff Für Anmerkungen zum Brauprozess, inklusive aller Fehler, sind die Felder Bemerkungen da.

**Comment by BurtMC** [comment]
Deswegen will ich das Rezept auch nicht anpassen. 

Die anderen Parameter werden für den **Sud** allerdings auch angepasst (in meinem Beispiel die Stammwürze von 19,2°P auf beim Brauen gemessene 19,4°P, dabei ist das Rezept weiterhin konstant), deswegen bin ich der Meinung, dass es für die **Bittere** auch möglich sein sollte. Zumal er ja auch schon ausgegeben wird, allerdings in meinem Fall immer falsch.

Wenn die Umsetzung zu komplex ist, kann ich das akzeptieren.

**Comment by Rasinari** [comment]
Stammwürze kann man messen. Deswegen operiert der KBH mit Zielstammwürze. IBU kann man mit Hobbymitteln nicht messen. Deswegen gibt es hier keinen Bedarf etwas zu ändern.

**Comment by BurtMC** [comment]
SOLL:
![grafik](https://user-images.githubusercontent.com/17658461/114097966-07172700-98c1-11eb-8201-243cf9c26692.png)

IST:
![grafik](https://user-images.githubusercontent.com/17658461/114098046-1f874180-98c1-11eb-9712-f5967cc83682.png)

Ich gebe zu, in diesem Beispiel marginal, allerdings hatte ich auch schon geplant 5min und reell 45min.

![grafik](https://user-images.githubusercontent.com/17658461/114097792-d59e5b80-98c0-11eb-998e-04f5dbc306e5.png)

**Comment by Rasinari** [comment]
Siehe oben die Links.

**Comment by Rasinari** [comment]
> Wenn die Nachisomerisierungszeit im Rezept angepasst wird, dann ändern sich auch die Hopfengaben im Rezept. Das ist aber nicht gewollt, da dies dann nicht mehr der Realität entspricht. Zudem ändern sich dadurch nicht IBU für den Sud.
> 
> Ziel ist es einen besseren Vergleich zwischen Rezept und entstandenem Sud zu bekommen. In der Sudauswahl werden ja schließlich beide Werte angezeigt. Für die anderen angegeben Werte funktioniert es ja auch 😉
> 
> ![grafik](https://user-images.githubusercontent.com/17658461/114093843-e6989e00-98bb-11eb-977e-d3d6c0d58613.png)
> 
> In dem Beispiel müssten es z.B. mehr als 50 IBU sein, da statt der geplanten 5min Nachisomerisierung 10 min draus geworden sind.

Jetzt verstehe ich - Du meinst den Spickzettel. Deine Annahme ist falsch. Alles wird richtig berechnet. Alkohol, Menge, Sudhausausbeute etc. wirkt sich auch auf IBU aus. Der Rest sind Rundungen. Die Tabelle ist eine Bestandaufnahme. Da darf NICHTS verändert werden. Bitte die Artikel hinter den Links lesen.

**Comment by BourgeoisLab** [comment]
Idealerweise hätte man die Rezeptdaten und für den eigentlichen Sud eine editierbare Kopie all dieser Werte (inklusiv Mengenangaben). Aber der KBH ist nicht so aufgebaut. Dass man die Stammwürze und Würzemenge für den Sud eingeben kann ist hier eine Ausnahme. Für die Isomerisierungszeit eine weitere Ausnahme einzuführen, finde ich mässig gut. Man könnte genauso argumentieren, dass die Kochzeit anders als im Rezept gehalten wurde und deswegen diese auch veränderbar sein sollte. Oder dass der einte Hopfen aufgebraucht wurde und die Menge entsprechend nicht mehr stimmt.

Unter dem Strich wäre diese Änderung nicht optimal.

Übrigens, der Unterschied der Bittere zwischen Rezept und Sud beruht auf den Mengenunterschied (linear skaliert).

**Comment by Rasinari** [comment]
Genau. Man muss immer im Blick behalten, dass der BH nicht Selbstzweck ist, sondern eine Hilfe für den Brauprozess. Stammwürze und Würzemenge können – ohne sich selbst zu betrügen – auch nicht richtig geändert werden.

Würzemenge vor dem Kochen, nach dem Kochen, beim Anstellen lassen unter bestimmten Voraussetzungen Eingriffe in Würzemenge und Stammwürze zu. Allein nur durch Verdünnung. Nie durch Reduzierung von Zeit, da dies sich auf die anderen Parameter auswirken würde.
Vereinfacht gesagt: Bittere ist absolut und lässt keine Änderungen zu, Stammwürze und Würzemenge lassen Änderungen in engen Grenzen zu, um zum Ende hin, d.h. beim Anstellen die berechnete Würzemenge und Stammwürze exakt zu treffen. Dies setzt einen sauberen Brauprozess und eine gut eingemessene Brauanlage hinsichtlich SHA und Verdampfungsrate voraus.

Ich bin vor diesem Hintergrund entschieden gegen Möglichkeiten im KBH, die einen sauberen Brauprozess relativieren und Braufehler kaschieren. Im Gegenteil: Der KBH soll ein Tool sein, dass den Anwender unterstützt einen optimierten Brauprozess zu entwickeln. Dies schließt Optionen zur Fehleranalyse ein. Die ausgebauten Felder für Bemerkungen in v2.3 zielen in diese Richtung. Diese Funktion erfüllt der KBH zum Zeitpunkt vorbildlich.
