### ISSUE TITLE
Rezept Kochen Ausschlagen

### ISSUE THREAD

**Issue by BurtMC** [kleiner-brauhelfer/kleiner-brauhelfer-2#192]
Im Tooltip zur Nachisomerisierungszeit ist beschrieben, dass die angegebene Zeit im Reiter Rezept --> Kochen bei Auswahl **Ausschlagen** als negative Zeit ausgegeben wird.

![grafik](https://user-images.githubusercontent.com/17658461/114092645-6aea2180-98ba-11eb-9394-fe4bd98e2978.png)

Das ist bei der Version 2.3 für Linux (AppImage) nicht der Fall.

Man kann zwar die Zeit händisch eintragen, aber als Vorgabe wäre es gut, wenn die eingestellte Nachisomerisierungszeit vorausgewählt wird.

**Comment by BourgeoisLab** [comment]
Erledigt mit d253fdb.
