### ISSUE TITLE
Hopfen Pairing

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#194]
Welcher Hopfen passt zu welchem Hopfen ist eine der wichtigsten Fragen in der Rezeptentwicklung. Manche Seiten mit Hopfenportraits wie learn.kegerator.com befassen sich mit diesem Thema und geben kommerzielle Beispiele. Bei Hopfen-Büchern ist diese Kategorie ohnehin Pflicht.

Der KBH sollte im Reiter Hopfen um eine Spalte Pairing erweitert werden.

**Comment by BourgeoisLab** [comment]
Duplicate #186
