### ISSUE TITLE
Automatisches Speichern

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#199]
Automatisches Speichern ist ein typisches Verhalten von Programmen, die mit Datenbanken arbeiten.
In den KBH soll automatisches Speichern eingebaut werden.

Derzeit verhindert der Kleine Brauhelfer durch diese fehlende Funktion automatische Prozesse des Betriebssystems wie das automatische Auschalten.
Wünschenswert wäre eine Funktion in den Einstellungen, mit der man automatisches Speichern an- und abschalten kann.

**Comment by BourgeoisLab** [comment]
Duplicate #168
