### ISSUE TITLE
undefined reference to 'vtable for ...'

### ISSUE THREAD

**Issue by ivh** [kleiner-brauhelfer/kleiner-brauhelfer-2#20]
Hallo!

Wenn ich im Qt-Creator (5.12.3 auf Linux) bauen will, bekomme ich seit kurzem solche Fehler. Liegt da der Fehler auf meiner Seite?
![kbh-error](https://user-images.githubusercontent.com/134957/60380449-0ee83d00-9a46-11e9-8109-e1be4485119d.png)

**Comment by BourgeoisLab** [comment]
Hi

Ich habe vor kurzem das Unterprojekt brauhelfer-core von shared zu static library umgestellt. Du musst qmake neu ausführen und alles neu kompillieren. Unter Windows musste ich noch das ganze build ordner löschen, da qt den Wechsel nicht ganz hingekriegt hat.

Lg

**Comment by ivh** [comment]
Build-Ordner löschen hat geholfen. Danke!
