### ISSUE TITLE
Exportiertes BEER.XML Format hat falsches character encoding. 

### ISSUE THREAD

**Issue by heinrichhumer** [kleiner-brauhelfer/kleiner-brauhelfer-2#202]
Das im header stehende character encoding (ISO-8859-1) passt nicht mit den inkludierten Zeichen zusammen. So werden Texte dann auch falsch in das Ziel-System übernommen.
Üblicherweise ist es am geschicktesten, das XML-File in UTF-8 Kodierung abzuspeichern.
 
Sowohl ISO-8859-1, als auch UTF-8 gibt den Inhalt des generierten Files nicht richtig wieder. Es geht um die Umlaute und °C als Sonderzeichen.

Wenn man das File beispielsweise in CraftbeerPi hochlädt, bekommt man folgende Darstellung:

![Screenshot 2021-05-12 170010](https://user-images.githubusercontent.com/84087002/117997812-9d68bd80-b343-11eb-8451-2bbf7aa1113d.png)

Ausschnitt aus beer.xml file:
![Screenshot 2021-05-12 170437](https://user-images.githubusercontent.com/84087002/117998503-41eaff80-b344-11eb-8a68-24186c1540b0.png)
bzw:

**Comment by BourgeoisLab** [comment]
Erledigt mit 9519eee.

**Comment by heinrichhumer** [comment]
Herzlichen Dank!
