### ISSUE TITLE
Fehler bei Berechnung der eSHA - bei ausgeblendetem Speisemodul

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#205]
![grafik](https://user-images.githubusercontent.com/33151586/120118199-b40b7300-c191-11eb-8c56-5548ad25dc4e.png)

12,3 °P und und 12 l und 12,4 kg müsste irgendwas nahe den 63 % aus dem Rezepte ergeben, aber nicht 70 %.

Hier der Klickweg:
![klick1](https://user-images.githubusercontent.com/33151586/120118296-106e9280-c192-11eb-826f-e8d084e29c43.gif)

Komisch ist auch, dass die Anstellmenge immer wieder auf was geringeres resettet wird:
![klick2](https://user-images.githubusercontent.com/33151586/120118383-8c68da80-c192-11eb-86c9-f75c0383259e.gif)

**Comment by LondonRain** [comment]
Ah, im Hintergrund steht bei abgefüllter Speisemenge 1 Liter. Das Modul habe ich aber ausgeblendet und sicher nichts dort eingetragen gehabt.

**Comment by Rasinari** [comment]
Das ist mir auch schon verwirrend aufgefallen. Man kommt drauf, aber erst wenn man zwischen den Tabs gewechselt ist. Die Feldbenennung kann hier Klarheit schaffen und auf die Zusammenhänge hinweisen. Das sollte nicht an ein TT delegiert werden.

**Comment by LondonRain** [comment]
Nein, es sollte einfach ein ggf. im Hintergrund wieso auch immer ausgefülltes Speisefeld keinerlei Rolle spielen, wenn das Speisemodul deaktiviert wurde.

**Comment by Rasinari** [comment]
D#accord

**Comment by BourgeoisLab** [comment]
Das Deaktivieren des Moduls blendet die entsprechenden Felder nur aus. Er setzt die Speisemenge nicht auf 0.

Ich frage mich noch, wieso bei dir nicht 0 drin stand. Im Code wird der Wert nie automatisch gesetzt. Ganz sicher, dass du den nicht einmal gesetzt hast? Hast du den Sud kopiert oder neu erstellt?

**Comment by Rasinari** [comment]
War bei mir seit der letzten Version auch so - immer steht 1 darin. Ich kann es aber gerade nicht nachstellen, da ohne aktuellen Sud.

**Comment by BourgeoisLab** [comment]
Ich habe es doch noch gefunden. Das ist ein böser Bug :(.

Erledigt mit 5016ad0.

**Comment by LondonRain** [comment]
Cool! Dann ist doch gut, dass er gefunden wurde. Danke!

**Comment by BourgeoisLab** [comment]
Danke dir für deine wertvollen Fehlermeldungen und Typokorrekturen!
