### ISSUE TITLE
Mehr Auswahl im Tab Brauübersicht

### ISSUE THREAD

**Issue by patman081** [kleiner-brauhelfer/kleiner-brauhelfer-2#207]
Im Tab Brauübersicht, wäre es Prima, wenn man die Gesamtschüttungsmenge hinzufügen kann, damit z.B. Verhältnis von SHA und Schüttungsmenge angezeigt werden kann

**Comment by BourgeoisLab** [comment]
Erledigt mit 8ada982ec74199d3ce9c49fb20a22019bfff4edc.
