### ISSUE TITLE
Ergänzung Menge an Hefe-Starter

### ISSUE THREAD

**Issue by kroddn** [kleiner-brauhelfer/kleiner-brauhelfer-2#211]
Hallo zusammen,

ich habe das Problem, dass ich die Menge an Hefe-Starter beim Ansetzen nicht korrekt berücksichtigt bekomme.

Ich habe z.B. nach dem Hopfeseihen 50 Liter. Hefe-Starter von 5 Litern.
Wenn ich nun bei Anstellmenge auf 55 Liter einstelle, korrigiert sich automatisch die Gesamtwürzemenge auf 55 Liter. Genauso umgekehrt.
Korrigiere ich die Gesamtwürzemenge, dann geht die eff. SHA hoch. Das verfälscht die Statistik natürlich.

Ich wünsche mir also ähnlich der abgefüllten Speisemenge ein Feld für Hefe-Starter (oder generell ein "Zusatz" Feld).
Perfekt wäre natürlich, wenn man für den Zusatz gleich die °P mit angeben kann. Mein Starter hatte nur 8°P und würde dann theoretisch ja die resultierende Stammwürze geringfügig nach unten ziehen.

Und um gleich auf die Frage zu antworten :-) - Dekandieren möchte ich in diesen Fällen nicht, weil die Hefe zu schlecht ausfällt. Und selbst wenn, würde am Ende auch 2 Liter übrig bleiben. Da ich Speise vom Vor-Sud zum Ansetzen nehme, besteht das Bier auch aus denselben Zutaten :-)

**Comment by Rasinari** [comment]
Das Problem ist bekannt. Ich habe es auch. Der KBH hat derzeit keine Funktion für einen Hefestarter, und ich glaube auch nicht, dass eine kommen wird. Es wäre aus der großen Fraktion der Propagierer sicher zu wünschen.

Ich behelfe mir seit Jahren mit dem Trick des Umwegs über High Gravity. Dazu ist es wichtig, den Hefestarter durchzumessen, dann im Mischkreuz richtig zu berechnen, damit die Stammwürze und Sudmenge nachher stimmt.

Inzwischen habe ich soviel Routine, dass ich auf das Mischkreuz verzichte. Der Hefestarter ist regelmäßig 5-6%, High Gravity ist eingestellt bei 7-12%. Das gleicht Abweichungen der Stammwürze aus, man verdünnt ja nicht mit Wasser, sondern mit angesetzter Hefewürze. Je näher dabei der Starter der Stammwürze kommt, um so weniger Abweichung. Der Schuss kann aber auch nach hinten losgehen, dass es mehr Würze wird, als geplant. 10% Starter finde ich wegen Geschmacksveränderungen zu viel - aber das ist ein gangbarer Weg. 

Du kannst das alles in den Freitextfeldern zusätzlich dokumentieren. Hoffe das hilft ein wenig.

Radulph

**Comment by BourgeoisLab** [comment]
Erledigt mit e5fd35e1a3c070b872e1716473b9153c0ffcb4ba.
