### ISSUE TITLE
Hopfenmenge > 999g beim Kochen

### ISSUE THREAD

**Issue by hkristen** [kleiner-brauhelfer/kleiner-brauhelfer-2#212]
Hi! 
Ich skaliere öfter die Rezepte aus dem KBH von 50L auf 10hl rauf und da ists manchmal bei den hopfigeren Sorten notwendig im Reiter Kochen mehr als 999 g pro Hopfengabe einzugeben. Kann es natürlich immer auf mehrere Gaben ausplitten, die zum gleichen Zeitpunkt reinkommen aber von der Übersicht her wäre es einfacher, wenn man mehr als 999g eingeben könnte (so wie im Reiter Gärung).

Wäre cool wenn ihr das einbauen könntet :)

**Comment by Rasinari** [comment]
Mit 10 hl dürftest Du der ausstoßmäßig größter Brauer sein. In der anderen Richtung wären Erweiterungen auch wünschenswert. Beim Hopfenkochen wären 2 Nachkommastellen wie beim Malz gut.

**Comment by BourgeoisLab** [comment]
Obergrenze erhöht mit e537412.

Download:
https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/actions/runs/1199349455
