### ISSUE TITLE
Hefemenge in Rezept >99 geht nicht

### ISSUE THREAD

**Issue by Sebbbastian** [kleiner-brauhelfer/kleiner-brauhelfer-2#215]
Im Rezept in Tab Gärung ist die Eingabe der Hefemenge auf 99 begrenzt. Auch die 'Empfohlen' Menge zeigt max. 99 an, selbst wenn die errechnete Menge größer 99 ist. 
Ich kaufe Trockenhefe im 500g Pack und verwalte diese dann im Rohstoffe Tab in der Einheit g statt Pckg it der Würzemenge 0,8l/g. D.h. wenn ich z.B. 120 Liter Würze für ein untergäriges Bier habe, dann benötige ich 144g Hefe. So würde für mich die Verwaltung super funktionieren. Nur ist da das Problem der begrenzten Eingabe bzw. Empfehlung auf 99 im Tab Rezept | Gärung.
Das sollte auf 3 Stellen erweitert werden -> max. 999 und schon lässt sich auch dieser Fall gut abbilden.
Gibt es andere Workarounds für diesen Use Case? Ich bin dich sicher nicht der einzige KBH Nutzer, der Trockenhefe in der 500g Packung kauft, oder doch?
![kbh_anzahl begrenzt](https://user-images.githubusercontent.com/66955692/131629132-35e02102-2c44-4053-8813-e8d6421af860.PNG)

**Comment by Rasinari** [comment]
Ich schließe mich an. Ich kaufe 250g-Packs direkt ab Hersteller.

**Comment by BourgeoisLab** [comment]
Das kann ich ganz einfach ändern.
Eine neue Release wird es aber so schnell nicht geben. Wenn die änderung gemacht ist, kannst du dir aber die automatisch generierte Version herunterladen (nicht getestet). Ich verlinke die Datei, wenn es soweit ist.

**Comment by BourgeoisLab** [comment]
Obergrenze erhöht mit e537412.

Download:
https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/actions/runs/1199349455
