### ISSUE TITLE
Bug Farbberechnung bei Stück

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#218]
Wenn man die Rohstoffe bei Gewürze von Gramm auf Stück ändert und eine helle Farbe gewählt ist, wirkt sich dies bereits bei einem Stück überproportional aufhellend auf den gesamten Sud aus.

Beispiel: Gewürzbier - Gaben von 2g pro Gewürz, alle sind mit Farbwert 1 erfasst. Sobald auf Stück umgestellt – statt 2g jetzt 20 Stück Körner – hellt sich die Farbe von EBC 17 auf 7 auf.
Beispiel 2: 1 Korn Piment = 0,05g wird mit -3EBC berechnet (Piment ist mit Farbwert 1 erfasst). Das 2. Korn -2EBC, das 3. Korn -1EBC. Dann flacht die Kurve ab.

**Comment by Rasinari** [comment]
Die Abweichung bei Stück ist enorm. Kommawerte bei EBC mögen da sicher eine Abhilfe sein. Ich gebe aber zu bedenken, dass das sehr ungewöhnlich ist. Zumindest habe ich noch nie einen nichtganzzahligen EBC-Wert gesehen. Vielleicht gibt es einen besseren Lösungsweg?

**Comment by BourgeoisLab** [comment]
Erledigt mit 07df87f.
