### ISSUE TITLE
BUG: Wrong recipe is loaded on click in list

### ISSUE THREAD

**Issue by maxliemant** [kleiner-brauhelfer/kleiner-brauhelfer-2#22]
When double clicking on a recipe in the main view, the recipe-view is loaded.
Only in the middle view is the correct recipe. The left column und right is a different recipe. Same on other tabs regarding this recipe.
Closing and opening the app fixed it, but it's still a bug though.
Screenshots attached
![kleiner-brauhelfer-1](https://user-images.githubusercontent.com/45594714/61994211-11a37580-b078-11e9-95bd-ceb1048b161e.PNG)
![kleiner-brauhelfer-2](https://user-images.githubusercontent.com/45594714/61994212-123c0c00-b078-11e9-89ff-02c514ae4119.PNG)

**Comment by BourgeoisLab** [comment]
Not quite sure what you mean. Please add a screenshot of the first tab (Sudauswahl) with Weizenbier selected. The loaded brew is Weizenbier and but the first screenshot shows Lime-Basil Alie.

**Comment by maxliemant** [comment]
That's the point. I double clicked Lime-Basil Ale and Weizenbier appeared. The middle part with malt, hop etc. is still Lime-Basil though.

**Comment by BourgeoisLab** [comment]
That is strange. Please check with the upcoming beta2 if this is still an issue. Many bugs were fixed in the meantime. Thanks.

**Comment by maxliemant** [comment]
No, it does not. Restarting the app definetly helped though. Are there some logs you could need for the next time it happens?

**Comment by BourgeoisLab** [comment]
Not really. You can send me your database if you want. Maybe I can reproduce it.

**Comment by Rasinari** [comment]
I have the same problem.

**Comment by BourgeoisLab** [comment]
@maxliemant 
Can you reproduce the bug on a regular basis? Would you mind testing 1-2 versions? I have some ideas on how to solve it, but it cant't reproduce the bug...

@Rasinari 
You only have Mac OS, right? It can't build for Mac OS.

And by the way: german language is also OK.

**Comment by Rasinari** [comment]
Der Bug taucht bei schnellem Doppelklick auf ein Rezept auf. Es wird dann grundsätzlich die eine bestimmte falsche Version geöffnet. Sieht nach einem ID-Fehler aus, der bei Neustart behoben wird. 
Dabei werden ALLE Gewichtsangaben auf 0 gesetzt.
Derzeit nicht reproduzierbar.

Ich habe macOS, kann aber auch in der VM auf Windows 10 testen.

**Comment by BourgeoisLab** [comment]
Neustart sollte nicht nötig sein. Kann man nicht einfach einen anderen Sud laden und dann wieder den gewünschten Sud laden?

**Comment by Rasinari** [comment]
Das geht nicht. Schon probiert.

**Comment by maxliemant** [comment]
Konnte es jetzt nicht mehr reproduzieren.
Ich werde versuchen beim naechsten mal drauf zu achten, was ich vorher gemacht habe.
Beta 2 ist bei mir jetzt schon mehrere male abgestuerzt.
z.B. beim JSON Import von MMuM.

**Comment by BourgeoisLab** [comment]
Ich werde bald (hoffentlich nächstes Wochenende) eine beta3 kompillieren.
Falls ein Import systematisch nicht funktioniert, bitte melden und die json Datei anhängen.

Welche Windows Version hast du? 32/64bit?

**Comment by Rasinari** [comment]
Ich habe gerade den Import von MMuM durchexerziert. Klappt auf Mac tadellos. Man muss viel austauschen, wenn man die Rohstoffe anders benannt hat.
@maxliemant : kanne es bei Dir daran liegen? Um den Fehler einzugrenzen, mein bescheidener Vorschlag: In der JSON mit einem Editor Deine Rohstoffbezeichnungen vorher eintragen, dann nochmals importieren. Wenn das nicht klappt - wie sieht es unter einem nackten User aus?

**Comment by BourgeoisLab** [comment]
Passiert das immer noch?

**Comment by maxliemant** [comment]
Kann ich nicht genau sagen, da es ja nicht 100% reproduzierbar ist.

**Comment by BourgeoisLab** [comment]
Ich schliesse es und falls es nochmals vorkommt, einfach wieder öffnen. Ich vermute, es lag am "Speichern Bug".
