### ISSUE TITLE
Anlagenwerte expotieren/importieren möglich?

### ISSUE THREAD

**Issue by markussoeth** [kleiner-brauhelfer/kleiner-brauhelfer-2#220]
Hallo,
gibt es eine Möglichkeit die Anlagenwerte zu exportieren/importieren?
Ich habe dazu nichts gefunden.
Hintergrund ist, ich spiele mit der Idee eine Gemeinschaftsbrauanlage aufzubauen. Da wäre es toll, wenn die Leute sich die Anlagenwerte für ihre eigenen Sude importieren könnten.
Gruss
Markus

**Comment by Rasinari** [comment]
Das gibt es nicht. Aber die wichtigsten Parameter wie SHA und Verdampfungsrate werden beim Import eines Rezeptes mitberücksichtigt.

Auf einer Gemeinschaftsanlage ist es am praktikabelsten wohl per Aushang die Maße zu veröffentlichen. Zu bedenken ist, dass die Werte für Verdampfung und SHA nicht statisch sind. Wichtiger wäre Sorge zu tragen, dass diese Werte regelmäßig in die Mittelwertsberechnung einfließen.

Von daher macht es wohl am meisten Sinn, wenn es zur Gemeinschaftsanlage auch eine Gemeinschaftsdatenbank des KBH gibt.

Gruß
Radulph
