### ISSUE TITLE
Hauptfenster neu aufteilen

### ISSUE THREAD

**Issue by psytrap** [kleiner-brauhelfer/kleiner-brauhelfer-2#221]
Hallo zusammen,

Die Tabs werden ja immer mehr! Da dachte ich mir die sollte man in zwei Gruppen aufteilen. Die Werkzeugleiste war noch frei und ich dachte mir die lässt ich ganz gut als pseudo-Tab missbrauchen. Die Gruppen wären "Verwaltung" und "Sud" (siehe Screenshot). Beim Klick auf Verwaltung sind nur die folgenden Tabs sichtbar:
* Sudauswahl
* Brauübersicht
* Ausrüstung
* Rohstoffe
* Datenbank
Der Sud-Option zeigt alles zu einem Sud:
* Rezept
* Braudaten
* Abfülldaten
* ....
Die momentane Tabauswahl bleibt vielleicht auch gleich beim Wechsel der Gruppe Erhalten. Das erleichtert einen Abgleich zwischen dem Sud und den Verwaltungsstatus.

Wär das was?

![image](https://user-images.githubusercontent.com/44663346/138555282-996b35a4-c03f-439c-abdf-f2a8344d34a5.png)

**Comment by psytrap** [comment]
Jetzt hab ich es doch mal geschafft und den Ansatz mit der Werkzeugleiste und Dialog-Fenstern zur Demonstration hingepfuscht. Das schaut sogar ganz gut aus, weil nicht modale Dialog-Fenster vor dem Parent-Fenster bleiben aber nicht sperren. Unten hab ich das Rohstoff-Werkzeug geöffnet und danach im Hauptfenster im Rezept den Malz-Dialog aufgemacht. Das geht wohl auch unter Windows so: https://docs.microsoft.com/de-de/cpp/mfc/modal-and-modeless-dialog-boxes?view=msvc-160

Das von Tab-Widgets auf Dialog-Fenster umräumen berührt einige Stellen im Code. Das macht einiges an Arbeit und bei meinem Zeit-Budget braucht das sicher bis in den Weihnachtsurlaub. Gebt also bitte Bescheid wenn es nicht erwünscht ist.

Hier mein Branch mit der Demo: https://github.com/psytrap/kleiner-brauhelfer-2/tree/hauptfenster_aufraeumen

![image](https://user-images.githubusercontent.com/44663346/140803364-161e92de-c9f4-457e-8bd2-d096e2383e22.png)

**Comment by Rasinari** [comment]
Tut mir leid - da sehe ich nichts. Ich sehe nur die Windows-Erklärung und auf Github keine Demo.

**Comment by BourgeoisLab** [comment]
Danke für die Demo. Diese muss man selber kompilieren.

Irgendwie überzeugt es mich nicht so. Wenn da 3-4 Fenster offen sind, wird es schnell unübersichtlich. Vielleicht ist es aber auch ein Gewohnheitsding.

Die zusätzliche Toolbar finde ich aber nicht so schlecht. Wie wäre es dort mit einem zusätzlichen Eintrag "Sud".  Klickt man drauf, erscheinen unten die Tabs wie bisher. Klickt man aber auf "Brauübersicht", "Ausrüstung", "Rohstoffe" oder "Datenbank" wird die entsprechende Seite unten statt den (Sud-) Tabs angezeigt.

Etwa so:
Sud (Reiter Brauübersicht, Ausrüstung und Datenbank müssten noch weg):
<img width="1310" alt="sud" src="https://user-images.githubusercontent.com/9480307/141003255-8d6a80df-18ed-4899-8bf0-e72846bd0c26.PNG">

Brauübersicht:
![brauuebersicht](https://user-images.githubusercontent.com/9480307/141003271-f8755dcd-7c73-4200-9225-c388c0922a67.png)

**Comment by Rasinari** [comment]
Mir gefallen verschiedene Fenster sehr gut. sie haben aber einen Stoplperstein, den Frédéric hier zu Recht anspricht: Sie sollten aber über eine magnetische Andockfunktion verfügen, sonst wird es schnell unaufgeräumt.

Ich habe hier noch ein Uraltprogramm von 2004 und die neuen Adobe-Programme Indesign, Illustrator und Photoshop, deren Hauptfenster von Menü und Werkzeugleisten losgelöst ist. Ergebnis is oft ein zugemüllter Bildschirm, bei dem die Elemente unlesbar übereinander liegen. Solch ein Programm mal schnell beiseite zu schieben, ist auch immer ein Aufwand.

Es sollte also die Möglichkeit geben, sich die Module anzuordnen.

**Comment by psytrap** [comment]
Es hat eine Weile gedauert, aber jetzt gibt es das Überarbeitete Hauptfenster.

Knöpfe in der Werkzeugleiste toggeln beim öffnen vom Dialog
Wenn der Dialog bereits geöffnet ist springt Dialog beim Klick auf die Werkzeugleiste in den Vordergrund.

![image](https://user-images.githubusercontent.com/44663346/148060885-524fdc9d-7a3d-4635-bd57-30c32b7e33ff.png)

Der Tab Datenbank ist nicht als Dialog aus Werkzeugleiste gelandet, sondern in die Menüleiste unter "Ansicht" gewandert. Von wo auch der Log-Dialog zugänglich ist.
Den "Speichern"-Knopf habe ich prominenter gemacht und in der Werkzeugleiste ergänzt
![image](https://user-images.githubusercontent.com/44663346/148060994-604cb53f-b9e9-4fd3-98b2-f7c7dc267a98.png)

Defizite der Dialoge: Kein Fenster-Maximieren Knopf + Singleton/Single-Instance stellt die naheliegende Implementierung non-modaler Dialoge dar

Offene Aufgaben:

- Saubere Singleton-Implementierung für die Dialog-Fenster. (Thread-Safe)
- Safe- und restore Fenster-Settings
- Standardgröße für die Dialoge
+ Tab-Stops, Hilfe update, Hell/Dunkel-Theme, Übersetzung, Aufräumen...

Wer selber die Version ausprobieren möchte kann sie über seine Github-Actions bauen:
https://github.com/psytrap/kleiner-brauhelfer-2/tree/hauptfenster_mit_werkzeugleiste

BTW:
Mit etwas Glück sind die Actions nicht privat und hier lässt sich die Anwendung herunterladen
https://github.com/psytrap/kleiner-brauhelfer-2/actions/runs/1653510076

Ansonsten gibt es den „Run Workflow“-Knopf bei den Github-Actions
https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/pull/227

**Comment by BourgeoisLab** [comment]
Sieht auf den ersten Blick gut aus!
Das Speichern der Dialoggrösse finde ich wichtig. Das darf nicht fehlen. Eventuell auch die Position.

Wenn du willst kannst du ein pull-request machen. Ich würde wahrscheinlich zuerst einmal dann ein Branch erstellen. Das motiviert mich weiter am KBH zu arbeiten:).

**Comment by psytrap** [comment]
Nachtrag: Alle als offen genannten Aufgaben werden von mir die nächsten Tagen noch erledigt. Ich wollte nur noch Feedback von meinen Brauern zu allem abwarten, bevor ich zum Aufräumen übergehe.

**Comment by Rasinari** [comment]
Da ich leider nicht kompilieren kann, kann ich auch meinen Senf nicht dazugeben. Da ich damit nicht alleine bin, es aber wohl einige engagierte Anwender mehr gibt, wäre es eine Überlegung, ob Ihr nicht eine kompilierte Version zur Begutachtung erstellen könntet.

**Comment by psytrap** [comment]
Mit den Github-Actions lässt sich das Online erledigen. Eigentlich. Jetzt seh ich das klappt nur für den Eigentümer eines Repositories oder PRs. Wer da wirklich Rechte dazu hat bei Github erscheint mir ein bisschen verworren. Ich kugg mal was sich machen lässt.

**Comment by psytrap** [comment]
Jetzt hab ich es mal geprüft. Eine Actions kann man in Fremden Repos nicht starten. Der Zugriff auf Build Artefakte geht auch nicht...
Hier mein Cloud-Laufwerk:
https://c.gmx.net/@520576031342467694/lqg9ErFVTf2nTCFkhu26QA

**Comment by Rasinari** [comment]
Danke für die Mühe. funktioniert. Die letzte Version läuft hier gerade. Was auffällt, sind die Umlaute. Es fehlen auf den ersten Blick bei Rohstoffe 2 Funktionalitäten (Mac):
a) Reiter Fenster. Kleineres Fenster Rohstoffe verschwindet und kann nicht ohne Umwege hervorgeholt werden (Mac Vorgabe). Bei schwebenden Fenstern muss das Hauptmenü zwingend den Menüpunkt "Fenster" enthalten
b) Fenster Rohstoffe macht schwebend nur Sinn, wenn es zusätzliche Funktionen anbietet. Hier drängt sich Drag & Drop förmlich auf!
Neuer Button Speichern gefällt mir sehr!

Ich finde generell die Idee Fenster abzutrennen gut. Das macht aber nur mit neuen Funktionen Sinn, ohne ist es fast sinnbefreit, da keine Klicks (Interaktion) eingespart werden.

Ich schau die Tage noch die anderen Versionen an.

**Comment by psytrap** [comment]
Mit Mac bin ich nicht vertraut. Jetzt lade ich mir aber eine VM herunter sonst verstehe ich deine Kommentare nicht.
Drag&Drop klingt nach einer guten Idee. Hab ich noch nie gemacht und da muss ich mich mal einlesen.

Neue Funktionen als Vorraussetzung für größeres Aufräumen finde ich immer schwierig. Das führt schnell zum Henne-Ei-Problem. "Unordnung" erschwert neue Funktionen, neue Funktionen erzeugen erstmal "Unordnung". Aber das ist eine philosophische Frage und nur als Kommentar hier.

Morgen ist wieder Programmiertag bei mir. Mal sehen zu welchen Ergebnissen ich dann komme.

**Comment by Rasinari** [comment]
Perfekt. Kleine Hilfe - ein Mac-Programm ist in seinen Grundfunktionen immer gleich aufgebaut. Das macht die Einarbeitung in neue Programme so einfach. Apple gibt das vor. Anbei zwei Screenshots - sollten selbsterklärend sein.
<img width="511" alt="Bildschirmfoto 2022-01-06 um 15 01 34" src="https://user-images.githubusercontent.com/51321250/148394933-8229
<img width="614" alt="Bildschirmfoto 2022-01-06 um 15 03 14" src="https://user-images.githubusercontent.com/51321250/148394952-762e721c-2692-4ba9-913d-a6b9699e46ef.png">
de1d-9514-4cae-8532-13711ad6006f.png">

**Comment by Rasinari** [comment]
Das wäre die Idee für Drag&Drop:
<img width="1721" alt="Bildschirmfoto 2022-01-06 um 15 09 16" src="https://user-images.githubusercontent.com/51321250/148395787-67d51e3f-156f-48ae-9d50-08e1f6b0bf33.png">

**Comment by psytrap** [comment]
Bei dem RestoreView() funktioniert das nicht so wie erwartet. Morgen gehts weiter....

**Comment by BourgeoisLab** [comment]
Drag&Drop sollte erst in einem zweiten Schritt angegangen werden.

Die Liste der Sude in der Brauübersicht will ich von der Liste aus der Sudauswahl entkoppeln. Auch erst in einem zweiten Schritt. Falls du also Probleme hast mit der Synchronization der Listen, ignoriere es einfach.

**Comment by BourgeoisLab** [comment]
> Knöpfe in der Werkzeugleiste toggeln beim öffnen vom Dialog Wenn der Dialog bereits geöffnet ist springt Dialog beim Klick auf die Werkzeugleiste in den Vordergrund.

Ich fände es besser mit einem erneuten Klick, das Fenster zu schliessen, statt es in den Vordergrund zu bringen. Das ermöglicht ein schnelleres Schliessen (statt auf das kleine X zu klicken). Will man es in den Vordergrund bringen, klickt man einfach zweimal drauf.

**Comment by Rasinari** [comment]
> > Knöpfe in der Werkzeugleiste toggeln beim öffnen vom Dialog Wenn der Dialog bereits geöffnet ist springt Dialog beim Klick auf die Werkzeugleiste in den Vordergrund.
> 
> Ich fände es besser mit einem erneuten Klick, das Fenster zu schliessen, statt es in den Vordergrund zu bringen. Das ermöglicht ein schnelleres Schliessen (statt auf das kleine X zu klicken). Will man es in den Vordergrund bringen, klickt man einfach zweimal drauf.

Das ist nicht selbsterklärend. Diese Technik ist in anderen Betriebssystemen auch unbekannt. Würde ich davon abraten, sondern ganz auf Visibility setzen. Hidden Features ist eher was für Leute, die Easter Eggs suchen ;-)

**Comment by psytrap** [comment]
So, gestern bin ich noch fertig geworden. Nur für hier schreiben wars dann ein bisschen zu spät.

Da es eine größerer Umbau ist hier das Fazit von meiner Seite:
Pro: Mehr Struktur mit Werkzeugleiste+Dialoge und Reitern (Deswegen hab ichs ja gemacht :)
Contras:
- Sehe ich auf der Implementierungsseite. Dialoge machen die Kopplung mit dem Hauptfenster undurchsichtiger. Bei Reitern stellt sich die Frage nicht so sehr, denn die sind ja Teil vom Hauptfenster. Wie sauber das sein muss kann ich nur schwer beurteilen da ich beruflich keine GUIs mache. Da im Prinzip alles in einem Thread läuft muss man wohl nicht über-penibel sein.
- Dialogfenster können auch keinen "Maximieren"-Knopf. Das "Window"-Menü von MacOS wird von QT schon nicht unterstützt und selber hinbiegen halte ich für zu aufwendig.

Die Sache das der Klick in die Werkzeugleiste einen bereits offenen Dialog in den Vordergrund schiebt, habe ich mir bei Inkscape abgekuggt und sehe keinen Grund hier das anderst zu machen.

Die Funktion für Drag&Drop kann ich mir in verschieden Variationen vorstellen. Das ist ein eigenes Thema und würde ich durchaus übernehmen. Montag geht die Arbeit wieder los und nervt gerade ohne ende (Da bin ich froh mal was richtiges gemacht zu haben). Aber entsprechend dauern weitere Arbeiten bei mir ein paar Monat.

**Comment by Rasinari** [comment]
Von der GUI-Seite kann ich helfen, ich habe in der Entwicklung von Lehrangeboten im Medienbereich an Universitäten ab und an damit zu tun.

**Comment by BourgeoisLab** [comment]
Erledigt mit 318efa4.
