### ISSUE TITLE
High Gravity: Würzmenge nach Hopfenseihen != Anstellmenge 

### ISSUE THREAD

**Issue by DomCGN** [kleiner-brauhelfer/kleiner-brauhelfer-2#224]
Version: 2.3.0
Ich habe heute das erste mal High Gravity gebraut. Ich hatte 18 Liter nach dem Whirlpool abfüllen in den Gärtank. Wie das Rezept auch vorgegeben hat musste ich 2 Liter Wasser verschneiden um auf mein Zielstammwürze zu kommen. 

1) Es scheint als wäre die "Anstellmenge" die Menge ohne Verschneidung / Wasserzugabe. Jedenfalls wird nur so die "Wassermenge, um auf Zielstammwürze zu verdünnen" und die "Effektive Sudhausausbeute" korrekt berechnet. Dies sollte klarer beschrieben werden.
 
2) In welchem Fall ist die "Würzemenge nach Hopfenseihen" != der "Anstellmenge" (ohne Wasserzugabe)? Übersehe ich da was oder ist da auch noch ein "Problem"?

**Comment by Rasinari** [comment]
zu 2.: Wo ist das Problem? Würzemenge nach dem Hopfenseihen und Anstellmenge sind oft nicht identisch, deswegen werden sie getrennt behandelt. Der KBH geht aber zuerst davon aus, dass beide Mengen identisch sind, deswegen läuft die Anstellmenge bei der Eingabe im Feld "Würzemenge nach dem Anstellen" mit. Umgekehrt ist dies nicht der Fall. Die Anstellmenge verändert sich oft durch Zugaben zur Gärung wie z.B. ein Starter.
zu 1. Verstehe Deine Ausführungen nicht ganz. Der Anstellmenge ist es egal, ob mit Verschneidung oder ohne. Mache einen Vorschlag, wie das besser kommuniziert werden soll, dass Zugaben nicht zur Effektiven sudhausausbeute eingerechnet werden. Eigentlich ist es ja klar: Das HG-Wasser gehört nicht zu Brauprozess. Mit Würzemenge nach dem Hopfenseihen ist der Brauprozess beendet. Das Anstellen gehört schon zum Gärprozess.
Der KBH weist ausdrücklich darauf hin, dass zusätzliche Zutaten die Berechnung verfälschen können.

Wenn Dir eine bessere Benennung einfällt, mache eine Vorschlag. Es ist vielleicht beim ersten Mal eine knifflige Stelle, wenn man HG nutzt, bisher gab es aber keine Auffälligkeiten mit Verständnisschwierigkeiten.
