### ISSUE TITLE
Verdünnung der Würzmenge nach dem Hopfenseihen

### ISSUE THREAD

**Issue by robtor-de** [kleiner-brauhelfer/kleiner-brauhelfer-2#228]
Ich bin bereits mehrfach auf das Problem gestoßen, dass ich eine höhere Sudhausausbeute hatte als erwartet und daher meine Stammwürze nach dem Hopfenseihen/Kochende weitaus über dem Zielwert lag. Hier wäre es äußerst praktisch die Option zu haben sich im Tab Brauen die benötigte Wassermenge zur Verdünnung auf die gewünschte Zielmenge zu berechnen.

Oder gibt es bereits eine Methode im Programm die ich vielleicht übersehen habe?

**Comment by Rasinari** [comment]
Du hast die Verdünnung übersehen. Schau unten im Tab Braudaten.

**Comment by BourgeoisLab** [comment]
Wie @Rasinari richtig sagt, wird im Tab Braudaten weiter unten angegeben, wieviel Wasser nötig ist um auf **Zielstammwürze** zu kommen (nicht **Zielmenge**). Auf Zeilmenge verdünnen macht wenig Sinn, da die Stammwürze dann nicht stimmen wird.

**Comment by robtor-de** [comment]
Vielen Dank für die schnellen Antworten. @BourgeoisLab da habe ich mich leider nicht richtig ausgedrückt, ich meinte natürlich "Auf die Zielstammwürze verdünnen"

Und vielen Dank, ich hatte das entsprechende Feld tatsächlich übersehen, da es direkt bei der Berechnung der benötigten Speisemenge steht.

Hätte mich auch sehr gewundert, wenn diese Funktion nicht vorhanden wäre.

Da das Feld ausgeblendet wird, sobald man den Sud als gebrat markiert hat, hätte ich lange suchen können ^^
