### ISSUE TITLE
Synchronisation sqlite Dropbox mit iOS App

### ISSUE THREAD

**Issue by affenbraeu** [kleiner-brauhelfer/kleiner-brauhelfer-2#229]
Erstmal vielen Dank für das tolle Programm, das zudem auch noch kostenlos zur Verfügung gestellt wird! Das Programm funktioniert in der Desktopversion einwandfrei. Wir haben die Datenbank auf unserem Dropbox-Account der Brauerei abgelegt. Der Ordner ist mit unseren privaten Dropbox Accounts geteilt, so dass wir das Programm auf dem Laptop in unserer kleinen Brauerei als auch auf privaten PCs zur Rezeptplanung nutzen können.
 
Gestern haben wir zusätzlich noch die App im AppStore (iOS) heruntergeladen und wollten auch diese verknüpfen. Leider scheint dies nicht zu funktionieren, da man in der App den Pfad für die Datenbank nicht wählen kann. Die App legt bei der Verknüpfung im privaten Dropbox Account einen neuen Ordner an (\Apps\brauhelfer) und möchte, dass man die Datenbank dahin kopiert. Leider kann ich die Datenbank dann aber nicht mehr mit meinen Kollegen zusammen nutzen, da sie nicht mehr in einem geteilten Ordner liegt. 
Alternativ haben wir versucht den Ordner \apps\brauhelfer mit der Datenbank darin vor der Installation auf dem Handy bereits anzulegen und zu teilen. Bei der Installation der App greift die diese dann aber nicht auf den bereits bestehenden Ordner zu sondern möchte zwingend wieder einen neuen Ordner anlegen. Dieses mal war es dann der Ordner \brauhelfer.
 
Gibt es hierfür eine Lösung oder einen Workaround?

**Comment by BourgeoisLab** [comment]
Da kann ich dir leider nicht helfen. Die iOS App wird nicht vom kleinen-brauhelfer Team entwickelt, sondern ist eine unabhängige Entwicklung von Dirk Hildebrand. Am besten versuchst du die Frage hier zu stellen:
https://hobbybrauer.de/forum/viewtopic.php?f=3&t=147

Für Android gibt es eine andere App (https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-app). Die wurde von mir geschrieben und man kann dort den Dropbox Pfad frei wählen. Die App muss manuell installiert werden, also nicht über den Play Store.

**Comment by Rasinari** [comment]
Die iOS App ruht leider. Mein Eindruck ist, dass das am niedrigen Interesse liegt.

Längerfristige Lösung wäre wohl eine browserbasierte Version...
