### ISSUE TITLE
BUG: mash water is displayed wrong

### ISSUE THREAD

**Issue by maxliemant** [kleiner-brauhelfer/kleiner-brauhelfer-2#23]
When in the recipe view, you have the water amounts on the right side at the bottom.
For example it says 
* mash water: 18,3L
* sparge water: 14,6L
* total: 32,9L

But in the next tab "Braudaten" it says:
* mash water: 33L

Issues remains after restart of the app.

See screenshot attached.
![kleiner-brauhelfer-hauptguss-1](https://user-images.githubusercontent.com/45594714/61994251-a7d79b80-b078-11e9-984b-396d9e30a600.PNG)
![kleiner-brauhelfer-hauptguss-2](https://user-images.githubusercontent.com/45594714/61994252-a7d79b80-b078-11e9-9395-ffe87f291313.PNG)

**Comment by BourgeoisLab** [comment]
This is already fixed in beta2. Please check this issue again after the release of beta2.

**Comment by maxliemant** [comment]
Great. Just didn't see this in the fix list.
