### ISSUE TITLE
Durchschnittsberechnung Sudhausausbeute & Verdampfungsrate funktioniert nicht

### ISSUE THREAD

**Issue by markussoeth** [kleiner-brauhelfer/kleiner-brauhelfer-2#233]
Hallo,
erst einmal wieder vielen Dank für Eure Arbeit. Das Tool ist toll und wird immer besser. 
Ich habe heute die neue Version 2.3.2 installiert.
Leider werden bei meinen Geräten aktuell nicht mehr die Durchschnittswerte für SHA und Verdampfungsrate ausgerechnet.
An meiner Konfiguration sollte es nicht liegen. Bei der Vorgängerversion funktionierte das noch.
![grafik](https://user-images.githubusercontent.com/306641/151657390-0846e977-923a-4674-bbdb-4e7826c8fede.png)
Der Schieberegler lässt sich nicht bewegen, da keine Sude für den Durchschnitt erfasst sind. 
In der Auflistung sind aber fast alle Sude für den Durchschnitt angelegt
![grafik](https://user-images.githubusercontent.com/306641/151657557-b4405072-98e7-4577-8a45-a11e0993cd86.png)

**Comment by BourgeoisLab** [comment]
Erledigt mit 33a4960.
