### ISSUE TITLE
Wunsch: Anpassung der Zugabemenge nach Braudaten

### ISSUE THREAD

**Issue by markussoeth** [kleiner-brauhelfer/kleiner-brauhelfer-2#234]
Hallo,

ich dachte mir es wäre ganz schön, wenn sich die Zugabemenge von Zusätzen (Hopfenstopfen etc) sich der Menge des Sudes aus dem Brauvorgang anpasst. 
Bin da beim ersten Mal darauf reingefallen, dass die dort aufgeführte Menge sich immer auf das Rezept bezieht und ich mir die tatsächliche Menge selbst anhand meiner Braudaten ausrechnen muss.

**Comment by Rasinari** [comment]
> Hallo,
> 
> ich dachte mir es wäre ganz schön, wenn sich die Zugabemenge von Zusätzen (Hopfenstopfen etc) sich der Menge des Sudes aus dem Brauvorgang anpasst. Bin da beim ersten Mal darauf reingefallen, dass die dort aufgeführte Menge sich immer auf das Rezept bezieht und ich mir die tatsächliche Menge selbst anhand meiner Braudaten ausrechnen muss.

Verstehe nicht, was Du meinst, das ist zu ungenau. Du musst schon genau beschreiben WO, sonst kann man Dir nicht folgen.

**Comment by BourgeoisLab** [comment]
Ich denke, er meint, wenn z.B. Anstellmenge nicht gleich Zielmenge ist, dann ist die Berechnung fürs Hopfenstopfen nicht mehr richtig.
Aus meiner Sicht müsste beides angezeigt werden (Hopfenmenge laut Rezept und laut effektiver Braumenge). Dasselbe gilt auch für die Hefe und andere Zusätze (bei der Gärung).

**Comment by markussoeth** [comment]
Sorry.. 
Erst einmal Danke, dass Du Dich meinem Wunsch angenommen hast.
Ich versuchs nochmal besser zu erklären.
Im Rezept kann ich im Reiter "Gärung" Zutaten hinzufügen. Zum Beispiel eben Hopfen, der nach 5 Tagen hinzugegeben wird und dann nach 5 Tagen wieder entnommen wird. 
In den Feldern kann ich entweder die Zugabe nach Menge oder g/L angeben. 
![grafik](https://user-images.githubusercontent.com/306641/151662340-7025392b-1e6c-47ac-9101-804de8cae1f8.png)

Wenn ich beim Brauen nun auf eine andere Literzahl komme, weil ich z.B. Wasser zum Verdünnen hinzugeben musste, steht weiterhin in den Feldern für die Braudaten die Menge, die ich lt. Rezept hinzugeben müsste. 
![grafik](https://user-images.githubusercontent.com/306641/151662452-bc11c0da-2e34-453b-9d56-39f1dec95292.png)

Rechenbeispiel
Ausschlagmenge lt Rezept 26 Ltr. 
Hopfengabe lt Rezept 0,6 g/Ltr = 15,6g
Beim Brauen mussten 2 Ltr. zur Verdünnung hinzugegeben werden
Neue Ausschlagmenge 28 Ltr. 
Hopfengabe sollte nun 16,8 g sein.
Aber in der rechten Spalte steht weiterhin die Zugabe von 15,6g
![grafik](https://user-images.githubusercontent.com/306641/151662800-dc045d7d-6b1c-43e1-9f87-c2a8670a9378.png)

@BourgeoisLab : Danke war grade beim Tippen als deine Rückmeldung reinkam. Ja genau das meinte ich.

**Comment by Rasinari** [comment]
> Ich denke, er meint, wenn z.B. Anstellmenge nicht gleich Zielmenge ist, dann ist die Berechnung fürs Hopfenstopfen nicht mehr richtig.
> Aus meiner Sicht müsste beides angezeigt werden (Hopfenmenge laut Rezept und laut effektiver Braumenge). Dasselbe gilt auch für die Hefe und andere Zusätze (bei der Gärung).

Jetzt verstehe ich. Da ist natürlich etwas dran. Menge laut Rezept bezieht sich aufs Rezept. Im Reiter Abfülldaten sind Gaben zur Gärungszeit nicht gesondert aufgeführt.
Ich nutze dafür bisher die Freitextfelder, um - wenn nötig - Korrekturen wegen anderer Anstellmenge umzusetzen; die Angabe Gramm/Liter macht es da ja sehr einfach. Manchmal hätte ich mir da schon einen integrierten Rechner gewünscht, ich gehöre zu den Brauern, die es gerne genau haben.

Das Ansinnen verstehe ich wohl. Ich sehe aber auch, dass der Platzmangel dagegen spricht und dass es nicht überfrachtet wird. Letztlich wirst Du da die Richtung vorgeben müssen.

Grüße
R.

PS. Wie sieht es mit einer Mac-Version aus?

**Comment by bierbotschafter** [comment]
Hallo,

ich kann den Wunsch nachvollziehen und unterstützen, ich muss selbst immer in den Mengenfeldern rumfummeln, wenn ich die Zielmenge lt. Rezept nicht genau treffe (also immer :))

Aber bitte bedenken:
- Während der Rezeptentwicklung muss logischerweise immer mit den Rezeptdaten gerechnet werden, weil es noch keine Braudaten gibt
- Anstellmenge und Menge nach dem Hopfenseihen kann sich (um die abgefüllte Speisemenge) unterscheiden. Worauf soll sich eine Berechnung beziehen?
- Die Stelle für eine Anpassung, nämlich im Reiter Rezept, finde ich nicht logisch (s.u.). Wenn, würde es zur Gärung gehören

Vielleicht kann man für Gaben nach dem Anstellen ja mit einer prozentualen Korrektur arbeiten, die man aber bewusst "einschalten" sollte.

Das bringt mich aber zu einem weiteren Thema:

Wenn man es für alle Gaben / Zeiten / Mengen durchgängig machen will, müsste man konsequenterweise die Rezeptdaten komplett vom Brauprotokoll bzw. dem einzelnen Sud trennen. Das eine ist SOLL, das andere IST.

Bei der Zusammenfassung sind nach dem Brauen die Abweichungen teilweise zu sehen, z.B. bei der Menge oder beim Alkohol. Was ich nicht sehe, ist, ob ich am Brautag z.B. vom Maischplan abgewichen bin, indem ich 10 Minuten mehr Maltoserast gemacht habe oder ich habe 100 g mehr Malz genommen, weil der Beutel leer werden sollte. Da muss ich tatsächlich wieder das Rezept (SOLL) anpassen oder ellenlange Bemerkungen schreiben.

Hier wäre ja z.B. möglich, den Reiter Braudaten zu erweitern. Die Angaben (Gußmengen, Malzmengen, Zeiten etc.) aus dem Rezept würden übernommen und ich kann sie fallweise ändern/überschreiben, was sich in den einzelnen Sektionen der Zusammenfassung auch ausdrückt.

Ok, man darf ja bestimmt ein wenig rumspinnen ... 

Schönen Tag
Martin

**Comment by BourgeoisLab** [comment]
Erledigt mit 36a7f0ccf6538227e59caaaa7dc4749f20bb4fb4.
Es wurde im Moment einfach gelöst. Mit einem Checkbox kann ausgewählt werden, ob mit der Anstellmenge oder Rezeptmenge gerechnet werden soll.
