### ISSUE TITLE
Modale Fenster wie "Rohstoffe" sollten in der Größe anpassbar sein

### ISSUE THREAD

**Issue by schuessm** [kleiner-brauhelfer/kleiner-brauhelfer-2#236]
In der neuen Version sollten die losgelösten Fenster wie Rohstoffe und Ausrüstung etc. in der Größe wie jedes Fenster anpassbar sein, da sonst, wie in meinem Fall, auf älteren Laptops der untere Bereich des Fensters nicht erreicht wird um z.B. Hopfen oder Malz auszuwählen.
Danke!

**Comment by Rasinari** [comment]
Sind sie doch. Bitte.

**Comment by schuessm** [comment]
Hatte ich übersehen :-) Danke
