### ISSUE TITLE
Link Hilfe  zur Formelsammlung geht nicht

### ISSUE THREAD

**Issue by markussoeth** [kleiner-brauhelfer/kleiner-brauhelfer-2#237]
Der Link in der Hilfe oben zur Formelsammlung landet auf einem Error 404

https://kleiner-brauhelfer.de/formelsammlung.html

Aktuell liegt die unter
https://kleiner-brauhelfer.de/docs/formelsammlung/

**Comment by BourgeoisLab** [comment]
Der Link sollte mit der letzten Version (v2.3.2) richtig sein.
