### ISSUE TITLE
Bemerkungsfeld kann nicht (mehr) genutzt werden

### ISSUE THREAD

**Issue by RolGei** [kleiner-brauhelfer/kleiner-brauhelfer-2#238]
Heute das Update 2.3.2 eingespielt

Register Rezept - Bemerkungsfeld kann nicht mehr beschriftet werden, keine Eingabe möglich
lg roli

**Comment by Rasinari** [comment]
Unten rechts das Zahnrad.

Kannst Du bitte für Anwenderfragen den Thread im Hobbybrauerforum nutzen, dann haben alle mit ähnlichen Fragen etwas davon. 

Grüße
Radulph
