### ISSUE TITLE
Schriftart und Schriftgröße fest einstellen

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#239]
Ich vermisse eine Option, um Schrift und Schriftgröße fest einzustellen. Dieses bei jedem Eintrag in einem Bemerkungsfeld zu machen, ist auf Dauer lästig. Bei jedem neuen Eintrag wird auf 10p und erste Schrift in der Schriftsammlung zurückgestellt. Wäre schön, wenn das gefixt werden könnte.

**Comment by BourgeoisLab** [comment]
Erledigt mit c89e28eb827cb5f433903a461a1ab13ff6d69f5b.
