### ISSUE TITLE
Berechnung von Zuckergabe zur Carbonisierung falsch

### ISSUE THREAD

**Issue by matzzeglaeser** [kleiner-brauhelfer/kleiner-brauhelfer-2#240]
Im Brauhelfer 2.3.2 wird die Zuckermenge zur Carbonisierung m.E. falsch berechnet. Im Beispiel im Screenshot wird bei einem Jungbier mit 26 Grad Temperatur für 6.5 g CO2 eine Zugabe von 5.8 Gramm pro Liter berechnet. Korrekt müssten es aber 10.3 Gramm sein gemäss mehrer Online-Rechner, die ich zum Vergleich herangezogen habe.

<img width="778" alt="Bildschirmfoto 2022-03-25 um 10 17 04" src="https://user-images.githubusercontent.com/102354777/160092516-3ab3b2fd-cb12-4c49-9218-b329ea8e3020.png">
.

**Comment by Rasinari** [comment]
Die Berechnung ist korrekt. Der vorhandene Restzucker ist bereits abgezogen. Teste es mal, indem Du den Vergärungsgrad künstlich heraufsetzt, bzw. den Restextrakt herabsetzt.

**Comment by BourgeoisLab** [comment]
Kontrolliere, ob die Speisemenge wirklich auf 0 steht (--> Modul aktivieren). Wie sieht die Schnellgärprobe aus?

**Comment by matzzeglaeser** [comment]
Hi. Danke für die schnelle Antwort. Ich hatte nach dem Upgrade das Modul "Speise" tatsächlich nicht aktiviert. Hier war ein Liter Speise "versteckt". Gehe davon aus, dass es jetzt stimmt und kein Bug ist. Grüsse Mathias

**Comment by BourgeoisLab** [comment]
Das mit der Speise kommt (zu) häufig vor. Das wird in der neuen Version besser.

**Comment by matzzeglaeser** [comment]
Hi
Bei mir war das Problem, dass ich nach dem Upgrade das Modul nicht extra aktiviert habe. Wenn das per default aktiviert wäre, dann sieht man das sofort.
Danke 😊

Von: Frédéric Bourgeois ***@***.***>
Datum: Montag, 28. März 2022 um 09:32
An: kleiner-brauhelfer/kleiner-brauhelfer-2 ***@***.***>
Cc: matzzeglaeser ***@***.***>, State change ***@***.***>
Betreff: Re: [kleiner-brauhelfer/kleiner-brauhelfer-2] Berechnung von Zuckergabe zur Carbonisierung falsch (Issue #240)

Das mit der Speise kommt (zu) häufig vor. Das wird in der neuen Version besser.

**Comment by Rasinari** [comment]
In der Tat, daran denken selbst Nutzer nicht, die das erklären wollen. Das ist zu versteckt und in keiner Weise selbsterklärend. Ärgere mich, dass ich daran nicht gedacht habe. Und das ist mir auch schon öfter passiert.

So eine Funktion gehört isoliert in die Voreinstellungen, nicht versteckt in Module.

**Comment by matzzeglaeser** [comment]
Hi
Kein Problem😊 Schalt das Modul doch einfach per default an. Dann ist die Sache mit der Zuckerberechnung völlig klar und wer nie mit Speise arbeitet, kann es immer noch abschalten.
Danke übrigens für den kleinen Brauhelfer. Hilft mir als Hobbybrauer ENORM!

Grüsse
Mathias

Von: rakader ***@***.***>
Datum: Montag, 28. März 2022 um 11:13
An: kleiner-brauhelfer/kleiner-brauhelfer-2 ***@***.***>
Cc: matzzeglaeser ***@***.***>, State change ***@***.***>
Betreff: Re: [kleiner-brauhelfer/kleiner-brauhelfer-2] Berechnung von Zuckergabe zur Carbonisierung falsch (Issue #240)

In der Tat, daran denken selbst Nutzer nicht, die das erklären wollen. Das ist zu versteckt und in keiner Weise selbsterklärend. Ärgere mich, dass ich daran nicht gedacht habe. Und das ist mir auch schon öfter passiert.

So eine Funktion gehört isoliert in die Voreinstellungen, nicht versteckt in Module.

**Comment by Rasinari** [comment]
Verstehst Du falsch: Ich wollte es Dir erklären und lag falsch.
Ich arbeite nicht mit Speise. Halte das für einen Fehler. Die Gefahr der Kontamination ist zu hoch.

**Comment by matzzeglaeser** [comment]
Super! Vielen Dank. Dann ist ja alles gut!
Viele Grüsse
Mathias

Von: rakader ***@***.***>
Datum: Freitag, 25. März 2022 um 11:47
An: kleiner-brauhelfer/kleiner-brauhelfer-2 ***@***.***>
Cc: matzzeglaeser ***@***.***>, Author ***@***.***>
Betreff: Re: [kleiner-brauhelfer/kleiner-brauhelfer-2] Berechnung von Zuckergabe zur Carbonisierung falsch (Issue #240)

Die Berechnung ist korrekt. Der vorhandene Restzucker ist bereits abgezogen. Teste es mal, indem Du den Vergärungsgrad künstlich heraufsetzt, bzw. den Restextrakt herabsetzt.
