### ISSUE TITLE
Urgent: Haken "Unvergärbar" in Rohstoffe -> Zusätze

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#243]
Hohe Priorität: Der Kleine Brauhelfer produziert bei zuckerhaltigen aber nicht vergärteren Zutaten fehlerhafte Daten!
Dies passiert bei höhenwertigen Zweifach- und Mehrfachzuckern, die Bierhefe nicht verarbeiten kann.

Beispiel Milchzucker: Dieser ist zu 95-100% Teil der Stammwürze, hat aber 0% Anteil am EVG, bzw. Vol.% Alkohol.

Ich hatte bisher Milchzucker mit 0% Vergärung eingetragen. Bzgl. Vergärung ist das richtig, nicht aber in Bezug auf die Stammwürze. Ich wurde auf diesen Fehler gerade in der Facebookgruppe der Hobbybrauer aufmerksam gemacht. Im Hobbybrauerforum ist dies auch schon angesprochen worden: https://hobbybrauer.de/forum/viewtopic.php?t=27297&fbclid=IwAR3hKmxdUsLI6aE0YzYlRungbVkrSNxbMyeyjXO3JPhJE1l6bbDnKaUtr5E
Die Brewfather App. hat hierzu bereits ein Lösung: Es gibt ein Kästchen "Unvergärbar".

Bitte baldmöglichst einbauen.

Edit - ich füge die Anmerkung eines Users hinzu:
```
Technisch müsste meiner Meinung nach die Ausbeute auf 100% und ein Feld vergärbar [%] oder ja/nein eingefügt werden. Die Folge müssten dann folgende sein:
1. Wert wird zu OG addiert
2. Wert wird vor der Berechnung des EVG von OG abgezogen und
3. Nach Berechnung des FG und EVG wieder zu FG addiert.
Ob dann 4. noch der EVG angepasst werden muss, weiss ich nicht, dass wäre dann wieder was für Leute mit mehr Brautheorie-Wissen im Hintergrund.
```

**Comment by BourgeoisLab** [comment]
Erledigt mit 38df3280a2657b0a649053300d19f05c0be8576a.
