### ISSUE TITLE
Wie downloade und installier ich das Programm?

### ISSUE THREAD

**Issue by Mo3012** [kleiner-brauhelfer/kleiner-brauhelfer-2#244]
Ich weiß nicht wie ich das Programm installiere habe zwar die dateien runtergeladen aber komme einfach nicht weiter

**Comment by BourgeoisLab** [comment]
https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/releases/latest
Datei, welche zum Betriebssystem passt herunterladen und wie gewohnt installieren.
