### ISSUE TITLE
Prozentualer Anteil Extrakt Zusätze in Rezept Maischen 

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#246]
Bei einem importierten Rezept Brooklyn Sorachi Ace Ale wird Dextrose (Traubenzucker) zur Schaltung hinzugegeben. Im importieren Rezept ist der Anteil Traubenzucker an Stammwürze korrekt dargestellt. Der KBH stellt trotzdem einen Fehler fest und will 100% Malz.

Dazu wird Dextrose aus Malz herausgenommen und der Eintrag unter Zusätze gewählt. Obwohl Dextrose in den Rohstoffen mit 95% Vergärung angegeben wurde, ist nicht ersichtlich welchen prozentualen Anteil die Zugabe hat. 

Auch bei Zugaben sollte der prozentuale Anteil am Extrakt dargestellt werden. Es ist nicht ersichtlich, was es mit der fehlenden Angabe auf sich hat. Zumindest ist es verwirrend.

Bitte fehlende Angabe einbauen.
<img width="849" alt="Brookyln Import" src="https://user-images.githubusercontent.com/51321250/162985797-4cf7cc7d-1c8f-432b-832d-6517839900e3.png">
<img width="823" alt="Brookyln Korrektur" src="https://user-images.githubusercontent.com/51321250/162985809-553c9bc0-fc08-4301-9f79-4048ed50e7c9.png">

**Comment by BourgeoisLab** [comment]
Siehe #263
