### ISSUE TITLE
Automatische HTML-Formatierung ist übereifrig

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#247]
Wenn ich das
&lt;pre>Profiles (ppm)	Exist	Mash	Finished	
Ca		42	75	75
Mg		8	8	8
Na		40	40	40
SO4		39	117	117
Cl		58	58	58
HCO3		125	125	NA
SO4/Cl Ratio				2,0
				
Estimated Mash pH		5,43	SU	
				
Mineral Additions (gm)	Mash	Sparge		
Gypsum		2,8	1,3	
				
Mash Acid Additions      				
 	 	 	0,0	(ml)
Sparge Acid Addtions				
Lactic	80,0	%	1,6	(ml)&lt;/pre>

in das Hauptbemerkungsfeld in den neuen HTML-Editor paste, zerhackstückelt es mir das HTML mit vermeintlicher intelligenter, automatischer Formatierung zu so etwas:
![grafik](https://user-images.githubusercontent.com/33151586/163729551-0a95c826-59a2-4fbd-99c2-77212fc96b48.png)

Im Spickzettel hat das dann zig Zeilenumbrüche und ist nicht mehr vernünftig ausdruckbar.
![grafik](https://user-images.githubusercontent.com/33151586/163729585-81c3793b-3fe7-4d73-88d3-f75836592d28.png)

**Comment by Rasinari** [comment]
Das sieht vollkommen in Ordnung aus. Ich kann da nichts "Verhackstücktes2 erkennen.
In Brew'n Water sind es noch deutlich mehr Angaben, vor allem beim Zugabe von Mischwasser.

Das muss so aussehen.

**Comment by LondonRain** [comment]
Nein, das muss definitiv nicht so aussehen. In meinem HTML sind keine Absätze und zusätzliche Zeilenumbrüche drin. Also gehören da auch keine automatisch ergänzt.

**Comment by Rasinari** [comment]
An so etwas stört man sich nicht.

**Comment by LondonRain** [comment]
Man braucht halt vier statt zwei Seiten zum Ausdrucken. Misch dich doch einfach nicht ein, wenn es dich nicht stört. 🤷🏼‍♂️

**Comment by BourgeoisLab** [comment]
Als workaround kannst du SHIFT+ENTER benutzen. Dann sollte der pre-Tag zusammengefasst werden.

**Comment by LondonRain** [comment]
> Als workaround kannst du SHIFT+ENTER benutzen. Dann sollte der pre-Tag zusammengefasst werden.

Probiere ich morgen aus. Vielen Dank! Du meinst statt der eigentlichen Zeilenumbrüche in dem hineinkopierten Text.

Falls das kompliziert zu fixen ist und es einfacher wäre diese WYSIWIG-Automatiken optional ganz zu deaktivieren, wäre das

**Comment by Rasinari** [comment]
> Man braucht halt vier statt zwei Seiten zum Ausdrucken. Misch dich doch einfach nicht ein, wenn es dich nicht stört. 🤷🏼‍♂️

Warum bringst du es nicht gleich auf den Punkt?

**Comment by LondonRain** [comment]
> Als workaround kannst du SHIFT+ENTER benutzen. Dann sollte der pre-Tag zusammengefasst werden.

Ja, irgendwie kriegt man das dann so hin. Danke! Das ist als Workaround okay, aber als Dauerlösung extrem unpraktisch.

**Comment by LondonRain** [comment]
Gibts da schon Ideen zu? Das ist doch recht nervig für den Ausdruck.

**Comment by BourgeoisLab** [comment]
Die Zeilenumbrüche kommen wegen der ersten Zeile: `<div style="white-space: pre-wrap;">...</div>`.
Diese Zeile ist aber nur nötig, wenn die Bemerkung nicht im HTML Format ist. Also so wie früher.

Eine (inoffizielle) Version, ohne diese Eintrag, findest du hier. Es wirkt sich aber nicht auf die alten Bemerkungen aus!
Win: https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/actions/runs/2684949355
macOS: https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/actions/runs/2684949356
Linux: https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/actions/runs/2684949359

**Comment by LondonRain** [comment]
Das klappt prächtig. Herzlichen Dank!

**Comment by Rasinari** [comment]
> Die Zeilenumbrüche kommen wegen der ersten Zeile: `<div style="white-space: pre-wrap;">...</div>`. Diese Zeile ist aber nur nötig, wenn die Bemerkung nicht im HTML Format ist. Also so wie früher.
> 
> Eine (inoffizielle) Version, ohne diese Eintrag, findest du hier. Es wirkt sich aber nicht auf die alten Bemerkungen aus! Win: https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/actions/runs/2684949355 macOS: https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/actions/runs/2684949356 Linux: https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/actions/runs/2684949359

Entschuldigung, wenn ich hier noch einmal einhake: Ich kann den Fehler nicht nachstellen; bei mir wird alles ohne ärgerlichen Papierverbrauch ausgedruckt (macOS Monterey, Brother Netzwerkdrucker).

Ein großes Problem ist aber in beiden Versionen 2.4.0 und 2.4.1 die Behandlung der Textfarbe im Bemerkungsfeld des Reiters Rezept: bei gewählter Ansicht Farbschema Dunkel wird bei Copy und Paste in das Bemerkungsfeld die Darstellung Schwarz auf Dunkel dargestellt. Im Spickzettel ist die Darstellung korrekt, ebenso PDF und Ausdruck.

Wandelt man jedoch im Reiter Rezept den Text in Textfarbe Weiß um, erfolgt die Darstellung im Spickzettel überall als Weiß auf Weiß.

Wenn das hier zu weit führt, sollte man ein neues Issue aufmachen.
Wenn behoben, würde es sich anbieten eine offizielle 2.4.2 zu veröffentlichen.

Danke vorab.
