### ISSUE TITLE
Konsistente Benamung von Git-Tags

### ISSUE THREAD

**Issue by hurra** [kleiner-brauhelfer/kleiner-brauhelfer-2#249]
Hallo,

die Git-Tags sind leider nicht konsistent.
die `2.4.0` heißt im Git-Tag `v.2.4.0`, während die Versionen davor ohne dem `.` nach dem `v` geschrieben sind.

Kann das noch angeglichen werden?

Gruß Lorenz

**Comment by BourgeoisLab** [comment]
Kleiner Tippfehler.
Erledigt.
