### ISSUE TITLE
Mac-Version 2.4.0

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#250]
Kann jemand netterweise die Mac-Version kompilieren. Ich selber habe kein QT mehr, die ganze Installation ist über den Jordan gegangen. Danke vorab.

**Comment by realholgi** [comment]
Bin am Pfingstmontag wieder aus dem Urlaub zurück. Dann…

**Comment by realholgi** [comment]
Habe `kbh2_v2.4.0_macos.zip` gebaut und bei den "releases" hinzugefügt.
