### ISSUE TITLE
Bug: Hopfenkorrektur bei importierten MMuM-Rezepten verteilt Korrekturwert nicht

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#258]
Importiert man ein MMuM-Rezept, muss man die Mengen kurz darauf an die Anlage anpassen. Diese Anpassung weist der KBH rot unterlegt aus.

Bei Malz verteilt er die Differenz auf alle Malze, sobald ein Malz zur Korrektur angeklickt wird. Diese Technik versagt bei Hopfen. Dort wird der Korrekturwert allein dem einen angeklickten Hopfen zugeschlagen.

In Folge ist das Rezept nicht mehr brauchbar.

**Einzig ein Schritt zurück stellt die prozentuale Verteilung her. Dieser Workaround erschließt sich niemand.**

Da MMuM-Rezepte oft importiert werden, sollte dieser Bug schnellstmöglich behoben werden.

Eine ausführliche Beschreibung findet sich auf hobbybrauer.de

**Comment by BourgeoisLab** [comment]
Erledigt mit [5d3bfc9](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/commit/5d3bfc90bf90c9505f7e38be655fb205afb595c5).

**Comment by Rasinari** [comment]
Vielen vielen Dank. Das ist wirklich eine Verbesserung!
