### ISSUE TITLE
Bug: Leerzeichen nach Punkt und Komma verschwunden - auch bei Tooltips

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#259]
Einige frühere Versionen stellten nach Interpunktion kein Leerzeichen dar. Dieser mittlerweile behobene Bug hat ältere Einträge allerdings nicht verschont. So haben in den Freiformfeldern und den Rohstoffeinträgen Einträge nach Punkt und Komma kein Leerzeichen.

Betroffen davon sind auch die Tooltips!

Was ist davon zu halten, eine Funktion einzubauen, die markierten Textstellen Leerzeichen wieder hinzufügt?

Die Tooltips müssen indes komplett repariert werden.

Beim Anlegen neuer Rohstoffeinträge muss ein Leerzeichen 2x eingegeben werden, um 1x zu erscheinen. 1x Leerzeichen ergibt kein Leerzeichen. (Mac)

**Comment by Rasinari** [comment]
eine Überprüfung an anderer Stelle hat ergeben, dass es vermutlich an der eingebauten Schrift liegt. Diese verfügt auf Mac über ein unzureichendes Kerning nach Interpunktionen, die Leerzeichen nahezu unsichtbar machen. Problem scheint hier eine zu geringe Berechnung des Gevierts zu sein.

Ein Schriftwechsel sollte das Problem beheben.

1 Leerzeichen
<img width="230" alt="Bildschirmfoto 2022-10-03 um 21 14 01" src="https://user-images.githubusercontent.com/51321250/193659743-a4df3148-58f4-4d73-a07a-5bc240b64ede.png”>

2 Leerzeichen
<img width="188" alt="Bildschirmfoto 2022-10-03 um 21 14 26" src="https://user-images.githubusercontent.com/51321250/193659817-9896c100-9462-414d-b0d1-1fa6fea52bf5.png">

**Comment by BourgeoisLab** [comment]
Schriftart empfehlen will ich nicht. Einerseits ist das eine Präferenzsache und andererseits kommt es auf das System inklusive Hardware an (z.B. Bildschirmgrösse).
