### ISSUE TITLE
Darstellungsproblem beim Popup-Menu "beim Ausschlagen"

### ISSUE THREAD

**Issue by realholgi** [kleiner-brauhelfer/kleiner-brauhelfer-2#26]
Wird abgeschnitten in der beta2. 

<img width="700" alt="Bildschirmfoto 2019-07-28 um 21 51 32" src="https://user-images.githubusercontent.com/980419/62012108-36840f80-b182-11e9-86be-398aa703cce3.png">

**Comment by BourgeoisLab** [comment]
Ich kann das unter Windows und Linux nicht beobachten. Ist es nur in der Liste abgeschnitten, oder auch wenn es ausgewählt wurde?

Ich sehe gerade keine Einstellmöglichkeit, wo ich das ändern könnte. Wir könnten es aber auf "Auschlagen" ändern und auf das "beim" verzichten.

In beta1 hiess es noch "Nachisomerisierung" statt "Kochende". Vielleicht ist es deswegen jetzt anders.

**Comment by realholgi** [comment]
Ist nur in der Liste. Wenn der Eintrag ausgewählt wurde, stimmt die Anzeige.

**Comment by BourgeoisLab** [comment]
Text heisst neu nur noch "Ausschalgen". Commit fa2e06fc29108d2439081734bf9be19df80900c5.
