### ISSUE TITLE
Bug: Erneut keine Sortierung in Rohstoffliste

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#260]
In einigen früheren Versionen setzte die alphabetische Sortierung in den Rohstoffeinträgen aus und alles war durcheinander. Bei jedem Aufruf musste die Sortierung nach Name erneut manuell ausgelöst werden. Dieser Bug wurde dann behoben - mit dem neuen QT ist er aber wieder da.

**Comment by BourgeoisLab** [comment]
Das kann ich nicht bestätigen. Bei mir alles i.O.
Nach einem Update kann es passieren, dass man die Sortierung nochmals auslösen muss, aber danach sollte es nicht mehr nötig sein.

**Comment by Rasinari** [comment]
Gerade durchexerziert. Ab Neustart wieder alles i.O. in allen möglichen Variationen. keine Ahnung, woran das lag - an einem alten Rezept? Ich sage an, sollte es erneut auftreten.
