### ISSUE TITLE
Weitere Zutaten in Kalkulation von Schüttungsverteilung einbeziehen - möglicher Bug

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#263]
Beim Übertragen eines amerikanischen Rezeptes (das bekannte Pliny the Elder) mit Dextrose in der Schüttung stoße ich auf ein nicht auflösbares Problem, dergestalt der Vergärungsgrad der Dextrose nicht berücksichtigt, bzw. prozentual dargestellt wird.

Prozentual wird der Anteil richtig berechnet, aber nciht ausgewiesen. Nutzt man „Differenz verteilen“, schleichen sich Fehler ein.

Unabhängig von der weiteren Zutat, die prozentuale Verteilung der Schüttung bleibt unverändert; nur der Extraktanteil ändert sich. Unabhängigvom Anlagewert, die prozentuale Verteilung bleibt immer gleich. Die Differenz kann nicht eliminiert werden, wenn eine ausbeuterelevante Zutat ignoriert wird.
Auch der Restextrakt und der Alkoholgehalt  bleiben bei einem Zusatz unberücksichtigt. Ich kann tonnenweise Traubenzucker reinschütten, der Alkoholgehalt bleibt unverändert.

Kann man diesen Umstand künftig berücksichtigen und eine Lösung hierfür einbauen?
**Ich meine, man sollte unbedingt bei einem Zusatz als Gabe ein Prozentfeld einbauen. Das fehlt hier eindeutig!**

Aus dem GUI geht nicht hervor, wie der KBH bei einer bestimmten Zutat, die prozentual festgelegt ist, richtig rechnet. So gesehen ist das eigentlich ein Bug.

Edit: Wenn man die Sudhausausbeute verändert, passt sich die Schüttung an, aber die Zutat NICHT.

<img width="765" alt="Dextrose_in_Schuettung" src="https://user-images.githubusercontent.com/51321250/198929406-2da9fe49-800f-4836-86c8-015baafa8b01.png">

Edit: Es heißt zwar richtig, dass die Summe der Malze nicht der Gesamtschüttung entspricht, dies ist in der Praxis aber hinderlich. Schließlich will der Brauer wissen, welche prozentuale Verteilgung ALLE seine Zutaten haben. Meiner Meinung nach sollte dieses Hindernis beseitigt werden, es behindert die Rezeptentwicklung, wenn man ein Geschmacksbild im Kopf hat, dies aber nicht darstellen kann.

<img width="648" alt="Bildschirmfoto 2022-10-31 um 05 00 47" src="https://user-images.githubusercontent.com/51321250/198928724-03cb6c04-a38f-4d72-a227-98f269828804.png">

**Comment by BourgeoisLab** [comment]
Das ist die gleiche Issue wie #246, oder?

**Comment by Rasinari** [comment]
Ja, ist das gleiche Themenfeld, nur mit einer leicht veränderten Fragestellung. Kann zusammengeführt werden.

**Comment by BourgeoisLab** [comment]
Die Prozentangaben beziehen sich im Moment nur auf die Malzgaben. Das zu ändern, ist nicht ganz einfach. Soll das Extrakt aus den weiteren Zutaten auch berücksichtigt werden gibt es zwei Probleme:
1. Wenn die Einheit der Zutat keine Gewichtsangabe ist, sondern z.B. in ml/kg, können die Mengen nicht mit den Malzmengen (kg) verglichen werden. Hier müsste sich die Prozentangabe auf den Extrakt (°P) beziehen, statt wie bisher auf die Menge. --> lösbar
2. Das grössere Problem, ist wenn die Zutat, nicht beim Maischen, sondern beim Kochen oder Gärung eingetragen wird. Auch diese müsste für die Prozentangabe berücksichtigt werden. Das ist aus meiner Sicht viel unübersichtlicher, da diese nicht gleichzeitig sichtbar sind.

Wegen 2 tendiere ich, es so zu belassen. Die Prozente beziehen sich nur auf die Malzgaben.

**Comment by Rasinari** [comment]
Zu 2. würde es Sinn machen, diese Entscheidung dem Brauer/User zu überlassen?

Man kann sehr gut die Fruchtzuckeranteile recherchieren und dann mit Verdünnung/Zeit etc. die Ausbaute bestimmen. Das kann zwar fehlerbehaftet sein, sollte aber im Entscheidungsspielraum des Anwenders sein. Es gibt ja auch den Hinweis auf verfälschende Zutaten - das wird hier ja nicht geändert.

**Comment by BourgeoisLab** [comment]
Ich glaube das Beste, wäre ein zusätzlicher Prozentbutton beim Extrakt, welcher alle Einträge in den Reitern (Maischen/Kochen/Gärung) berücksichtigt.

**Comment by Rasinari** [comment]
Wo in Github definiere ich Daumen hoch? 

Exakt - so würde ich mir das vorstellen. Hoffentlich macht es nicht zu viel Arbeit!!

**Comment by BourgeoisLab** [comment]
Erledigt mit 7a1b49833b0f0856c7f10072f6366574047f4f83.
