### ISSUE TITLE
Hopfen Spalte Pellets

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#264]
In Rohstoffe -> Hopfen -> Pellets reagiert das Ankreuzfeld nur mit gutem Zureden: Der Bereich ist zu klein.

Bitte korrigieren.

**Comment by BourgeoisLab** [comment]
Die Grösse der Checkbox ist im Programm durchgehen gleich. Sehe nicht wirklich Handlungsbedarf in diesem speziellen Fall.

Das Problem scheint zu sein, dass es mehrere Clicks braucht, bis es reagiert. War das immer so? Mit der Tastatur (Space) funktioniert es besser.

**Comment by Rasinari** [comment]
Das ist richtig - es braucht mehrere Klicks.
Das war nicht immer so - ist neu.

**Comment by BourgeoisLab** [comment]
Erledigt mit b3d8b8c231328404a218196b5f815cbb71c18ab5.
