### ISSUE TITLE
Freitextfelder „Maischen“

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#265]
Es fällt wohl erst dann auf wenn man es braucht: Im Reiter Rezept, Untermenü Maischen, wären zusätzliche Freitextfelder unter einzelnen Gaben sinnig wie sie bei den Untermenüs „Kochen“ üblich sind, sobald „Weitere Zutaten„ hinzugefügt werden.

In meinem Fall ging es um Rohfrucht, und da diese zuweilen zickig sein kann, würden sich bei außergewöhnlichen Zutaten Freitextfelder empfehlen. (In meinem Fall war es Polenta, die vorbehandelt werden muss.)

Fände ich toll, wenn das zugefügt werden könnte! (Ich habe es in den allgemeinen Bemerkungen gelöst - aber da gehört so ein Sonderfall nicht hin, sondern unmittelbar unter die Gabe.)

Ein gesamtes Freitextfeld für das Untermenü wäre wohlmöglich klarer und einfacher - das würde dann aber auch für alle weiteren Prozessschritte Koche - Gärung - Maischplan gelten.
R.

**Comment by BourgeoisLab** [comment]
Ich würde es nicht für jede Gabe machen, sondern pro Reiter (Maischen/Kochen/Maischplan/Wasseraufbereitung).

Weitere Abhilfmöglichkeit: Ein Zusatz "Bemerkung" in der Rohstoffliste definieren:).

**Comment by Rasinari** [comment]
So meine ich das auch. Beides hat seinen Charme!

**Comment by BourgeoisLab** [comment]
Erledigt mit 11e5ec3c89ca4c8b78532013be39bbee804e31ee.
