### ISSUE TITLE
Reiter Rezept: Gärung - Hefestarter mit Brix

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#272]
Super, dass jetzt endlich ein Hefestarter berücksichtigt wird. Das erleichtert so vieles. Besser: Ein Riesengewinn!

Ein i-Tüpfelchen wäre noch, dass wie an anderen Stellen auch per Pop-up mit Brix gerechnet werden kann.

**Comment by BourgeoisLab** [comment]
Erledigt mit 648c471c0e8de8b9c43b40c8be760648ec1da345.
