### ISSUE TITLE
Maischeplan: Änderung Rastennamen ändert auch Zeit und Temperatur

### ISSUE THREAD

**Issue by markussoeth** [kleiner-brauhelfer/kleiner-brauhelfer-2#273]
Hallo,
mir ist eben folgendes aufgefallen. 
Nach Import eines Rezeptes wollte ich die Rasten umbenennen, mit den in der Drop-Down-Liste bereitgestellten Bezeichnungen. 
Sobald ich dort eine Änderung vornehme, werden auch die Felder Temperatur und Zeit geändert. 
Das ist ärgerlich, weil sich dadurch eben auch das Rezept ändert.

Beispiel Rezept war hier 
https://www.maischemalzundmehr.de/index.php?id=1761&inhaltmitte=rezept

Daten direkt nach Import
![grafik](https://user-images.githubusercontent.com/306641/211785227-5aa21e68-a56d-48c9-8f9b-a47618b207d6.png)

Daten nach Umstellung
![grafik](https://user-images.githubusercontent.com/306641/211785413-eaff105b-db4e-409d-8cee-bc1ecf443202.png)

Ich denke, das kommt durch default Werte für die Anlage eines neuen, noch leeren Rezepts. 
Dann müsste geprüft werden, ob Felder wie Temperatur und Zeit schon belegt sind. 

Daten bei einem neuen, leeren Rezept
![grafik](https://user-images.githubusercontent.com/306641/211786437-12a02ca4-22a2-4659-8887-a0fcfa8b5c0f.png)

**Comment by Rasinari** [comment]
Das Verhalten ist schon immer so, da an die voreingestellten Rasten je eine Temperatur geknüpft ist.
Ich stimme Dir zu, das kann nervig sein, eine Entkoppelung von er Temperatur würde Sinn machen.

Ein ähnliches Verhalten tritt bei einem gebrauten Sud auf. Dort werden alle Rastfelder auf Gummirast gestellt. Man muss erst entsperren, um die originalen Rasten zu sehen. Gesperrt wird immer nur Gummirast angezeigt.

**Comment by BourgeoisLab** [comment]
Ich sehe das anders. Will man die Rast umbenennen, kann man den Text einfach eingeben. Wählt man aus der Liste, ist es eben eine vordefinierte Rast mit einer vordefinierten Temperatur. Das ist z.B. bei der Rezepterstellung sinnvoll.

Dass bei gebrauten Sud "Gummirast" steht, ist natürlich ein Bug, welcher mir noch nie aufgefallen ist.

**Comment by markussoeth** [comment]
Aber das geht an der Usability vorbei.
Meiner Meinung nach eher so:

- Steht da nichts, also will ich ein Rezept erstellen, werden die Felder mit default Werten befüllt, die ich danach ändern kann.
- Ist schon ein Rezept importiert und ich kann aus einer Liste Namen auswählen, sollte diese Aktion nicht die vorher eingestellten Werte beeinflussen. Das erwartet man einfach nicht, sondern nur, dass sich der Name ändert. 

Ich hatte mir mal die Quellen runtergeladen, um mal zu schauen, ob ich da helfen kann. Aber leider hab ich so keine Ahnung von C Programmierung. Mit meinen Kenntnissen aus dem Webdevelopment bin ich da nicht weitergekommen.

**Comment by BourgeoisLab** [comment]
So einfach ist es nicht. Nach deinem Prinzip bei der Rezepterstellung:
- ich wähle aus versehen Maltoserast
- -> die Temperatur wird entsprechend gesetzt
- ich korrigiere den Eintrag am Kombirast
- -> die Temperatur wird NICHT angepasst (weil bereits etwas steht)
 
Aus Usability Sicht finde ich das schlimmer.
Jetzt ist es klar: Texteingabe -> keine Anpassung, Auswahl per Dropdown -> Anpassung.

**Comment by Rasinari** [comment]
Mein Beitrag hatte es vorhin verhagelt.

a) Eine leere Vorgabe birgt Flüchtigkeitsfehler und Fehler in der Datenbank. Dies gilt für den Namen wie für die Temperaturvorgabe wie für die Zeitvorgabe. Ich sehe das auch so: Texteingabe: keine Anpassung, DropDown: Anpassung.
1. Vorschlag: Optimalwerte der Raststufen bei Temperaturvorgabe geben, desgleichen Zeitvorgabe. Ich überarbeite hier auch noch die Tooltips.
Wie wäre es, wenn das Drop-Down mehr Eigeninitiative erfordert und stattdessen nach Standard die erste Rast mit Einmaischen als 1. Rast gesetzt wird? Jede weitere Rast wird dann durchnummiert mit immer der gleichen Zeit (0 min) und Temperatur (0 °C), damit der Anwender auch wirklich gezwungen wird, hier etwas zu tun. Das ist selbsterklärender - mit Hinblick auf Einsteiger - als ein Normalwert von z.B. 30 min, den ein Anfänger aus Versehen nicht antastet.
Das Drop-Down dann wie vorgeschlagen.

b) Das Einmaisch- Abmaischverfahren ist unnötig kompliziert. Es kann verkürzt werden. Das gesonderte Einmaischen ist verwirrend. Da die inkludierte anschließende Rast nicht angezeigt wird, muss die Zeit auf Null gesetzt werden, dann die eigentliche Rast ohne Einmaischtemperatur gesetzt werden. Andernfalll wird im Brauprotokoll nicht ersichtlich, um welche Rast es sich gehandelt hat. Die Lösung das per Text o, Feld Einmaischen zu lösen, ist unbefriedigend.
2. Vorschlag: Beim ersten Auftreten einer Rast, wird die Information zum Einmaischen automatisch hinzugefügt. Das gleiche gilt beim Auftreten der 2. oder letzten Rast für das Abmaischen.

c) Ich weiß nicht wie oft das zutrifft, aber Korrekturen der Rasten sollten daraufhin überprüft werden, dass die vorgegebenen Zeiten nicht jedes Mal auf Standard-Zeitvorgabe zurückgesetzt werden. Dies hat mich bereits mehrere Mal bei der  Rezeptentwicklung gezwungen, die Datenbank aus dem Backup neu einzuspielen. Das Verhalten ist identisch zu dem der Gummirast. -> Bug.
3. Vorschlag: einmal getätigte Zeitvorgaben werden beim Entsperren nicht automatisch auf Standardwerte gesetzt.

d) Beim Zubrühen wird zwar die korrekte Temperatur berechnet, es wird aber nicht die Sudhausausbeute bzw. Schüttungskorrektur angewandt. Ich hatte gestern zum 3. x den Fall, dass der Zielwert Stammwürze bei Kochbeginn im Reiter Braudaten extremst abgewichen ist - gestern um genau 3 °P - erwartet 11,8, tatsächlich 8,8. ich bin mir nicht sicher, aber es kann sein, dass hier ein bug vorliegt
4. Vorchlag: Die Berechnung Zubrühen überprüfen und ggf. überarbeiten.

Wenn Punkt 4 zu abseitig ist, eröffne ich für diesen Punkte ein neues Issue.

**Comment by markussoeth** [comment]
@BourgeoisLab 
Nun, da habe ich noch folgende Anmerkung dazu:
"So einfach ist es nicht. Nach deinem Prinzip bei der Rezepterstellung:"
Wenn jemand selbst Rasten anlegt, gehe ich davon aus, dass die Person weis, was sie tut und entsprechend die Temperaturen und Rasten noch selbst anpasst. 
Natürlich ist es ein tolles Angebot, wenn da schon bei einer Erstanlage Temperaturen und Zeiten vorgegeben werden. Wie  @Rasinari auch erwähnt schon, um auch Flüchtigkeitsfehler in der Datenbank zu vermeiden. 

Anders, wenn jemand unbedarftes, wie ich einfach mal die richtigen Rasten als Bezeichnung hinterlegen möchte und diese Änderung einfach das Rezept ändert.

Aktuell ist es eben auch leider so, dass bei Texteingabe ein Wert aus der Drop-Down-Liste vorgeschlagen wird. Ein ganz normales Verhalten. Bestätige ich den vorgeschlagenen Wert, wird das Rezept geändert. 
Das finde ich nicht gut. 

@Rasinari zu deinen Anmerkungen
"1. Rast gesetzt wird? Jede weitere Rast wird dann durchnummiert mit immer der gleichen Zeit (0 min) und Temperatur (0 °C), damit der Anwender auch wirklich gezwungen wird, hier etwas zu tun. "
Finde ich einen sehr guten Vorschlag

"b) Das Einmaisch- Abmaischverfahren ist unnötig kompliziert."
Ich finde das ganz ok so. Kann von mir aus bleiben. Irgendwie wirkt das so schön technisch. :-)

" Ich weiß nicht wie oft das zutrifft, aber Korrekturen der Rasten sollten daraufhin überprüft werden, dass die vorgegebenen Zeiten nicht jedes Mal auf Standard-Zeitvorgabe zurückgesetzt werden. "
Ja genau, darum geht es mir in diesem Issue.
Mein Vorschlag:
Einmal getätigte Zeitvorgaben werden **nie** automatisch auf Standardwerte gesetzt.


Danke an beide nochmal für die nette Diskussion

**Comment by BourgeoisLab** [comment]
> Wenn jemand selbst Rasten anlegt, gehe ich davon aus, dass die Person weis, was sie tut und entsprechend die Temperaturen und Rasten noch selbst anpasst. 

Der KBH soll auch Anfänger helfen. Ein Vorschlag für die Temperatur & Zeit sollte es auf jeden Fall geben.


> Aktuell ist es eben auch leider so, dass bei Texteingabe ein Wert aus der Drop-Down-Liste vorgeschlagen wird. Ein ganz normales Verhalten. Bestätige ich den vorgeschlagenen Wert, wird das Rezept geändert. Das finde ich nicht gut.

Das habe ich gestern auch gesehen. Das finde ich auch nicht gut.

Die Lösung wird wahrscheinlich so aussehen, dass der Dropdown durch ein Freitextfeld ersetzt wird. Nebendran wird es ein Button geben, mit dem man eine Rast aus einer Liste auswählen kann.

**Comment by Rasinari** [comment]
> Die Lösung wird wahrscheinlich so aussehen, dass der Dropdown durch ein Freitextfeld ersetzt wird. Nebendran wird es ein Button geben, mit dem man eine Rast aus einer Liste auswählen kann.

Sehr gute Lösung!

**Comment by BourgeoisLab** [comment]
Erledigt mit 31f1a57a1015a8e201bc7e41810774247f5ed6e3.

Es ist weiterhin nur ein Dropdownmenu. Aber die Autovervollständigung ist ausgeschaltet und die Temperatur & Zeit werden nur gesetzt, wenn aus dem Menu ausgewählt wurde. Die Variante mit dem Freitext + Button fand ich nicht sehr elegant.

**Comment by Rasinari** [comment]
Großartig und rücksichtsvoll. Danke. Gerade an Anfänger muss man denken.

**Comment by markussoeth** [comment]
Danke für die Arbeit!
