### ISSUE TITLE
Bug: Absturz durch nachträgliches Ändern der Messwerte Hauptgärung

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#283]
Das nachträgliche Ändern eine Messwertes in der Hauptgärung (°Plato oder °Brix) führt unter macOS seit vielen Versionen zuverlässig zum Absturz. Ich vermute ein Problem mit der Laufzeit dahinter.

**Comment by BourgeoisLab** [comment]
Kann nicht reproduzieren. Mehr Info nötig.

**Comment by Rasinari** [comment]
ein Bild sagt mehr als Worte. Direkt nach Enter beim 2. Eintrag Restextrakt an gleicher Stelle, stürzt das Programm ab. Reproduzierbar seit 2 Jahren.
![Absturz](https://user-images.githubusercontent.com/51321250/219199349-9068d853-9f73-4a78-8f45-e3a10c16b7d0.jpg)

**Comment by BourgeoisLab** [comment]
Erledigt mit 6d5dcd005b25341f7bf39d6e99a4c8094adf5ba5.
