### ISSUE TITLE
BeerXML-Export und Fermentable-Yield

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#287]
Beim BeerXML-Export wird für alle Fermentables immer 100% Yield angenommen, vermutlich weil die Info im KBH ja nicht verfügbar ist. Das führt dann in anderer Software zu einer falschen Schüttungsberechnung. Falls es in BeerXML valide den Wert/das Tag/die Zeile einfach wegzulassen, würde ich das tun. Falls nicht, sollte der verwendete Wert bei Malzen  ein niedrigerer Durchschnittswert (80%?) sein.

**Comment by Rasinari** [comment]
Ist das nicht zu sehr geschätzt? Ich kenne das nicht, aber muss man bei Malzen nicht immer von 100% ausgehen? Was wäre mit 80% gewonnen? Wäre es nicht zielführender zuerst zu wissen, warum dieser Wert für andere Software so wichtig ist und wie er angesetzt wird?

**Comment by LondonRain** [comment]
100% ist Zucker. Andere Software (konkret Grainfather) rechnet dann das Rezept so als ob das Malz so viel beitragen würde wie Zucker.
http://howtobrew.com/book/section-2/what-is-malted-grain/table-of-typical-malt-yields

**Comment by Rasinari** [comment]
Das geht natürlich gar nicht. Dann würde ich das Feld beim Sport einfach weglassen. Denn den Vergärungsgrad einzelner Malze zu bestimmen, dürfte ein Hexenwerk sein.

Selbst bei Zucker ist das ja nicht fix; Traubenzucker hat nur 69% von Haushaltszucker.

**Comment by BourgeoisLab** [comment]
Man darf es nicht weglassen (http://www.beerxml.com/beerxml.htm).
Ich habe kein Problem damit, 80% (oder einen anderen konstanten Wert) zu schreiben,.

**Comment by Rasinari** [comment]
Ich muss gestehen, dass ich auf diesem Feld blank bin. Es sollte dann auf jeden Fall eine Handreichung geben, welche Werte heranzuziehen sind. Das wäre ein Thema für die Dokumentation, die TT sowieso.
Bei Zucker habe ich dazu schon einiges geschrieben.

**Comment by Rasinari** [comment]
Vielleicht sollte man zwischen Basis- und Röstmalzen unterscheiden, vgl. Zeile 6 und 9:
https://braumagazin.de/malzanalyse-parameter/

**Comment by BourgeoisLab** [comment]
Auf welchen Wert wollen wir uns einigen?  Ich schlage 77% vor. Das ist der Mittelwert aus den 6 ersten Einträgen aus http://howtobrew.com/book/section-2/what-is-malted-grain/table-of-typical-malt-yields

**Comment by Rasinari** [comment]
Mittelwert hört sich gut an!

**Comment by LondonRain** [comment]
Find ich gut.

Alternativ hätte ich nur noch die Idee, 0 hineinzuschreiben, wenn ganz weglassen nicht erlaubt ist. Falls das denn erlaubt ist. Dann würde es vermutlich relativ schnell auffallen.

Bin unschlüssig was besser ist.

**Comment by BourgeoisLab** [comment]
Erledig mit 058998848feb79f09c7e66516601c249c5f77859.
Ich habe es mal auf 77% gesetzt.
