### ISSUE TITLE
Support für Qt 6.5

### ISSUE THREAD

**Issue by lolli78** [kleiner-brauhelfer/kleiner-brauhelfer-2#288]
Hallo,
unter Ubuntu 22.10 läuft der kbh-2 2.5.0 mit Qt5.15.2 nicht rund, so sind z.B. die Hilfeseiten leer und der "Spickzettel", der jetzt "Audruck" heißt, auch. Und irgendwas stimmt da mit SSL nicht:

qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
DlgCheckUpdate: Network error: "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."

Mit Qt6.5.0 sieht das alles viel schöner aus und funktioniert auch, bis ein Sud geöffnet wird (das ging mit dem kbh-2 2.4.0 noch).

Gibt es Pläne für Qt 6.5?

**Comment by BourgeoisLab** [comment]
Ja. Es wurde bereits ein Branch für Qt 6 erstellt.
Hast du die KBH Version für Qt5.15.3 getestet?

**Comment by Ventusfahrer** [comment]
Wurde der kbh unter Ubuntu installiert oder sprichst Du von der AppImage Version?


> Hallo, unter Ubuntu 22.10 läuft der kbh-2 2.5.0 mit Qt5.15.2 nicht rund, so sind z.B. die Hilfeseiten leer und der "Spickzettel", der jetzt "Audruck" heißt, auch. Und irgendwas stimmt da mit SSL nicht:
> 
> qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate DlgCheckUpdate: Network error: "Im Ablauf des SSL-Protokolls ist ein Fehler aufgetreten."
> 
> Mit Qt6.5.0 sieht das alles viel schöner aus und funktioniert auch, bis ein Sud geöffnet wird (das ging mit dem kbh-2 2.4.0 noch).
> 
> Gibt es Pläne für Qt 6.5?

App-Image oder installiertes .deb Paket?

**Comment by lolli78** [comment]
> Ja. Es wurde bereits ein Branch für Qt 6 erstellt. Hast du die KBH Version für Qt5.15.3 getestet?

Oh super! Den Qt6-Branch hatte ich noch nicht gesehen - der funktioniert wesentlich besser (mit dem bereits bekannten Bug, dass manche Ausgaben mehrfach erscheinen) :-)

AQT kennt nur Qt 5.15.2 unter Linux, deshalb hatte ich die 5.15.3 nicht ausprobiert.

**Comment by lolli78** [comment]
> App-Image oder installiertes .deb Paket?

Hab' das .deb installiert.

**Comment by lolli78** [comment]
Ich verwende jetzt den Qt6-Branch, damit ist das Problem für mich gelöst. Wäre natürlich super, wenn es dafür auch ein fertiges .deb gäbe. Und es wäre super, wenn es bei den Release-Ankündigungen einen Hinweis auf diesen Branch gäbe!
