### ISSUE TITLE
Falsche effektive Sudhausausbeute bei Verwendung von Hefestarter

### ISSUE THREAD

**Issue by Alcoinus** [kleiner-brauhelfer/kleiner-brauhelfer-2#294]
Hi,
wenn ich einen Hefestarter ins Rezept aufnehme, passt die Berechnung der effektiven Sudhausausbeute scheinbar nicht mehr. Gebe ich im Reiter _Braudaten_ unter _Anstellmenge_ und _Stammwürze beim Anstellen_ die Werte aus dem Rezept ein, kommt eine höhere effektive Sudhausausbeute raus, als im Rezept.

Ich vermute, dass in folgender Zeile noch der SW Anteil des Starters abgezogen werden muss:
https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/blob/058998848feb79f09c7e66516601c249c5f77859/kleiner-brauhelfer-core/modelsud.cpp#L840

Aber sollte die gesamte Berechnung der Sudhausausbeute und die Berücksichtigung der Anteile nicht eher auf dem tatsächlichen Extraktgewicht anstatt dem Stammwürzebetrag basieren? Angenommen bei einem Maischvorgang war die Ausbeute genau wie erwartet, beim Kochen ist aber bspw. mehr verdampft. Solange keine weitere Zutat oder ein Starter dazu kommt, passt alles. Aber wenn eine weitere Zutat mit der vorher berechneten Menge vor dem Kochende hinzugefügt wird (während also noch nicht klar ist, dass mehr verdampft), trägt diese jetzt einen größeren Stammwürzebetrag bei, als im Rezept, da weniger Volumen vorhanden ist. Dies ist bei der jetzigen Berechnung aber nicht berücksichtigt. Die (effektive) Sudhausausbeute sollte weiterhin dem Wert aus dem Rezept entsprechen, da der erwartete Anteil an Extrakt extrahiert wurde.

Weiterhin sollten _Stammwürze beim Anstellen_ und _Anstellmenge_ meiner Auffassung nach vor der Hinzugabe des Starters sein, da dieser ja schon teilweise vergoren ist und daher die Stammwürze weiter runterzieht, als erwartet. Alternativ könnte eine zusätzliche Eingabe der aktuellen Stammwürze des Starters hinzugezogen werden.

**Comment by Rasinari** [comment]
Das ist meines Erachtens alles korrekt. Der Starter verdampft ja nicht.

Ferner wird zwischen Sudhausausbeute und effektiver Sudhausbeute getrennt. Der Starter gehört zur effektiven Sudhausausbeute und nicht wie Du schreibst zur Sudhausausbeute. Und das ist korrekt so

Frage: Hast Du mit Startern in der Praxis schon gearbeitet?

**Comment by Alcoinus** [comment]
Ich glaube, da ist etwas ein bisschen durcheinander gekommen. Mir geht es primär um die Berechnung der **effektiven** Sudhausausbeute, wenn ein Starter verwendet wird.

- Rezept
  - Menge: 20l
  - Stammwürze: 12°P
  - Sudhausausbeute: **70%**
  - Hefestarter nicht vorhanden
- Braudaten
  - Anstellmenge: 20l
  - Stammwürze beim Anstellen: 12°P
  - **Effektive** Sudhausausbeute: **70%**

Passt!

- Rezept
  - Menge: 20l
  - Stammwürze: 12°P
  - Sudhausausbeute: **70%**
  - Hefestarter: 1l mit 10°P
- Braudaten
  - Anstellmenge: 20l
  - Stammwürze beim Anstellen: 12°P
  - **Effektive** Sudhausausbeute: **73,2%**

Passt nicht!

Im Helptext zur _Stammwürze beim Anstellen_ steht, dass **nach** der Zugabe des Hefestarters gemessen wird (folglich nehme ich gleiches für _Anstellmenge_ an). Gebe ich stattdessen die Werte **vor** der Zugabe des Hefestarters an (19l mit ~12,1°P), kommt die erwartete effektive Sudhausausbeute von 70% raus. Dann wird im Reiter _Abfülldaten_ aber auch mit 19l und 12,1°P gerechnet. Hier gibt es also eine Diskrepanz.

Sehe ich das so richtig?

In meinen Augen wäre es hier sinnvoll, die Messwerte **vor** Zugabe zu verwenden und mit den geplanten Werten des Starters zu verrechnen, sodass für die Berechnung der Gärung wieder die korrekten 20L mit 12°P verwendet werden.

Würden die Messwerte **nach** Zugabe verwendet werden, ergibt sich meiner Auffassung nach ein neues Problem: der Starter ist im Moment der Zugabe schon teilweise vergoren und hat nicht mehr die ursprünglichen 10°P. Daher messe ich zwangsläufig weniger als 12°P nach der Zugabe, woraus fälschlicherweise eine niedrigere effektive Sudhausausbeute berechnet werden würde. Zudem müsste noch für den bereits entstandenen Alkohol mit geringerer Dichte kompensiert werden.

---------

Nun zu meinem zweiten Punkt: als ich zum oben genannten Problem die Berechnung nachvollzogen habe, ist mir aufgefallen, dass die einzelnen Komponenten (Malz, Zusätze, Hefestarter) anhand ihres **geplanten** Wert der Stammwürze verrechnet werden. Es geht mir jetzt nicht länger speziell um den Hefestarter, sondern allgemein die Berechnung.

Bei der Berechnung der Sudhausausbeute und der effektiven Sudhausausbeute wird von der gemessenen Stammwürze der geplante Wert der weiteren Zutaten abgezogen. Wenn jetzt aber beim Kochen beispielsweise mehr verdampft, als geplant, kommt es zu Diskrepanzen, da sich das Extrakt der Zutaten auf ein kleineres Volumen verteilt und diese somit effektiv einen größeren Stammwürzewert haben. Die Berechnungen der Sudhausausbeuten korrigieren hier aber nur für den Malzanteil, weshalb die Ausbeute zu groß berechnet wird:

- Rezept
  - Menge: 20l
  - Stammwürze: 12°P -> Extrakt: 1.04838 * 12 g/100ml = 12,58056 g/100ml -> 2516,112g
  - Sudhausausbeute: **70%**
  - Zugabe von Zucker beim Kochen:
    - 200g -> 1 g/100ml (= 1°P laut Anzeige*)
- Braudaten (ohne Verluste zwischen Kochende und Anstellen)
  - Würzemenge vor Hopfenseihen und Anstellmenge: 18l (es ist mehr verdampft beim Kochen)
  - Stammwürze bei Kochende und beim Anstellen: 13,26°P (entspricht 2516,112g Extrakt auf 18l = 139,784 g/l ~ 1,0537 * 13,26 g/100ml)
  - Sudhausausbeute und effektive Sudhausausbeute: **70,2%** (bei 13,2°P) bzw. **70,8%** (bei 13,3°P)

In meinen Augen müssten beide Werte der Sudhausausbeute dem geplanten Wert entsprechen, da genau die geplante Menge Extrakt gewonnen wurde.

Ich kann meinen zweiten Punkt gerne in ein separates issue überführen, um das tracking einfacher zu gestalten.

\* hier gibt es noch ein weiteres Problem: Die Stammwürze ist keine lineare Funktion von der volumenbezogenen Extraktmasse. Gebe ich in eine 0°P und in eine 10°P Flüssigkeit gleichen Volumens die gleiche Masse Extrakt hinzu, steigt der Platowert nicht um den gleichen absoluten Betrag

**Comment by Rasinari** [comment]
Nein, siehst Du nicht richtig. 
Passende Links habe ich gesendet.
