### ISSUE TITLE
Anstellen  -  Anordnung der Felder praxisnäher

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#295]
Die derzeitige Anordnung der Felder im Kapitel Anstellen, Reiter Braudaten, ist nicht praxisnah. Man muss mit einem Hefestarter und Verdünnung bis zur Anstellemenge immer jonglieren, bis es passt und dabei unentwegt korrigieren. Dabei bleibt die geniale Schritt-für-Schritt-Abfolge des Kleinen Brauhelfers v2 auf der Strecke.

Ich schlage folgende Abfolge vor, die nach dem Hopfenseihen Schritt für Schritt abgearbeitet werden kann:

1. Würzemenge nach dem Hopfenseihen
2. Hefestarter
3. Wassermenge für Verdünnung
4. Anstellmenge

Dies hat den Vorteil, dass die Wassermenge für Verdünnung als Korrekturfaktor genutzt werden kann.

**Comment by BourgeoisLab** [comment]
Erledigt mit v2.6.
