### ISSUE TITLE
Alle Rezepte weg nach Datenbankupdate

### ISSUE THREAD

**Issue by Knochi** [kleiner-brauhelfer/kleiner-brauhelfer-2#300]
Habe ein update von Version 2.4.0 auf 2.5.0 gemacht. Dann die Frage für das Datenbankupdate bejaht.
Alle Rezepte sind weg, Rohstoffe sind noch da, die Datenbak hat auch noch die gleiche Größe.
hier die Datenbank vor (Backup) und nach dem Update
[KBH_DatenbankKnochi.zip](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/11363958/KBH_DatenbankKnochi.zip)

**Comment by BourgeoisLab** [comment]
Siehe:
https://kleiner-brauhelfer.de/docs/faq/#gerade-sind-alle-sude-verschwunden
