### ISSUE TITLE
Absturz bei Sudauswahl (bisher ungebraute Rezepte) bei v2.5.0 (Debian bookworm)

### ISSUE THREAD

**Issue by orlo11** [kleiner-brauhelfer/kleiner-brauhelfer-2#301]
Hallo,
nach dem Umstieg auf Version 2.5.0 stürzt der KBH immer ab, wenn ich ein noch nicht gebrautes Rezept (zB Import aus MMuM) in der Sudauswahl oder in der Datenbank aufrufen will -- diese haben alle Sudnummer 0.  Bereits gebraute Sude lassen sich öffnen.
Und: Ja, ich habe die Datenbank bereinigt, wie in den FAQ steht, jetzt werden keine Fehler mehr angezeigt, aber es hat nicht geholfen.
Ich benutze KBH unter Debian bookworm/sid.
Die Konsole liefert:
`kleiner-brauhelfer-2: symbol lookup error: kleiner-brauhelfer-2: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version Qt_5`
Viele Grüße,
orlo11.

**Comment by Rasinari** [comment]
Welches System? Importierst Du im MMuM-Format? Mir sind keine Probleme mit MMuM-Import bekannt.

**Comment by orlo11** [comment]
Ich habe heute mal alles , was per apt zu qt6 greifbar war nachinstalliert und aktualisiert -- hat nichts gebracht.
Ich kann einmal gebraute Sude öffnen, kann auch händisch neue anlegen. Aber bereits angelegte, die aber noch nicht gebraut wurden, lassen sich nicht laden. Auch wenn ich der Datenbank "blättere" (Menü Ansicht > Datenbank) kann ich alle bereits gebrauten Sude durchgehen, sobald ich zu einem noch nicht gebrauten Rezept komme stürzt KBH ab. Allerdings ist selbst in Debian sid (unstable) nur QT 6.4.2, 6.5 gibts in den Repos noch nicht. Wäre schön, wenn dazu Abhängigkeiten definiert wären... 
Wenn ich die Diskussion zu QT6 lese, so werde ich wohl das AppImage nutzen müssen (<maulen> Das ist ja wie bei Windows </maulen> ;-) - eigentlich ein eklatanter Widerspruch zu Paket-Management...
Ich probiere mal. Wenns klappt, dann schließe ich diesen Issue.

**Comment by orlo11** [comment]
Sooo,
wer sowas nicht spät abends macht, ist klar im Vorteil -- oder so.
Ich habe übersehen, dass es auch eine Version für QT 5.13.3 gibt, die natürlich auch mit 5.15.8 funktioniert

*schäm*

ich schließe den issue.
Schöne Pfingsten,
orlo11.
