### ISSUE TITLE
"Sud Teilen" nicht mehr möglich

### ISSUE THREAD

**Issue by BurtMC** [kleiner-brauhelfer/kleiner-brauhelfer-2#305]
In der aktuellen Version (2.6) habe ich festgestellt, dass es die Funktion "Sud teilen" nicht mehr gibt.

Besteht die Möglichkeit dies wieder zu integrieren? 

Ziel soll es sein die einzelnen Teilsude bzgl. Gärverlauf, CO2-Gehalt und Zutaten zu tracken. So ließen sich dann Experimente mit z.B. unterschiedlichen Hefen besser nachverfolgen.

**Comment by Rasinari** [comment]
Welches BS, welcher Reiter? Die Funktion heißt jetzt "Teilen" und findet sich im Reiter Sudauswahl.

**Comment by BurtMC** [comment]
Genau das habe ich gesucht. Früher war der Button unter Braudaten.
