### ISSUE TITLE
Maischeplan wird im Spickzettel nicht ausgegeben

### ISSUE THREAD

**Issue by markussoeth** [kleiner-brauhelfer/kleiner-brauhelfer-2#306]
In der Datei
kleiner-brauhelfer/data/Webview/spickzettel.html 

Scheinbar wird der Marker {#Rasten}[...]{/Rasten} in der Zeile 365 bis 397 nicht interpretiert.

Ich hatte mal versucht den durch den Marker {#Maischeplan}[...]{/Maischeplan} aus der Datei kleiner-brauhelfer/data/Webview/zusammenfassung.html zu ersetzen. Dann wird zumindest der Einmaisch Marker ({{#Einmaischen}}) ausgeführt, aber nicht mehr der Marker {{#Rast}}. Dann bin ich nicht weitergekommen.

**Comment by BourgeoisLab** [comment]
Die Datei im Repo sollte funktionieren 
https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/blob/master/kleiner-brauhelfer/data/Webview/spickzettel.html

Wahrscheinlich wurde beim Update die Datei bei dir nicht überschrieben.

**Comment by markussoeth** [comment]
Ach danke. Hat funktioniert. Wahrscheinlich, wurde die beim Update nicht überschrieben, weil ich da mal eine kleine Änderung drin gemacht hatte. Windows eben ;-)
