### ISSUE TITLE
Bitte AppImage nicht in ein Archiv einpacken

### ISSUE THREAD

**Issue by probonopd** [kleiner-brauhelfer/kleiner-brauhelfer-2#31]
Bitte das AppImage nicht in ein Archiv einpacken, die Gründe sind auf https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake erläutert. Danke!

**Comment by BourgeoisLab** [comment]
Die AppImage wurde in ein Archiv gepackt, damit der Ordner "kleiner-brauhelfer-2-x86_64.AppImage.config" vorhanden ist. Ist dieser Ordner vorhanden, werden alle Einstellungen und Daten dort gespeichert. Dadurch ergibt sich erst eine portable Version. Ist der Ordner nicht vorhanden, werden die Daten unter "[home]/.config/kleiner-brauhelfer/..." gespeichert. Das ist meiner Meinung nach keine portable Anwendung.

Hast du eine Idee wie man das anders lösen könnte, ohne vom User grosse Linux/AppImage Kenntnisse vorauszusetzen?

**Comment by probonopd** [comment]
Eine kleine Anpassung in `AppRun` sollte das erledigen:

```
#!/bin/bash

HERE="$(dirname "$(readlink -f "${0}")")"
if [ ! -z "$APPIMAGE" ] ; then
  mkdir -p "$APPIMAGE.config"
  export XDG_CONFIG_HOME="$APPIMAGE.config"
fi

exec $HERE/usr/bin/kleiner-brauhelfer-2
```

**Comment by BourgeoisLab** [comment]
Super. Habe den check jetzt so gemacht:
`if [ ! -d "$APPIMAGE.config" ] ; then`
