### ISSUE TITLE
Automatisch speichern und Beenden

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#313]
Der Kleine Brauhelfer 2 verhindert das automatische Abmelden auf Mac.

Vorschlag: Automatisches Speichern in Einstellungen einbauen, mit dem die Aufforderung zum Sichern abgeschaltet wird.

<img width="467" alt="Abemelden" src="https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/assets/51321250/9e76e072-5386-4c60-8161-295b74d383ea">

**Comment by BourgeoisLab** [comment]
Duplicate #168
