### ISSUE TITLE
Reiter Ausrüstung Enter legt neue Brauanlage an

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#316]
Bei Klick in eines der Eingabefelder rechts und Enter wird eine neue Brauanlage angelegt. Bei mehreren Änderungen hat man dann jede Menge neue Brauanlagen.

**Comment by BourgeoisLab** [comment]
Erledigt mit 8b6f0f2a8d05d8f98578dd795ee41866fd5f321e.
