### ISSUE TITLE
Absturz nach jedem schlissen

### ISSUE THREAD

**Issue by Aluhut** [kleiner-brauhelfer/kleiner-brauhelfer-2#318]
Nahezu nach jedem schliessen, kommt der Dialog der fragt ob die App wieder neu geöffnet werden soll.
(Jetzt natürlich ausgerechnet nicht)

MacBook Pro 
Mac OS Sonoma
KB 2.6.1

Ich werde hier zukünftig alle Bugs posten die ich finde, sofern euch das hilft!?
Es sind leider eine Menge, weswegen das nervig werden könnte.

**Comment by BourgeoisLab** [comment]
Ohne Fehlerberichte können die Entwickler gar nicht wissen, welche Bugs es überhaupt gibt. Also ruhig posten.
Aber bitte die Fehler detailliert Beschreiben. Mit der obigen Beschreibung kann ich eher wenig anfangen. Screenshot vom Dialog? Mit welchen Schritte kann man es reproduzieren? Seit welcher Version? Gut hast du das OS und die Version angegeben.

**Comment by Rasinari** [comment]
Ich wollte Dir diesen Patz schon unter Hobbybrauer.de empfehlen, aber Du hast ihn selber gefunden. Die Bugs sind auf Mac bekannt. Unter Monterey ist auch Schließen das Problem, es scheint sich mit Sonoma verstärkt zu haben.

Bitte bei jedem Absturz die Schritte bis zum Absturz ganz genau beschreiben. Auch die ersten Zeilen des Crash-Dialogs nach dem Absturz (schwarzes Fenster, an Apple senden) helfen.

Mir scheint es, das Schließen einen generellen Laufzeitfehler produziert.

**Comment by Aluhut** [comment]
Ok, ich konnte es reproduzieren.
Ich habe in "Rohstoffe" die Mengen meines Hopfen und Malz angepasst und auch einen Eintrag gelöscht. Also ich dann das extra Fenster von "Rohstoffe" schloss, stürzte die komplette App ab.
Anbei der Absturzbericht.
Falls ich noch irgendwie anders unterstützen kann, lasst es mich gerne wissen!

Viele Grüße und Danke im Voraus!
[crash.txt](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/13646378/crash.txt)

**Comment by BourgeoisLab** [comment]
Wenn es gut kommt, haben alle Abstürze den gleichen Grund. Den Fix gab es kürzlich. Vielleicht mag jemand diese Testversion testen:
https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/actions/runs/6988558571

**Comment by Aluhut** [comment]
> Vielleicht mag jemand diese Testversion testen
Eben gerade installiert, wieder den Ablauf wie oben beschrieben und alles funktionierte. Sieht bisher gut aus! Vielen lieben Dank! 

Ich habe Probleme zwischen der iOS App und der MacOS App die Reszepte in sync zu halten. Dafür hier einen neuen Issue aufmachen oder wie läuft das?

**Comment by BourgeoisLab** [comment]
> Ich habe Probleme zwischen der iOS App und der MacOS App die Reszepte in sync zu halten. Dafür hier einen neuen Issue aufmachen oder wie läuft das?

Nein. Die iOS App wird nicht von den gleichen Leuten entwickelt, wie der KBH. Soviel ich weiss, wird die App auch nicht weiterentwickelt und die Inkompatibilität mit dem KBH wächst.

**Comment by Rasinari** [comment]
> > Vielleicht mag jemand diese Testversion testen
> > Eben gerade installiert, wieder den Ablauf wie oben beschrieben und alles funktionierte. Sieht bisher gut aus! Vielen lieben Dank!
> 
> Ich habe Probleme zwischen der iOS App und der MacOS App die Reszepte in sync zu halten. Dafür hier einen neuen Issue aufmachen oder wie läuft das?

Das wurde kürzlich mehrfach auf Hobbybrauer.de erklärt: KBH iOS ist etwas anderes als der Original kleiner-brauheller-2.

Die iOS app hat zwar den gleichen Namen, dahinter steht aber ein anderer Entwickler, der nicht Willens ist, die iOS.app an das Original anzupassen. Die Namensgleichheit ist etwas unglücklich und führt zu permanenten Missverständnissen.

**Comment by Rasinari** [comment]
> Wenn es gut kommt, haben alle Abstürze den gleichen Grund. Den Fix gab es kürzlich. Vielleicht mag jemand diese Testversion testen: https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/actions/runs/6988558571

Funktioniert alles ohne Abstürze. Getestet mit Rohstoffe, Zusätze und Ausrüstung.

Danke für die Mühen. Großartig!
