### ISSUE TITLE
Keine Dezimalstellen bei Zuckergabe pro Flasche

### ISSUE THREAD

**Issue by planbnet** [kleiner-brauhelfer/kleiner-brauhelfer-2#32]
Bei der benötigten Zuckergabe pro Flasche in den Abfülldaten werden keine Dezimalstellen angezeigt. Das ist für eine sinnvolle Dosierung zu ungenau.

**Comment by BourgeoisLab** [comment]
Erledigt mit commit fa04868.
Danke.
