### ISSUE TITLE
Reiter Ausstattung: Ungewollte neue Brauanlagen

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#320]
Ein Klick auf das Feld Korrektur der Sollmenge legt ungewollt eine neue Brauanlage an.
Dies passiert nicht, wenn die Pfeiltasten zum Ändern des Wertes genutzt werden.

**Comment by realholgi** [comment]
Ich kann das nicht reproduzieren. Bitte beschreibe genau, was du gemacht hast und die Version.

**Comment by Rasinari** [comment]
In v2.6.2 tritt es nicht mehr auf, somit kann ich es nicht mer reproduzieren.

**Comment by Rasinari** [comment]
Nicht reproudzierbar.
