### ISSUE TITLE
Hauptgussfaktor

### ISSUE THREAD

**Issue by bigtreeteche3** [kleiner-brauhelfer/kleiner-brauhelfer-2#325]
Seit einiger Zeit scheint das Feld Hauptgussfaktor verschwunden zu sein

**Comment by BourgeoisLab** [comment]
Das ist nur für Grainfatheranlagen der Fall. Dort wird der Faktor gemäss Benutzerhandbuch automatisch gesetzt.
Für Standardanlagen gibt es weiterhin das Feld.
