### ISSUE TITLE
Unvollständiger Export Maischplan bei gemischten Maischverfahren

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#326]
Wie ein User auf hobbybrauer.de berichtet, wird bei gemischter Wahl von Dekoktion und Infusion beim Export nur die Dekoktion exportiert, die Infusionsrasten werden nicht übernommen.
Löscht man die Rast mit Dekoktion, werden alls Infusionsrasten ordentlich exportiert.
Dieser Bug sollte doch leicht zu beheben sein…

Vielleicht kann man für den User eine vorläufige Version per Action machen?

**Comment by BourgeoisLab** [comment]
Welches Format MMuM? Entscheidend ist, ob das MMuM Format das erlaubt.

**Comment by Rasinari** [comment]
Dazu kann ich nichts sagen, da der User sich nicht die Mühe mit Details gemacht hat. Schließen wir das hier.
