### ISSUE TITLE
Zusätzliche Tags für den Spickzettel

### ISSUE THREAD

**Issue by weedinator** [kleiner-brauhelfer/kleiner-brauhelfer-2#328]
Wäre es möglich für die verwendeten Zutaten die Tags "Bemerkung" hinzuzufügen?

Hintergrund: Ich gebe im Feld "Bemerkung" bei den Rohstoffen die Chargennummer ein und hätte diese auch gerne im ausgedruckten Spickzettel für die Rückverfolgbarkeit.

Vielen Dank für die supergute Software!

**Comment by weedinator** [comment]
Hi Rasinari,
also die html Vorlagen habe ich schon nach meinen Wünschen angepasst. Allerdings finde ich die benötigten Tags nicht auf der rechten Seite, welche ich benötige. Ich hätte jetzt vermutet, dass die Tags direkt im Programmcode (C++ ?) definiert werden, oder? Und da komme ich selber nicht weiter, da ich nicht programmieren kann.
Deswegen meine Bitte, die Tags anzulegen. Oder habe ich da etwas übersehen bzw. falsch verstanden?
Beste Grüße
Philip

**Comment by Rasinari** [comment]
Hallo Philipp, die Tags werden weniger kompliziert angelegt. Du müsstest den Aufruf für Bemerkungen herausfinden, dann kannst Du das selber in der Vorlage defineiren.
Der KBH wird grundlegend neu designt, daher werden aktuell keine neuen Funktionen eingebaut, zumal solche mit niedriger Priorität, die wenig Interesse anderer Nutzer nahelegen. Bitte um Verständnis und etwas Geduld. Vielleicht findest Du ja selbst einen Weg. Lade Dir doch mal die Quelldateien runter.

**Comment by BourgeoisLab** [comment]
Diese Tags werden für den Spickzettel nicht angeboten. Ich möchte es auch nicht hinzufügen, weil dann der Nächste kommt und wünscht sich z.B. das Haltbarkeitsdatum, der Nächste dann die Eigenschaften, usw...

Für das Redesign ist die Überlegung für jede Malz-, Hopfen-,  Hefegabe ein Bemerkungsfeld hinzuzufügen. Momentan gibt es das nur für die Zusätze. Diese wären dann im Spickzettel verfügbar.

**Comment by weedinator** [comment]
Hi BourgeoisLab,
danke für die Antwort.
Schade, aber ich kann die Entscheidung verstehen.
Dann muss ich die Chargennummer eben in den Namen schreiben.

Vielleicht gibt es im Redesign ja irgendwann doch mehr Tags...

Danke aber auf jeden Fall für die supergute Software!

Cheers
