### ISSUE TITLE
Rounding error: Set °dH (German hardness) to 1/100 

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#34]
If the data (calcium hardness etc.) in °dH (German hardness) are compared with the analyses of the water suppliers, rounding errors result. Calcium, magnesium or carbonate hardness is given by utilities 2 digits after the decimal point. In KBH it is only one digit. In practice, the rounding error means up to 1° dH difference in the end.

Like mmol/l, °dh should be set to 2 decimal places.

**Comment by BourgeoisLab** [comment]
Done with commit c1e07d2.
