### ISSUE TITLE
Rohstoffsortierung failt

### ISSUE THREAD

**Issue by ivh** [kleiner-brauhelfer/kleiner-brauhelfer-2#35]
![rohsort](https://user-images.githubusercontent.com/134957/66546725-ea6c2880-eb3d-11e9-95d3-b9c1282c010f.png)

Die 0.43g CaraFa im Screenshot werden falsch eingeordnet, auch bei mehrmaligem Klicken auf die Sortierung. Aktuelle Version aus master.

Gruß & danke!
thomas

**Comment by ivh** [comment]
Frage nebenbei: Was bedeutet eigentlich, wenn ein Rohstoffname kursiv dargestellt wird?

**Comment by BourgeoisLab** [comment]
Kursiv heisst: wird in einem nicht-gebrauten Sud verwendet (-> in Gebrauch) und darf nicht gelöscht werden.

**Comment by BourgeoisLab** [comment]
Die sauberste Lösung erfordert eine Änderung der Datenbankstruktur. (Alle Typen NUMERIC auf REAL ändern.)
Ich will damit aber liebe abwarten, damit nicht zuviel verschiedene Datenbankversionen im Umlauf sind.

**Comment by ivh** [comment]
Ok danke, keine Eile, und ist ja auch nicht so wichtig.

SQlite kann keine NUMERIC sortieren? ;)

**Comment by BourgeoisLab** [comment]
Bei NUMERIC macht er aus 0.0 ein integer und aus 0.3 ein double. Und das bringt Qt bei der Sortierng scheinbar durcheinander. Ist mir nicht ganz klar wieso...
Bei REAL wird aus 0.0 korrekterweise ein double.

**Comment by BourgeoisLab** [comment]
Erledigt mit 5f5ea38fb9d70e877db92ca656c5421cf16a7b62.
