### ISSUE TITLE
Kosten

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#36]
Die Bezeichnung der Kostenstellen ist im Programm uneinheitlich und nicht nachvollziehbar.

• Im Tab Braudaten
ist von Nebenkosten und Kosten die Rede. Nebenkosten und Kosten lassen sich definieren
• Im Tab Abfülldaten
ist von Nebenkosten und Kosten die Rede. Nebenkosten lassen sich definieren, Kosten nicht.
Nebenkosten werden dabei vom Tag Braudaten übernommen.
• Im Tab Ausrüstung
ist von Kosten (Gas, Wasser, Strom etc.) die Rede. Kosten (Gas, Wasser, Strom etc.) lassen sich definieren. Es ist aber unklar, was wo übernommen wird.

**Betriebswirtschaftlich ist die Benennung falsch!**

Gas, Wasser, Strom sind Betriebskosten. Darunter versteht man unveränderlich Kosten. Dazu gehört auch Miete, Abschreibung von Ausrüstung 
Nebenkosten gibt es in der Taxonomie streng genommen nicht. Streng genommen sind Nebenkosten Betriebskosten.
Die Hauptkosten sind die Sudkosten oder die Materialkosten. (Weil es unter Hobbybrauern keine Personalkosten gibt.) Darunter versteht man die singuläre Kosten pro Rezept, also Malz Hopfen, Hefe, Zutaten.
Daraus ergeben sich die Gesamtkosten. das gehört nach rechts

**Der Begriff Kosten ist somit missverständlich.**

Warum die Kosten im Tab Braudaten eingegeben werden können, im Tab Abfülldaten nicht, bleibt mir ein Rätsel.

In den Tooltips habe ich alles mal abgeändert (und auch die Feldbezeichnungen (!!!) in Sudkosten, Betriebskosten, Gesamtkosten.
Ich meine, da sollte man nochmal ran...

**Comment by BourgeoisLab** [comment]
Die Nebenkosten in den Tabs Braudaten & Abfülldaten sind gleich, ja. Die Felder werden synchronisiert.

Das Feld "Kosten" im Tab Braudaten sollte sich nicht einstellen lassen (ist zumindest bei mir so). Auch dieses Feld wird mit dem entsprechenden Feld in Abfülldaten synchronisiert.

Das ist die Berechnung:
`GesammtKosten/Liter = (Rohsfoffkosten + Nebenkosten + KostenAusAusrüstung) / Menge`

Die Bezeichnungen sind zuzeit nicht klar und ich mekre, dass die Berechnung nicht immer korrekt ausgeführt wird. Wird korrigiert...

**Comment by BourgeoisLab** [comment]
done 44a907cb5009b22a5bd3d80ce840bd18ba8d3d85.

**Comment by Rasinari** [comment]
Perfekt. Mit Dank.
Schau noch mal Tippfehle - falls an anderer Stelle Probleme auftauchen:GesammtKosten/Liter = (Rohsfoffkosten + Nebenkosten + KostenAusAusrüstung) / Menge

Gesamtkosten
Rohstoffkosten
