### ISSUE TITLE
macOS 10.15 Catalina KBH2

### ISSUE THREAD

**Issue by realholgi** [kleiner-brauhelfer/kleiner-brauhelfer-2#37]
Um in der aktuellen macOS 10.15 Version den leinen Brauhelfer 2 überhaupt starten zu können, muss über das Treminal zuerst das Quarantäne-Attribut gelöscht werden, da die App bisher (noch) nicht notarized ist:

`xattr -dr com.apple.quarantine kleiner-brauhelfer-2.app`

**Comment by Rasinari** [comment]
> Um in der aktuellen macOS 10.15 Version den leinen Brauhelfer 2 überhaupt starten zu können, muss über das Treminal zuerst das Quarantäne-Attribut gelöscht werden, da die App bisher (noch) nicht notarized ist:
> 
> `xattr -dr com.apple.quarantine kleiner-brauhelfer-2.app`

Es geht auch so - ohne die Quarantäne für den KBH ganz auszuschalten:
`sudo spctl --master-disable`
dann in Sicherheit -> Allgemein -> Dennoch öffnen
und Gatekeeper wieder einschalten
`sudo spctl --master-enable`

**Comment by realholgi** [comment]
Inzwischen hhabe ich herausgefunden, kann man auch ohne Kommandozeile auskommen:

1. Zuerst mit Rechts(Ctrl)-Klick auf dem Programm-Icon "Öffnen" und "Abbrechen".
2. Nochmal Rechts(Ctrl)-Klick auf dem Programm-Icon "Öffnen" und "Öffnen" startet dann den kbh2.
3. Nach dieser Prozedur kann das Programm wie immer dopplet geklickt werden. Puuh.

**Comment by BourgeoisLab** [comment]
Macht es Sinn das in der readme Datei zu schreiben? Wenn die issue geschlossen ist, ist es schwierig es wieder zu finden.

**Comment by Rasinari** [comment]
Diese Prozedur ist auch deutlich sicherer als Gatekeeper (spctl) ausschalten und wird von Apple selbst empfohlen. Sollte in den Beipackzettel aufgenommen werden. Abbrechen ist nicht nötig.

Frage: Lässt sich etwas an den Widget-Fenstern bei Retina-Displays machen? Diese sind zu klein, Inhalt wird nicht korrekt dargestellt. Aufziehen löst das Problem, danach beginnt es aber wieder von vorne.

**Comment by realholgi** [comment]
Das ist interessanterweise ein "Standard-Feature", das allerdings erst nach Veröffentlichung von Catalina bekannt wurde. Hmm. Jetzt sicherlich interessant, in 2 Monaten wissen das Ann alle Mac-User.

**Comment by Rasinari** [comment]
stimmt. Warum erst jetzt, wo man mit sudo spctl seit 2017 herumwerkelt ist unergründbar. Apple eben.

**Comment by BourgeoisLab** [comment]
Alles klar. Wenn es selbstverständlich wird, dann macht es keinen Sinn. Danke.

**Comment by Rasinari** [comment]
Sehe ich anders. Das macht IMHO Sinn. Viele Mac-User sind reine Anwender und technisch weniger versiert als Windows-Nutzer, weil man sich um Updates, Treiber etc. nicht kümmern muss.

**Comment by realholgi** [comment]
https://support.apple.com/de-de/guide/mac-help/mh40616/mac
