### ISSUE TITLE
Milchsäure, pH-Wert, Aufsalzung, Warnungen

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#38]
Die jetzige - alleinige - Milchsäureangabe macht ohne korrespondierenden pH-Wert keinen Sinn.
Obendrein birgt die Fokussierung allein auf Milchsäure die Gefahr von Geschmacksbeeinträchtigungen. 
Der Wert ist der Literatur nach 400 ppm.

• Der Wert ppm fehlt
• Der Wert pH fehlt

Nach Braumagazin https://braumagazin.de/article/von-der-wasseranalyse-zum-brauwasser/
soll ein Wert von 100 ppm nicht überschritten werden, da Malz selber eigene Milchsäure einträgt.

Der Milchsäureanteil wird gewöhnlich durch Aufsalzen mit Calciumsulfat oder Calciumchlorid abgesenkt oder durch Einsatz anderer Säuren. Üblich ist eine Kombination aller Stoffe. Üblich sind Salz- und Phosphorsäure. Phosphorsäure hat den Vorteil kaum geschmacksbeeinflussend zu sein.

• Die Angabe CaSO4 fehlt
• Die Angabe CaCl fehlt
• Die Angabe Bittersalz/Natriumdisulfit/Magnesiumchlorid fehlt
• Die Angabe Salzsäure fehlt
• Die Angabe Phosphorsäure fehlt

(Schwefelsäure ist nicht aufgeführt, da privat nicht erhältlich.)

Überschlägig habe ich gerade die KBH-Empfehlung bei einem 19l Sud Pale Ale durchgerechnet und komme auf 350ppm mit Nachguss. Too much.

Mein Vorschlag: Milchsäuregabe mit ppm und pH auszeichnen. Berechnet sich ausgehend von Malz und Wasseranalyse. Komplizierter wird es mit Verschnittwasser und anderen Säuren, die mit unterschiedlichen Konzentrationen auf dem Markt sind.
Wichtig ist der Hinweis, dass es sich bei Säuren und Salzen um lebensmitteltaugliche Qualität nach EU-Norm (E-Nummer) handeln muss.

• 2 Säureangaben ermöglichen
• Verdünnungsgrad/Konzentrationswert angeben.

Bei Überschreiten empfohlener Dosierungen Feld rot hinterlegen. Dies gilt für
• Milchsäure
• Calcium
• Chlorid
• Sulfat
• pH-Bereich unter 5,2 oder über 5,8, bzw. 5,3 oder 5,7 (Messtoleranz)
(• Natriumdisulfit)

Ohne Verschnitt/Osmose/Destilliertes reicht die Angabe der Wasseranalyse (da selbst ist auch noch Luft nach oben – anderes Ticket).

**Comment by BourgeoisLab** [comment]
Berechnungen:
https://www.maischemalzundmehr.de/index.php?inhaltmitte=toolswasserrechner

**Comment by Rasinari** [comment]
… mit dem Wasserrechner von MMuM bin ich auch eingestiegen. Die Vorbehandlung mit CaO kann man sich schenken.
Wichtiger sind Tools, die eine verspätete Gabe von Röst-/Karamellmalzen einrechnen, ob Salze für den Nachguss gleich zur Maische kommen. Dies beeinflusst den pH viel mehr.
Ganz wichtig ist die feine Berechnung der Malzsorten für den pH und auch das Ca/SO4-Verhältnis

Wie gesagt: Ich stelle mich hier gerne zur Verfügung, möchte aber vorher wissen, welcher Umfang geplant ist.
Um zielgenau planen zu können, wäre vorab eine kleine Sammlung von Wasseranalyse aus DE, AT und CH hilfreich, damit man den User bei seinen Werten abholen kann. Wasseranalysen unterscheiden sich enorm. Dies muss eine Umsetzung in einem Programm berücksichtigen.

**Comment by BourgeoisLab** [comment]
Danke für das Angebot. Ich habe mich mit der Thematik noch gar nicht auseinandergesetzt und brauche sicher Zeit, um mich da einzulesen. Es wird wahrscheinlich bis nach der 2.0 Release warten müssen.

Meinst du, es reicht die MMuM Berechnungen zu übernehmen, oder braucht es noch mehr?

**Comment by a5a351e7** [comment]
Bei mir ist es ähnlich, aber den Vorschlag Daten bereits zusammenzutragen finde ich sehr gut. So weit ich das jetzt überblicken kann sind folgene Ionen interessant:

- HCO3
- Ca
- Mg
- SO4
- Cl
- Na 

Ist das so weit richtig?

**Comment by Rasinari** [comment]
MuMM alleine wird nicht reichen. State of the art ist Brew‘n‘Water. Die beiden. 


Von meinem iPhone gesendet

**Comment by Rasinari** [comment]
Am 29.11.2019 um 14:09 schrieb Florian <notifications@github.com>:
> 
> ﻿
> Bei mir ist es ähnlich, aber den Vorschlag Daten bereits zusammenzutragen finde ich sehr gut. So weit ich das jetzt überblicken kann sind folgene Ionen interessant:
> 
> HCO3
> Ca
> Mg
> SO4
> Cl
> Na
> Ist das so weit richtig?
> 
Das ist soweit richtig. Aber das meine ich nicht. Wasseranalysen enthalten selten HCO3, muss man errechnen. Z.b aus der Säurekapazität bei pH 4,3. Das sind Normwerte, die jedes Wasserwerk anders handhabt. Das macht es so schwierig eine Wasseranalyse für die Restalkalität heranzuziehen. 

Wasseranalysen aus allen Himmelsrichtungen der Republik meine ich. Dann kann man beginnen zu entwickeln. 

Ist ein wirklich weites Feld.

**Comment by hkristen** [comment]
Das wäre ein 

> 
> 
> … mit dem Wasserrechner von MMuM bin ich auch eingestiegen. Die Vorbehandlung mit CaO kann man sich schenken.
> Wichtiger sind Tools, die eine verspätete Gabe von Röst-/Karamellmalzen einrechnen, ob Salze für den Nachguss gleich zur Maische kommen. Dies beeinflusst den pH viel mehr.
> Ganz wichtig ist die feine Berechnung der Malzsorten für den pH und auch das Ca/SO4-Verhältnis
> 
> Wie gesagt: Ich stelle mich hier gerne zur Verfügung, möchte aber vorher wissen, welcher Umfang geplant ist.
> Um zielgenau planen zu können, wäre vorab eine kleine Sammlung von Wasseranalysen aus DE, AT und CH hilfreich, damit man den User bei seinen Werten abholen kann. Noch komplizierter wird es bei den Profilen im angelsächsischen oder frankophonen Raum.
> Eine Gegenrechnung ist wichtig. Kationen und Anionen müssen nahezu ausgeglichen sein, sonst liegt eine Fehlberechnung vor.
> Wasseranalysen unterscheiden sich enorm. Dies muss eine Umsetzung in einem Programm berücksichtigen.

Hier eine Wasseranalyse aus AT --->> habe bereits 3 andere Wasseranalysen aus AT gesehen und alle hatten das gleiche Format:

![grafik](https://user-images.githubusercontent.com/21188501/69880883-89eea180-12cb-11ea-8a6e-fde386e38a3a.png)

--> Reicht mir leicht um mit dem MMuM Rechner das Wasser einzustellen und damit sehr gut Brauergebnisse zu erziehlen. 
Brew‘n‘Water wäre halt dann der Gold Standard ;)

**Comment by BourgeoisLab** [comment]
> --> Reicht mir leicht um mit dem MMuM Rechner das Wasser einzustellen und damit sehr gut Brauergebnisse zu erziehlen.
> Brew‘n‘Water wäre halt dann der Gold Standard ;)

Habe Brew‘n‘Water heruntergeladen und es sieht schon recht komplex aus. Was holt man da mehr aus als bei MMuM? Und ist das für den Hobbybrauer überhaupt relevant? Das man Doktorarbeiten über die Wasseranalyse schreiben kann, ist mir klar.

Kommt noch dazu, und das ist fas entscheidend, bei MMuM werden die Formeln angegeben.

**Comment by Rasinari** [comment]
> > --> Reicht mir leicht um mit dem MMuM Rechner das Wasser einzustellen und damit sehr gut Brauergebnisse zu erziehlen.
> > Brew‘n‘Water wäre halt dann der Gold Standard ;)
> 
> Habe Brew‘n‘Water heruntergeladen und es sieht schon recht komplex aus. Was holt man da mehr aus als bei MMuM? Und ist das für den Hobbybrauer überhaupt relevant? Das man Doktorarbeiten über die Wasseranalyse schreiben kann, ist mir klar.
> 
> Kommt noch dazu, und das ist fast entscheidend, bei MMuM werden die Formeln angegeben.

Die Zugabezeitpunkte sind wichtig, die Balance, Bierstile und damit pH. Bevor nicht eine Roadmap feststeht, ist Github wohl nicht der richtige Ort, um das zu diskutieren.
Schwierig an Brew'n'Water (BnW) ist nur der Einstieg und damit die  richtige Umrechnung der Wasseranalyse. Obwohl es Formeln gibt, reichen die nicht aus. Mir immer zu Hilfe ist der Cactus2000 Rechner:
https://www.cactus2000.de/de/unit/masswas.php

Eine Wasseranalyse sieht hier im Südosten Bayerns so aus (komplizierter als z.B. in Hamburg oder Österreich:
[Wasser Passau 2018.pdf](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/3906332/Wasser.Passau.2018.pdf)
Diese Werte werden in BnW folgend eingegeben:
<img width="1116" alt="Bildschirmfoto 2019-11-29 um 21 15 22" src="https://user-images.githubusercontent.com/51321250/69888676-63d9f900-12ed-11ea-8c86-8bd19295e974.png">
Schwierig ist es jetzt die Balance mit den richtigen Angaben zu finden. Mein Beispiel liegt im Optimum von 0,00. Es braucht eine Weile, bis man drauf kommt, dass die Karbonathärte der richtige Wert ist und HCO3 sich mit dieser berechnen lässt:
<img width="1129" alt="Bildschirmfoto 2019-11-29 um 21 17 22" src="https://user-images.githubusercontent.com/51321250/69888726-ab608500-12ed-11ea-9952-e4265faebb7a.png">
Unten finden sich Hilfsformeln, mit denen man die Balance anhand der der Angaben der Wasseranalyse berechnen kann. Die Gegenprobe macht man mit der Säurekapazität:
<img width="1142" alt="Bildschirmfoto 2019-11-29 um 21 19 04" src="https://user-images.githubusercontent.com/51321250/69888766-e5318b80-12ed-11ea-8309-65cb53a38a6d.png">
Ab jetzt ist es einfach. Zuerst wird der Nachguss eingestellt. Bei mir sind das in der Regel 100% Osmosewasser mit einer Leitfähigkeit 4-7. Anhand von ppm as CaCO3 lässt sich die Restalkalität berechnen; wir Deutschen brauchen dazu Cactus2000 und damit die Karbonathärte - die Gegenprobe. Die Ranges sind gut erklärt, alles andere macht BnW:
<img width="829" alt="Bildschirmfoto 2019-11-29 um 21 21 10" src="https://user-images.githubusercontent.com/51321250/69888863-66891e00-12ee-11ea-92ab-d9fd1a31c4f1.png">
Jetzt trägt man die Zutaten wie bei MuMM ein. Wichtig ist zu entscheiden, ob man Röst/Cara entnimmt/später hinzugibt. Das beeinflusst den pH massiv. Sehr praktisch bei dunklen Bieren, wenn bei weichem Wasser der pH in den Keller zu gehen droht. Hier ein Beispiel für den Wochenendsud:
<img width="1287" alt="Bildschirmfoto 2019-11-29 um 21 25 25" src="https://user-images.githubusercontent.com/51321250/69888947-d39cb380-12ee-11ea-8a24-79298ff5e21d.png">
Jetzt kommt der Hauptteil. Ich gebe das gewünschte Profil ein, die Berechnungen der Schüttung liefert der KBH. Verschnittwasser ja/nein? Actual Profile und Mashing Water Profil sind die Zielgrößen. Sie orientieren sich am gewünschten Profil (in diesem Fall absolut krass und trocken):
<img width="1774" alt="Bildschirmfoto 2019-11-29 um 21 29 28" src="https://user-images.githubusercontent.com/51321250/69889068-5aea2700-12ef-11ea-8668-2f86c1cb867b.png">
Stimmt der pH, kann man den RA vernachlässigen; das ist identisch zu MuMM, aber ausdifferenziert:
<img width="1774" alt="Bildschirmfoto 2019-11-29 um 21 29 28" src="https://user-images.githubusercontent.com/51321250/69889095-866d1180-12ef-11ea-8ec6-61331cfcf516.png">

Reichen die Salze nicht aus, kommen Säuren zum Einsatz, um den richtigen pH zu treffen. Ich verwende Phosphorsäure und Milchsäure, selten andere: 
<img width="1586" alt="Bildschirmfoto 2019-11-29 um 21 32 25" src="https://user-images.githubusercontent.com/51321250/69889172-db108c80-12ef-11ea-8706-3b85677fac81.png">

Spannend sind diese Felder. Sie entscheiden, ob der pH genau oder genauer getroffen wird - Einzelheiten führen hier zu weit:
<img width="639" alt="Bildschirmfoto 2019-11-29 um 21 33 37" src="https://user-images.githubusercontent.com/51321250/69889193-f2e81080-12ef-11ea-8ba3-009f0665059c.png">
Dann geht es zur Übersicht. Wasser aufbereiten. Fertig.
Heute ein Profil zu berechnen, dauert mit Übung und gespeicherten Vorlagen keine 5 Minuten Am längsten dauert die Eingabe der Schüttung und die Berechnung der RA mit deutscher Härte dH.

**Comment by Rasinari** [comment]
> Kommt noch dazu, und das ist fast entscheidend, bei MMuM werden die Formeln angegeben.

Ich habe hier entsperrte Sheets. Da musst Du die Formeln nur rauskopieren. Schicke ich Dir?

**Comment by BourgeoisLab** [comment]
> 
> 
> > Kommt noch dazu, und das ist fast entscheidend, bei MMuM werden die Formeln angegeben.
> 
> Ich habe hier entsperrte Sheets. Da musst Du die Formeln nur rauskopieren. Schicke ich Dir?

Bru'n Water ist lizensiert und darf nicht einfach so kopiert werden. Nur mit expliziter Erlaubnis vom Entwickler.
![Unbenannt](https://user-images.githubusercontent.com/9480307/69897888-35423980-1352-11ea-8619-6547b6c31abb.PNG)

**Comment by Rasinari** [comment]
Aber die Formeln darfst Du Dir schon anschauen? Ich diskutiere öfter mit Martin, frag ihn einfach. Ich habe hier privat meine eigene lokalisierte Version, war mir wichtig, um das Thema zu verstehen.

**Comment by hurra** [comment]
Im Forum gibt es ein tolles Excel-Sheet, an welchem man sich orientieren könnte. Das wäre mein erster Ansatzpunkt. https://hobbybrauer.de/forum/viewtopic.php?f=4&t=11831&p=374564&hilit=schlupf#p374564

Die dort verwendeten Mittel und Methoden sollten aus meiner Sicht übernommen werden.



Wasserprofile aus verschiedenen Regionen mitzuliefern halte ich für unnötig:
* Die Wasserwerte gibts meist online abzurufen und sollten für jeden mit Bedarf leicht selbst einpflegbar sein
* Die Werte können sich ändern, das wäre ein unzumutbarer Aufwand von zentraler Stelle immer die Aktualisierungen mitzuliefern

**Comment by Rasinari** [comment]
Wasserprofile für verschiedene Regionen und Bierstile ist extrem wichtig. Das ist ja der Sinn und Zweck der ganzen Wasseraufbereitung.
Schau mal bei brewersfriend die Diskussionen um  die Wasserprofile von Randy Mosher.

Wasserwerte gibt es eben nicht meist online abzurufen und wenn, dann nicht in der Ausführlichkeit wie von uns Brauern benötigt.
Dass die Werte sich ändern ist bekannt. Deswegen werden z.B. in Bru'n'Water Mittelwerte verwandt. Mache ich auch so, da sich das Wasser sommers wie winters verändert - und fahre gut damit.

Das Excel-Sheet ist schon OK, zusammen mit BnB wird es perfekt. Lade Dir mal die aktuelle Version.

**Comment by BourgeoisLab** [comment]
Mit v2.2.0beta ist ein erster Wurf für die Wasseraubereitung implementiert. Sollten weitere Wünsche ofen sein, bitte ein Neues Issue starten.

**Comment by Rasinari** [comment]
Das ist bekannt. Es sist die angepasste Version von Schlupfs Wasserrechner. Dieser Rechner ist aus unserer Erfahrung am ungenauesten. Getestet mit 6 Suden.
Di/MI setzen wir uns wegen der Formeln BnW ran. Heute Abend damit eine Genauigkeit von PH 0,01 Vorhersage.

Wasserprofile von Regionen wäre ein USP des KBH.
•Viele Rezepte/Biersteile orientieren sich an Profilempfehlungen von Randy Mosher
• bei vielen Regionen fehlt das Profil, weil es die Werte eben NICHT im Netz gibt (z.B. hier in Bayern), im Norden, Niedersachsen, Schleswig Holstein ist das dagegen vorbildlich.

Vorschlag: Grundprofile wie Pilsen, München, Düsseldorf, Dortmund sind bekannt. Mit der Zeit können dann andere Regionen hinzukommen, bzw. eine eigene Datenbank aufgebaut werden. Ich bespreche das mit oBrama.
