### ISSUE TITLE
[BUG] App crash on saving changes to a recipe or saving a new recipe

### ISSUE THREAD

**Issue by maxliemant** [kleiner-brauhelfer/kleiner-brauhelfer-2#39]
Hi,
As mentioned in the comments of #22 I have issues with the import of an .json from MMuM.
Import itself works.
On first time click of recipe I am asked to replaced unknown ingridients. So far still good. 
After replacing all unknown stuff, I want to save the recipe. Now that's the point where the app closes each time.

Find attached my database and the .json.

I tested with the new beta3.

[bug-kbh-import-mmum.zip](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/3736049/bug-kbh-import-mmum.zip)

**Comment by BourgeoisLab** [comment]
Thanks for the data. I tried now on 3 different Windows and 2 Linux machines and had no crash...

I just imported the recipe, loaded the recipe, replaced the ingredients and saved. All went well.

Can someone else reproduce the crash?

**Comment by maxliemant** [comment]
That's crazy weird.

Any chance to investigate it on my end? Maybe some logs or whatever?

See also attached this video.
[Video_20191018_200601.zip](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/3745151/Video_20191018_200601.zip)

**Comment by BourgeoisLab** [comment]
Not much you can do I guess. Can you attach the kleiner-brauhelfer-2.ini file located under C:\Users\<user>\AppData\Roaming\kleiner-brauhelfer. 

And I assume the database is not saved, right?

There is no log file at the moment. I will try to make a version with some debug messages.

**Comment by BourgeoisLab** [comment]
Saving the database in general works?

**Comment by maxliemant** [comment]
Database is not saved afterwards.
Looks like it's happening on saving with any existing recipe as well. 
_So it probably does not have anything to do with the MMuM import._

Saving any changes in the `Rohstoffe` or `Ausruestung` tabs works fine.

App crashes started with version beta2.


[kleiner-brauhelfer-2-ini.zip](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/3745402/kleiner-brauhelfer-2.zip)

**Comment by BourgeoisLab** [comment]
Can you try with this version:
[kleiner-brauhelfer-2.zip](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/3745949/kleiner-brauhelfer-2.zip)

It will create a log file (logfile.txt) in the C:\Users<user>\AppData\Roaming\kleiner-brauhelfer directory. Hopefully this will help...

**Comment by maxliemant** [comment]
I can verify that it is working on my linux machine as expected.
It seems to be a problem with my setup. 

See the attached [logfile.txt](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/3747102/logfile.txt)

**Comment by BourgeoisLab** [comment]
Even though the problem is with your setup, I wonder what is going on...
So next try:

Download the portable version, just to make sure we use the same files:
[kbh2_v2.0.0beta3_portable_win_x64.zip](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/releases/download/v2.0.0beta3/kbh2_v2.0.0beta3_portable_win_x64.zip)

Replace the exe with this one:
[kleiner-brauhelfer-2.zip](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/3747675/kleiner-brauhelfer-2.zip)

And attach the logfile again.

With a "correct" run, it should look like this:
```
...
INFO  | 20.10.19 11::33::37.995 | Brauhelfer::save()
DEBUG | 20.10.19 11::33::37.995 | SqlTableModel::submitAll(): "Malz"
DEBUG | 20.10.19 11::33::37.995 | SqlTableModel::select(): "Malz"
DEBUG | 20.10.19 11::33::37.995 | emit SqlTableModel::submitted()
DEBUG | 20.10.19 11::33::37.995 | emit SqlTableModel::modified()
DEBUG | 20.10.19 11::33::37.995 | SqlTableModel::submitAll(): "Hopfen"
DEBUG | 20.10.19 11::33::37.995 | SqlTableModel::select(): "Hopfen"
DEBUG | 20.10.19 11::33::37.995 | emit SqlTableModel::submitted()
DEBUG | 20.10.19 11::33::37.995 | emit SqlTableModel::modified()
...
```

**Comment by maxliemant** [comment]
This time I just changed an existing recipe.
The log output stops after `SqlTableModel::select(): "Malz"`.

[logfile.txt](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/3748306/logfile.txt)

**Comment by maxliemant** [comment]
@BourgeoisLab 
If you want to debug this stuff, I could give it a try. 
Although I am more a Kotlin/Java developer and do not have so much expierence in C++.

Just give me some hints for what I should watch out and were may be the critical parts of your application regarding this.

Does IntelliJ work well for debugging C++ programs? Which IDE are you using?

**Comment by BourgeoisLab** [comment]
I wanted to send you this evening 1-2 versions with modified code to test.

Not sure if you'll see something with the debugger... But if you want to try, this could help, of course.

- First you will need Visual Studio Community edition. You just need to install it, you don't need to run it (no registration needed). 
- Next I think you need the "Debugging Tools for Windows". You can find it in the SDK (install only the debugging tools) https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk
- Next install Qt 5.13.0 Open Source Edition (no registration needed). During the installation make sure to install the components "Qt Charts" and "Qt WebEngine". Qt is a C++ Frameworks with tons a features (GUI/SQL/...) and uses the Visual Studio compiler.
- With both installed you can run Qt Creator and open the main project file kleiner-brauhelfer-2.pro.
- Select the "Debug" version in the lower left corner

**Comment by maxliemant** [comment]
Alright.
I will check this out asap. But won't make it before tomorrow evening.

**Comment by BourgeoisLab** [comment]
Check these 2 versions.
[kleiner-brauhelfer-2.zip](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/3752457/kleiner-brauhelfer-2.zip)

**Comment by maxliemant** [comment]
Hey, I finally tried your two versions, but looks like it still don't work well.
Maybe the logoutput gives you some more hints now.
[logfile-noMalztabelle-test.txt](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/3780943/logfile-noMalztabelle-test.txt)
[logfile-noRohstoffAuswahl-test.txt](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/3780944/logfile-noRohstoffAuswahl-test.txt)

**Comment by BourgeoisLab** [comment]
It's strange. I don't know why ModelMalz::dataExt() (last entry) is called in your case. It's not called on my side. 

I don't know what to do next. If you can try to run the debbuger this might help...

**Comment by BourgeoisLab** [comment]
One more thing:
check if the "Visual C++ Redistributable für Visual Studio 2015" and 2017 are installed. Or reinstall them:

2015:
https://www.microsoft.com/de-de/download/details.aspx?id=48145

2017:
look in the directory of the programm for vc_redist.x64.exe

**Comment by BourgeoisLab** [comment]
I made a new version with some changes. Can you try it?

[kleiner-brauhelfer-2beta4-rc1.zip](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/3827616/kleiner-brauhelfer-2beta4-rc1.zip)

**Comment by BourgeoisLab** [comment]
I think I finally got it.
[kleiner-brauhelfer-2beta4-rc2.zip](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/3833151/kleiner-brauhelfer-2beta4-rc2.zip)

**Comment by maxliemant** [comment]
Hey, I tested both versions and it didn't change. Also this time there are no logs.
Also `C++ 2015-2019` is installed and it doesn't let me install 2017 as "there is another version".

**Comment by BourgeoisLab** [comment]
From: https://hobbybrauer.de/forum/viewtopic.php?f=3&t=21510&p=355610#p355610

> Das Problem mit dem Absturz bleibt unauffindbar. :crying Gestern habe ich mit Innuendo ziemlich lange an der Ursache gesucht. Wir haben den Debugger auf seinem Laptop laufen lassen und den Absturz reproduzieren können. Der crash passiert aber im Qt internen code, so dass wir nicht tiefer gehen konnten. Da helfen auch Logfiles nicht... Ich habe gewisse Codeteile dann ausgeschaltet und es ging ohne Abstürze. Aber es war nicht nachvollziehbar wann und wieso es passiert, so dass wir es irgendwann abgebrochen haben.
> 
> Lange Reder kurzer Sinn, ich finde den Bug nicht. Meine Hoffnung ist nun, dass es mit der neusten Qt Version besser geht...

Log must now be enabled in the ini file (LogLevel=1-4 or 999). But they don't show anything useful...

**Comment by BourgeoisLab** [comment]
Please try the new beta:
https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/releases/tag/v2.0.0beta4

At least for one people, the change to Qt5.13.2 solved the crash problem

**Comment by maxliemant** [comment]
Closing as it seems to work now with `beta 4`
