### ISSUE TITLE
round() undefined in tabetikette.cpp

### ISSUE THREAD

**Issue by ivh** [kleiner-brauhelfer/kleiner-brauhelfer-2#4]
Wenn ich selbst im QTcreator kompiliere, muss ich ein #include <math.h> zu tabetikette.cpp zufügen, weil da was gerundet wird, sonst tut es bei mir (Debian/stable) nicht.

**Comment by BourgeoisLab** [comment]
Das wurde bereits im commit e9c8440f3d4ef09f223d0b8dd77c750e9561dd9c gelöst (round() durch qRound() ersetzt).

**Comment by ivh** [comment]
Oops, sorry, das hatte ich verpasst. :)
