### ISSUE TITLE
Braudaten: "Stammwürze beim Anstellen" wird automatisch geändert

### ISSUE THREAD

**Issue by Ventusfahrer** [kleiner-brauhelfer/kleiner-brauhelfer-2#40]
beim Ändern des darunter liegenden Feldes Würzmenge (20°C).

Ich habe dazu ein kleines [Bildschirm-Video ](https://psimon7v.de/owncloud/index.php/s/6TTpr6BQpEAoZnZ) gemacht.

Ich kann mir nicht vorstellen, dass das so gewollt ist?

Grüße

Peter

**Comment by BourgeoisLab** [comment]
Danke fürs Video. Bug korrigiert mit 9992784.
lg
