### ISSUE TITLE
[Bug] Kopie mit falschen Werten

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#41]
a) Wenn die Hopfenmenge x% bei 0 min (Kochende) auf einen Minuswert (Ausschlagen) geändert wird und die Hopfenmenge dadurch mit 999g berechnet wird, kann das Rezept nicht mehr korrekt kopiert werden:
b) Wenn die Hopfenmenge x nicht ausreichend vorhanden ist (rot), kann das Rezept nicht korrekt kopiert werden:
 
Einträge Malz und Hopfen sind dann doppelt vorhanden und/oder aus anderen Rezepten übernommen.

KBH muss in diesem Fall beendet und neu gestartet werden. Erst dann kann ein Rezept ordentlich kopiert werden.
Dieser Bug ist auf Mac reproduzierbar.

**Comment by BourgeoisLab** [comment]
Ist das bei dir immer noch so?

**Comment by Rasinari** [comment]
Ist erst gestern beim Kopieren eine zuvor importierten Rezeptes wieder aufgetreten: Falsches Rezept kopiert, doppelte Zutaten - trotz speichern der Vorlage zuvor.
Tritt aber so unregelmäßig auf, dass ich keine generelle Aussage treffen kann.

Gerade eben alles OK.

Ich vermute es hängt mit dem Speichern vorheriger Bearbeitungen zusammen.
Ich kann mir vorstellen, dass der Einbau einer Speicherroutine etwa alle 10 min generell helfen könnte…

**Comment by BourgeoisLab** [comment]
Ich glaube, ich weiss woher die Fehleinträge kommen. Das sind wahrscheinlich "Leichen" aus einem Sud, der irgendwann gelöscht wurde. Sagen wir der Sud hatte die ID 75. Beim Löschen wurde die ID 75 gelöscht, aber nicht die Rohstoffeinträge. Beim erstellen eines neuen Sud wurde die ID 75 neu vergeben und die Einträge entsprechend dem Sud zugewiesen. Die Leichen kommen wahrscheinlich noch vom brauhelfer v1.

Wann man die Datenbankreinigung benutzt, sollten diese "Leichen" detektiert werden.

Ich schliesse die Issue. Einfach wieder öffnen, falls die Vermutung doch nicht richtig ist.

**Comment by Rasinari** [comment]
Du hast vollkommen recht: Es betraf zuvor gelöschte IDs. Hatte die DB bereinigt, aber vllt. waren noch Reste drin. Taucht aktuell nicht mehr auf.
Vielen Dank. Großartig!
