### ISSUE TITLE
Etiketten erstellen funktioniert mit dem App-Image nicht

### ISSUE THREAD

**Issue by Ventusfahrer** [kleiner-brauhelfer/kleiner-brauhelfer-2#42]
Hi,
ich verwende zum Testen von kb-2.0 Beta auf Linux (ich arbeite ausschließlich auf Linux)  _kleiner-brauhelfer-2-x86_64.AppImage_.

Der Grund dafür ist, dass ich vermute mit der Installation des .deb Paketes mir meine produktive Version 1.4.4.6 zu überschreiben. Das AppImage verwendet eine eigene Konfiguration und erlaubt deshalb auch eine andere Datenbank als die installierte kb-version.

Mit der _kleiner-brauhelfer-2-x86_64.AppImage_ kann ich jedoch keine Etiketten erzeugen obwohl die dazu gehörigen Dateien laut strace gefunden werden.

Was mache ich falsch?

Danke für Tipps.

Peter
[kbh.log](https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/files/3762443/kbh.log)

**Comment by Ventusfahrer** [comment]
Hi, 
obige Ausgabe stimmt nicht!
Mein Problem war die in V2 geänderte Oberfläche und das geänderte Verhalten.

In KBH V1 hat man in der linken Spalte des Bierlabel/Etiketten-Tabs unter  **Auswahl aus Anhängen des Rezepts (svg)**  eine Dropdown mit genau einem Eintrag **Beispiel Label** stehen.
Den Label _Auswahl aus Anhängen des Rezepts_ hatte ich nie richtig verstanden. Die Dropdown-Box mit **Beispiel Label** lies auch keine weitere Auswahl zu, also hatte ich mich damals auf die Suche nach der Datei streifen_vorlage.svg (Information aus der rechten knappen Online Doku auf joerum.de) gemacht und diese direkt geändert. Funktionierte, das reichte.

Nach Installation der notwendigen Entwicklertools, Clonen des Github-Repositories und kurzem Debuggen der KBH 2.x BETA habe ich das veränderte Verhalten der V2 interpretieren:

Die DropDownBox gibt es immer noch, **aber ohne erklärendes Label, und in der Liste fehlt der alt-bekannte _Beispiel-Label_**. Weil der initiale DropDown Eintrag leer ist und der DropDownButton ganz einsam und versteckt auf der Rechten Seite des Dialogs platziert ist, fällt die DropDown über dem riesengroßen karierten Hintergrund der Label-Anzeige überhaupt nicht auf. Wenn man den Drop-Down Button drückt, ist die Liste plötzlich mit zwei Vorlagen (streifen_vorlage.svg und streifen_vorlage_farbig.svg) gefüllt. Wenn ich davon eine auswähle, wird sie auch angezeigt und ich kann mein PDF-File wie gewohnt erzeugen.

Jetzt habe ich auch den Label "Auswahl aus Anhänge..." der V1 verstanden. In V1 kann man eine angepasste .svg Grafik-Datei dem Rezept im Tab Rezept **Anhänge** hinzufügen. Diese erscheint dann in der DropDown-Liste nur wenn das Rezept einen .svg Anhang hat, lässt sich in der Drop-Down-Liste auch alternativ zu **_Beispiel Label_** was auswählen. Alle weiteren .svg-Dateien im kbh v1 config Verzeichnis werden ignoriert. Damit ist der alternative Flaschenlabel Rezept abhängig.

Jetzt meine Punkte zu V2:

1. Alle .svg Dateien aus dem Config Verzeichnis werden in der Drop-Down-Liste gelistet und können verwendet werden. 
2. Durch den fehlenden Standard-Eintrag in der Drop-Down-Liste ist die Ettiketten-Darstellung von vornherein leer - anders als in V1. Hier sollte man streifen_vorlage.svg als Standardeintrag vorgeben. Dadurch wird die Grafig gefüllt und die DropDownListe fällt besser auf
3. Es ist nach wie vor möglich eine .svg als Anhang einzufügen. Diese wird anschließend in der Drop-Down-Liste auch aufgeführt, aber der Inhalt bei Selektion nicht in den Darstellungsbereich des Dialogs geladen. Da es auf der Oberfläche keinen Hinweis mehr auf die weitere svg-Quelle (Anhänge) mehr findet, könnte man entweder den Eintrag aus der Drop-Down-Liste entfernen oder man sorg dafür, dass der Inhalt bei Selektion ordnungsgemäß geladen wird.

Puh, hoffentlich war die Ausführung jetzt nicht zu anstrengend.

Grüße

**Comment by BourgeoisLab** [comment]
Zu 2:
Die Information, dass man keine Etikette verwendet (d.h. leere dropdown) finde ich sinnvoll. Deshalb ist es am Anfang leer. Man könnte sich vorstellen, dass im Spickzettel/Zusammenfassung die Etikette erscheint, falls eine Etikette ausgewählt wurde (und nur dann).

Zu 3:
Ein Hinweis fehlt. Das werde ich ändern.
Ein Anhang muss nicht zwinged eine Etikettenvorlage sein. Deshalb muss man trotzdem manuell die svg noch auswählen.

Zu 4:
Stimmt.

**Comment by BourgeoisLab** [comment]
Erledigt mit 72c98dd.
