### ISSUE TITLE
Maybe a [Bug] Braudaten Stammwürze Speichern setzt Eingabe auf Zielstammwürze zurück 

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#44]
Gibt man einen Wert bei "Stammwürze nach Kochende" im Tab Braudaten ein und speichert unmittelbar, wird der Wert wieder auf dei Zielstammwürze im rechten Feld zurückgesetzt.

Erst die Korrektur der Würzemenge nach Kochende lässt ein richtiges Speichern zu.

Diskussion: Zusammenhang müsste optisch eindeutig kommuniziert werden.

**Comment by BourgeoisLab** [comment]
Das könnte mit dem "Speicherbug" zusammenhängen. Falls es immer noch passiert, kannst du die Issue einfach nochmals öffnen.
