### ISSUE TITLE
Nachkommastellen Hopfen

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#45]
Im Bereich Hopfen im Tab Rezept wird ein Hopfen rot markiert, wenn sein prozentualer Wert unter 0,1% fällt. Im Spickzettel wird die Menge richtig angegeben.
Dies ist besonders der Fall, wenn Hopfengaben nach Gewicht berechnet werden und unter der Hopfengabe Hopfen mit niedrigem Alphawert darunter sind.

Vorschlag: Hopfen prozentual und gewichtsmäßig auf 2 Nachkommastellen berechnen lassen

**Comment by BourgeoisLab** [comment]
Ich sehe den Sinn nicht Hopfen in 100stel Gramm anzugeben. Über das ganze Programm werden die Hopfenangaben in Gramm angegeben. Deswegen find ich es auch richtig, dass auch bei eine Zugabe von 0.1% das Feld rot erscheint. Das zeigt dem Benutzer, dass man hier genauer hinschauen soll.

**Comment by Rasinari** [comment]
Punkte, die ich kritisch sehe: Bei unter 0,1 kann es zu Fehlberechnungen an anderer Stelle kommen. Die Werte ergeben nicht exakt 100%. Ob sich letztes auswirkt, entzieht sich meiner Kenntnis.

Ich sehe es problematischer:
Das rote 0,1% Feld ergibt sich wegen fehlender 1/100, wenn man bei den Haupthopfengabe beim Kochen prozentual zugibt und die Aromagaben bei Kochende, nach dem Ausschlagen unter 0,1% fallen. In diesem Fall werden bis zu 999g Hopfen bei 0,1% berechnet. D.h. die Hopfenrechnerei ist an diesem Punkt einfach falsch und KBH zwingt einen die Aromagabe entgegen der Rezeptidee zu erhöhen. Das sind dann schnell 40g und mehr Unterschied!

**Comment by BourgeoisLab** [comment]
Kannst du Screeshots anhängen, wo man den Unterschied zwischen Spickzettel und Rezeptteil sieht?

Die Eingabefelder für Hopfen sind auf 999g limitiert.

**Comment by Rasinari** [comment]
<img width="720" alt="Bildschirmfoto 2019-11-09 um 12 56 01" src="https://user-images.githubusercontent.com/51321250/68528277-e2480a00-02f0-11ea-990b-16413401559e.png">
<img width="742" alt="Bildschirmfoto 2019-11-09 um 12 58 07" src="https://user-images.githubusercontent.com/51321250/68528278-e70cbe00-02f0-11ea-8341-2638029699f2.png">
<img width="756" alt="Bildschirmfoto 2019-11-09 um 12 59 10" src="https://user-images.githubusercontent.com/51321250/68528279-ed029f00-02f0-11ea-8eea-ddb26d5affe2.png">
<img width="731" alt="Bildschirmfoto 2019-11-09 um 12 59 31" src="https://user-images.githubusercontent.com/51321250/68528280-ee33cc00-02f0-11ea-8b64-473279e99778.png">
<img width="742" alt="Bildschirmfoto 2019-11-09 um 12 59 43" src="https://user-images.githubusercontent.com/51321250/68528281-effd8f80-02f0-11ea-9e97-e5f25a9c3fe2.png">

**Comment by BourgeoisLab** [comment]
Zugegeben die Eingabe der Hopfens kann mühsam sein. 

Aber du versuchts in a) auf 5.5 IBU zu kommen, obwohl es als Aromahopfen gedacht ist. Rechts sieht man die IBU Ausbeute von 0.1%. Da braucht es entsprechend eine Menge, bis man auf 5.5 IBU kommt. Angezeigt wird durch die Eingabelimitierung nur 999g, aber intern wird der Wert höher sein. In diesem Fall solltest du eher mit "Prozentanteil entspricht Gewicht" arbeiten.

Das es zu Rundungsfehler kommt und der IBU nicht 100% erreicht wird, kann schon vorkommen. Aber das sehe ich nicht als kritisch.

Enventuell müsste man sich überlegen, die Berechnung etwas zu ändern. Zum Beispiel mit der Option einzelne Hopfengaben von der IBU Berechnung zu entfernen. In diesem Fall würde man die Gabe in Gramm/Liter eingeben. Aber das ist mehr oder weniger was jetzt gemacht wird mit der Ausbeute von 0.1%.

**Comment by Rasinari** [comment]
Sehe ich anders. Das Beispiel ist ein extremes. Aber selbst wenn ein Feinhopfen 0,3% IBU beitragen soll, können das schnell 200g sein, aber nur 30 oder 40 werden hinzugegeben.

Probiere es selber aus: Sobald Du beim Ausschlagen mit Nachisomerisierung Feinhopfen für die Aromagabe nutzt, zwingt Dich das Programm unrealistische Mengen zu nutzen. Das geht nicht.

Bei Aromagaben kommt es nicht auf IBU an. Mit einer Nachkommastelle mehr wäre das Problem behoben. 

Die Lösung eine Hopfengabe von der Berechnung auszunehmen ist auf den ersten Blick sympathisch, aber auf den zweiten auch nicht praxistauglich: Was ist, wenn ein Hochalpha als Aroma genutzt wird, aber die Gabe niedrig sein soll? Manche Hochalpha wie Pacfic Gem oder Columbus haben als späte Zugabe völlig andere Eigenschaften.

Ist eine zuästliche Nachkommastelle so problematisch?

**Comment by BourgeoisLab** [comment]
Du kannst doch die Menge an Aromhopfen auch in Gramm angeben (Bei "Prozentanteil entspricht IBU"). Wieso nutzt du das nicht?

Zuviele Nachkommastellen habe insofern nicht gern, weil dann die nach oben/unten Pfeile bei Eingabefeld zuwenig inkrementieren.

**Comment by Rasinari** [comment]
Nutze ich doch. Sobald ich aber auf die Prozenttaste für die 100% Berechnung klicke, wird der Anteil auf 0 gesetzt. Das war das Beispiel mit den 20g

**Comment by Rasinari** [comment]
Vielleicht liegt es nur an der Prozenttaste, die ausgeblendet wird, sobald 100%?

**Comment by BourgeoisLab** [comment]
Anteil von 0% IBU ist in demfall ja schon richtig. Verschwindet der  "-0%-Knopf" nicht, wenn du bei einem anderen Hopfen den "-0%-Knopf" drückst?

**Comment by Rasinari** [comment]
So ist es. Gerade auch entdeckt. Klicke ich auf auf den -0%-Knopf wird dann der Ausschlaghopfen auf 0g gesetzt.

Sorry, ich plädiere wirklich auf 2 Nachkommastellen. Man kommt zwar in einer genauen Abfolge hin, indem man Gramm beim Ausschlagen händisch eingibt. Das ist aber so eine Frickelei, die nicht selbsterklärend ist.

Wie gesagt, eine Lösung könnte sein, dass der -0%-Button mit 2 Nachkommastellen arbeitet, dann gerundet wird. Dann ist es auch egal, wenn Ausschalgen Hopfen 0% ist, aber KBH greift dann nicht in die Menge ein, da im Hintergrund alles prozentual gerundet wird und viele Nachkommastellen nicht stören. Wäre das eine Lösung?

**Comment by BourgeoisLab** [comment]
> Um es nochmal auf den Punkt zu bringen: **Der überaus hilfreiche -0%-Knopf setzt die Menge Hopfen Ausschlagen in einigen Fällen auf 0!**

Du drückst den Knopf aber schon bei einem anderen Hopfen, oder?

**Comment by Rasinari** [comment]
Definitiv ja.

**Comment by Rasinari** [comment]
Kommando zurück - dann wird Ausschlagmenge nicht verändert.

**Comment by Rasinari** [comment]
> > Um es nochmal auf den Punkt zu bringen: **Der überaus hilfreiche -0%-Knopf setzt die Menge Hopfen Ausschlagen in einigen Fällen auf 0!**
> 
> Du drückst den Knopf aber schon bei einem anderen Hopfen, oder?

Es gibt Fälle, da bleiben die Knöpfe stehen, drückt man Ausschlagsknopf. Umgekgehrt verschwinden alle.

**Comment by LondonRain** [comment]
Man will auf jeden Fall (Nach-)Kochendegaben in g/l angeben können.
Ich hatte auch letztens (noch in der 1er-Version) bei einem DIPA-Rezept mit 30-Minuten Nachisomerisierung und großer Whirlpoolgabe damit gekämpft. Die einzig praktikable Lösung war den Hopfen nicht als Hopfengabe sondern weitere Zutat mit g/l zu erfassen, weil die Rumrunderei bei Aufteilung nach IBU grauenvoll fisselig war.

**Comment by Rasinari** [comment]
> Man will auf jeden Fall (Nach-)Kochendegaben in g/l angeben können.
> Ich hatte auch letztens (noch in der 1er-Version) bei einem DIPA-Rezept mit 30-Minuten Nachisomerisierung und großer Whirlpoolgabe damit gekämpft. Die einzig praktikable Lösung war den Hopfen nicht als Hopfengabe sondern weitere Zutat mit g/l zu erfassen, weil die Rumrunderei bei Aufteilung nach IBU grauenvoll fisselig war.

Interessante Lösung! Freut mich, dass ich nicht der einzige bin, der bei der Machisomerisierung zu kämpfen hat.
Das lässt die Idee aufkommen, die Hopfengabe Kochenende/Ausschlagen generell in Sonstige zu nehmen. Praktikabel ist das aber nur bei hochfeinen Sorten, Hochalpha-Sorten tragen meist dohc etwas IBU ein. Das Ergebnis wäre verwirrend  wie jetzt auch.

Der Knackpunkt ist der Wert 0,1%. Der ist zu groß angesetzt. Es sollte 0,01% sein. Auch 0,025% Schritte wären OK.

**Comment by BourgeoisLab** [comment]
Die Prozentangabe für die Hopfengaben haben jetzt 2 Nachkommastellen.

Da die Hopfengaben Kochenende/Ausschlagen Auswirkung auf den IBU Berechnung haben (wenn auch zum Teil minim), werde ich diese nicht in die "weitere Zutaten" schieben. Ich denke, das macht es zu unübersichtlich.

Eine Angabe in "g/L" ist durchaus denkbar. Ich habe jetzt aber schon Platzprobleme :) und fürchte, dass es noch unübersichtlicher wird. Zur Not, kannst du die Menge temporär auf 1L setzen.

**Comment by Rasinari** [comment]
> Die Prozentangabe für die Hopfengaben haben jetzt 2 Nachkommastellen.
> 
> Da die Hopfengaben Kochenende/Ausschlagen Auswirkung auf den IBU Berechnung haben (wenn auch zum Teil minim), werde ich diese nicht in die "weitere Zutaten" schieben. Ich denke, das macht es zu unübersichtlich.
> 
> Eine Angabe in "g/L" ist durchaus denkbar. Ich habe jetzt aber schon Platzprobleme :) und fürchte, dass es noch unübersichtlicher wird. Zur Not, kannst du die Menge temporär auf 1L setzen.

Super. Vielen Dank. Alle Rezepte mit späten Aromagaben werden es danken. Glaub mir. :-) 
Zu g/L: Das halte ich für redundant - das kann ja an anderer Stelle z.B. in der Auswertung stehen.
