### ISSUE TITLE
[BUG] beta 4 - Sud kann nicht abgefüllt werden

### ISSUE THREAD

**Issue by maxliemant** [kleiner-brauhelfer/kleiner-brauhelfer-2#52]
**Current**:
Rezept mit Hopfenstopfen.
Hopfen wurde hinzugefügt.
Hopfen wurde wieder "entnommen".

Wenn klick auf Sud abgefüllt: Fehlermeldung "Es wurden noch nicht alle Zutaten für die Gärung zugegeben oder entnommen"
Es gibt keine Möglichkeit weiterhin Zutaten hinzuzufügen oder zu entnehmen.

**Expected**:
Sud kann abgefüllt werden.

Besser:
Sud kann auch abgefüllt werden, auch wenn Zutaten noch nicht entnommen wurden.

**Explanation**:
Wenn ich mein Bier abfülle, "entnehme" ich nicht erst den Stopfhopfen, sondern fülle direkt ab, indem ich das Jungbier vorher filtere. 
IMO, das ist ein Schritt in der Realität und sollte nicht mehrere Schritte in der App sein.

**Comment by BourgeoisLab** [comment]
Den Bug kann ich nicht nachvollziehen / reproduzieren.

Die Meldung kommt, damit man Schritte nicht vergisst. Es geht vor allem um die Zugabe. Bei der Entnahme, kann ich mir vorstellen, dass die Meldung nicht mehr kommt und die Zutaten automatisch als "entommen" markiert werden.

**Comment by maxliemant** [comment]
Ok, ist evtl ein Nutzer-Problem.
Es geht hier um die laut System fehlende Hefegabe. 
![grafik](https://user-images.githubusercontent.com/45594714/69672225-f1bca680-1097-11ea-8314-5ae031c92fdb.png)
Leider konnte ich nicht finden, wie man die Hefe dann dazugibt.

**Comment by BourgeoisLab** [comment]
OK. Die Hefe kannst du im Reiter "Rezept" bei den Hefegaben zugeben.
