### ISSUE TITLE
Keine Zuckerberechnung mehr

### ISSUE THREAD

**Issue by planbnet** [kleiner-brauhelfer/kleiner-brauhelfer-2#55]
In der neusten Version (für mit dieser Version angelegte Sude) erscheint das Eingabefeld für Zuckerfaktor und das Feld mit der berechneten Zuckermenge nicht mehr. Für die alten Daten wird es weiterhin angezeigt.

**Comment by BourgeoisLab** [comment]
Diese felder werden nur angezeigt, falls eine zuckergabe auch tasächlich nötig ist. Sprich, nicht genügend Speise entnommen oder wert für den restextrakt noch nicht gesetzt.

**Comment by planbnet** [comment]
Oh das hätte ich mir denken können. Bin in diese Falle gelaufen weil ich mich entschieden habe, doch mit Zucker statt der eingefrorenen Speise zu karbonisieren.

**Comment by BourgeoisLab** [comment]
Du kannst in dem Fall die Speisemenge im Reiter Abüplldaten wieder auf 0 setzen.
