### ISSUE TITLE
Ctrl-Q

### ISSUE THREAD

**Issue by ivh** [kleiner-brauhelfer/kleiner-brauhelfer-2#57]
Der Keyboard-Shortcut zum Beenden ist verloren gegangen.

**Comment by realholgi** [comment]
Hmm, in der aktuellen Mac-Version nicht nachvolziehbar. Sieht nicht nur aus, funktioniert auch.

<img width="308" alt="Bildschirmfoto 2019-12-14 um 07 42 35" src="https://user-images.githubusercontent.com/980419/70844739-69832300-1e45-11ea-9a42-e31f99917bf8.png">

**Comment by ivh** [comment]
So sieht das bei mir auf Linux aus. Aktueller _master_ mit QtCreator gebaut.
![noctrlq](https://user-images.githubusercontent.com/134957/70844999-a3eebf00-1e49-11ea-8330-af0588a2d475.png)

**Comment by BourgeoisLab** [comment]
Mit 9f73598 sollte es wieder bei Mac, Linux & Windows wieder funktionieren.

**Comment by ivh** [comment]
In der Tat! Danke! :bowing_man:
