### ISSUE TITLE
Typo(s)

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#58]
Ich sammel mal, wenn ich was finde.

In der Sudübersicht:
![grafik](https://user-images.githubusercontent.com/33151586/71592692-8308b800-2b31-11ea-98b5-f493be94322b.png)

Der **R**est. Großes R. Die anderen Überschriften sind zwar keine Substantive, aber wenn man will könnte man sie als Überschrift auch groß setzen.

**Comment by LondonRain** [comment]
![grafik](https://user-images.githubusercontent.com/33151586/71592726-a5023a80-2b31-11ea-8bc5-0982184a5892.png)
"schließen" statt "schliessen"

**Comment by LondonRain** [comment]
![grafik](https://user-images.githubusercontent.com/33151586/71592878-38d40680-2b32-11ea-807e-7e8c13fb005d.png)
ale = alle?

Eigentlich hatte ich aber nach einer Erklärung gesucht, was das kursive bedeutet.

**Comment by LondonRain** [comment]
![grafik](https://user-images.githubusercontent.com/33151586/71593028-a849f600-2b32-11ea-9423-7d7db8071dcf.png)
Tooltip vom "Rezept importieren" Button: "kompatible" -> "kompatibel" (Buchstabendreher)

**Comment by BourgeoisLab** [comment]
Danke. Wird bei Gelegenheit korrigiert.
Ich werde die Issue offen lassen, so kannst du (oder andere) hier einfach die Typos melden.

**Comment by LondonRain** [comment]
![grafik](https://user-images.githubusercontent.com/33151586/71685016-68d01380-2d97-11ea-973a-1070477f4078.png)
Schlie**ß**en

Im Title hatte ich es schon oben gemeldet, aber hier kommt es auch in der Message selbst noch mal vor.

**Comment by LondonRain** [comment]
Tooltip Grid im Gärverlauf
![grafik](https://user-images.githubusercontent.com/33151586/72644360-1be06580-3971-11ea-9daf-c74c7029ebde.png)
Fehlendes Leerzeichen fehlendes a

**Comment by LondonRain** [comment]
Hier ist der Text irgendwie seltsam und nicht eindeutig. Ich vermute er sollte beschreiben, dass es dort die SHA der Anlage und nicht des Rezeptes ist.
![grafik](https://user-images.githubusercontent.com/33151586/73208420-b9445200-4146-11ea-93f0-afc5551c4cf5.png)

**Comment by LondonRain** [comment]
Tab Abfülldaten, Feld Verlust
![grafik](https://user-images.githubusercontent.com/33151586/73881017-e2a86080-485f-11ea-9136-0fe5a5e3ca41.png)

Tab Abfülldaten, Feld Zusätzliche Kosten
![grafik](https://user-images.githubusercontent.com/33151586/73881238-42067080-4860-11ea-917b-4ff0a714ef8c.png)
Text unklar - da fehlt irgendwie ein Teil. Weitere Zutaten: kleines **w**

**Comment by LondonRain** [comment]
![grafik](https://user-images.githubusercontent.com/33151586/75099688-c7aa5000-55c4-11ea-837a-cd725f58099a.png)
Fehlendes Leerzeichen.

**Comment by LondonRain** [comment]
![grafik](https://user-images.githubusercontent.com/33151586/75099713-0f30dc00-55c5-11ea-9930-979b737e8f2a.png)

en**t**spricht (+t)
Verdampfungs~~s~~seffekte**n** (-s +n)

**Comment by BourgeoisLab** [comment]
Bis hier alles korrigiert. Danke.

**Comment by LondonRain** [comment]
![grafik](https://user-images.githubusercontent.com/33151586/101680867-9c182980-3a61-11eb-8c65-c026da4b845b.png)
Die Tooltips für Ok und Abbrechen sind nicht die richtigen.

**Comment by BourgeoisLab** [comment]
gefixt

**Comment by Ventusfahrer** [comment]
![TypeSudListe](https://user-images.githubusercontent.com/5901190/106810898-dd961100-666d-11eb-99cf-2bb0a65ed2a2.png)
in der 2.2.3 - Sudliste...

**Comment by Rasinari** [comment]
Danke. Sehe ich erst jetzt. bitte Tippfehler weiterhin dokumentieren. Hilft sehr.

Bzgl.: "ss" - das ist das schweizerische "szett". ß gibt es in Schweizer Tataturbelegung m.W. nicht.

**Comment by BurtMC** [comment]
Version 2.3 
Rezept --> Maischen --> Extrakt

![grafik](https://user-images.githubusercontent.com/17658461/113351548-539bb900-933b-11eb-8177-25b69c5eb2c9.png)

Male --> Malze
Darrfverfahren --> Darrverfahren 
ist --> entfernen

**Comment by Rasinari** [comment]
Fehler in Tooltip wurde angepasst. Vielen Dank.

**Comment by LondonRain** [comment]
![grafik](https://user-images.githubusercontent.com/33151586/115114041-7cec5400-9f8d-11eb-8986-000668348929.png)
EtiketteN

**Comment by LondonRain** [comment]
![grafik](https://user-images.githubusercontent.com/33151586/115114702-f174c200-9f90-11eb-82b9-65a80a501f27.png)

Leerzeichen
gegebeneN
*E*inmaischtemperatur
deNEN

**Comment by Rasinari** [comment]
Danke London - fixed.

**Comment by BurtMC** [comment]
Reiter Rezept --> Maischen --> ToolTip für Extrakt bei Zusatz 

![grafik](https://user-images.githubusercontent.com/17658461/115988573-affc9c00-a5ba-11eb-89c6-69963105478b.png)

![grafik](https://user-images.githubusercontent.com/17658461/115988637-f225dd80-a5ba-11eb-91db-6459082835b9.png)

ntig --> nötig

**Comment by BurtMC** [comment]
Rezept --> Stammwürze (ToolTip)
![grafik](https://user-images.githubusercontent.com/17658461/115989356-3666ad00-a5be-11eb-8144-fafbeeb3155c.png)

iel --> Ziel

**Comment by Rasinari** [comment]
> Reiter Rezept --> Maischen --> ToolTip für Extrakt bei Zusatz
> 
> ![grafik](https://user-images.githubusercontent.com/17658461/115988573-affc9c00-a5ba-11eb-89c6-69963105478b.png)
> 
> ![grafik](https://user-images.githubusercontent.com/17658461/115988637-f225dd80-a5ba-11eb-91db-6459082835b9.png)
> 
> ntig --> nötig

@Frédéric: Ich finde das Widget nicht mehr. Wie heißt das jetzt?

**Comment by Rasinari** [comment]
> Rezept --> Stammwürze (ToolTip)
> ![grafik](https://user-images.githubusercontent.com/17658461/115989356-3666ad00-a5be-11eb-8144-fafbeeb3155c.png)
> 
> iel --> Ziel

An welcher Stelle ist das? Bitte einen größeren Ausschnitt als Screenshot. ich muss sonst alle Felder durchgehen.

**Comment by LondonRain** [comment]
Rezept / Maischplan / Einmaischen / Einmaischdauer
![grafik](https://user-images.githubusercontent.com/33151586/120098623-40d51300-c137-11eb-8bc7-1440923c6101.png)

fehlendes Leerzeichen
min -> Minuten
gebener -> gegebenen
Einmaischtemperatur (großes E)

**Comment by Rasinari** [comment]
Danke. Erledigt!
