### ISSUE TITLE
Tabs werden beim Speichern aus den Bemerkungen entfernt

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#60]
Da ich so immer mein Wasserprofils aus Bru'nWater kopiere ist das dann ein bisschen unschön in der Formatierung.

Beispiel:
<pre>
Profiles (ppm)	Exist	Mash	Finished
Ca		42	50	50
Mg		8	8	8
Na		40	40	40
SO4		39	39	39
Cl		58	72	72
HCO3		125	125	NA
SO4/Cl Ratio				0,5

Mineral Additions (gm)	Mash	Sparge		
Gypsum		0,0	0,0	
Calcium Chloride		0,6	0,4	
				
Mash Acid Additions      				
 	 	 	0,0	(ml)
Sparge Acid Addtions				
Lactic	80,0	%	2,3	(ml)
</pre>

**Comment by BourgeoisLab** [comment]
Das feld "bemerkung" wird als html interpretiert. Ich glaube es gibt einen html tag (<code>??), der tabs als solches interpretiert.

**Comment by BourgeoisLab** [comment]
Mit < code > geht es leider nicht.

Du müsstest das Ganze in einer HTML Tabelle packen. Dann geh'ts mit copy&paster natürlich nicht so gut.

**Comment by LondonRain** [comment]
< pre > geht! Oder? Ach, jetzt versteh ich auch erst: Es wird im Editiermode als HTML-Source und im Ansichtsmodus als gerendertes HTML angezeigt?

**Comment by BourgeoisLab** [comment]
Ah genau < pre > habe ich eigentlich gesucht:)
