### ISSUE TITLE
Karbonisierung mit Zuckerlösung

### ISSUE THREAD

**Issue by maxliemant** [kleiner-brauhelfer/kleiner-brauhelfer-2#61]
Ich karbonisiere mit Zucker. Dabei löse ich den Zucker vorher in Wasser auf und schlauche das Jungbier darauf. So muss ich nicht jede Flasche einzeln mit Zucker befüllen.
Dabei verändert sich das Volumen und ich denke, die Berechnung für den entgültigen Alkoholgehalt müsste dann auf das geänderte Volumen angepasst werden.
Ähnlich wie Karbonisierung mit Speise?

Dann wäre ein weiteres Eingabefeld für die Wassermenge notwendig.
Ich verwende zum Beispiel meistens ca. 1L Wasser und die angegebene Gesamtmenge an Zucker.

**Comment by bitwave** [comment]
Praktisch wäre auch die Option zum Umschalten pro Flasche, da ich z.B. nicht genau messen kann, wie viel Bier im Gärbottich ist und daher lieber pro Flasche rechne.

**Comment by BourgeoisLab** [comment]
Erledigt mit 575f1d6122f98896752e61d913e1dc32cc79b263.
(Kommt erst in der übernächsten Version 2.2.0)
