### ISSUE TITLE
Zielstammwürze vor Läutern

### ISSUE THREAD

**Issue by maxliemant** [kleiner-brauhelfer/kleiner-brauhelfer-2#65]
Ich arbeite mit einem Malzrohrsystem.
Daher kann ich nicht akurat die Stammwürze nach dem Läutern messen und ggf. etwas weniger Sparge wasser hinzugeben, wenn die SHA mal nicht so gut war. 
Ich denke, es wäre relativ einfach einen Näherungswert für die Zielstammwürze nach dem Maischen/vor dem Läutern zu errechnen.

**Comment by BourgeoisLab** [comment]
Die Berechnung lautet:
```
SollStammwürzeKochbeginn * (Hauptguss + Nachguss) / Hauptguss
```

Das kannst du im Spickzettel folgendermasse machen:
```
<script type="text/javascript">
  function parseFloat2(str) {
    return parseFloat(String(str).replace(',','.'))
  }
  document.write((parseFloat2({{Rezept.SWKochbeginn}})*parseFloat2({{Wasser.Gesamt}})/parseFloat2({{Wasser.Hauptguss}})).toFixed(1))
</script>
```

**Comment by BourgeoisLab** [comment]
Passt so, oder?

**Comment by maxliemant** [comment]
Ich hab das mal ausprobiert und das klappt leider nicht so.
Mit dem Läutern wird noch Zucker aus dem Malz ausgewaschen, weshalb die Zahl doch nicht so trivial zu berechnen ist.

Kann trotzdem geschlossen werden.
