### ISSUE TITLE
Braudaten um `Stammwürze bei Kochbeginn` erweitern

### ISSUE THREAD

**Issue by maxliemant** [kleiner-brauhelfer/kleiner-brauhelfer-2#67]
Es wäre nett, wenn man auch zusätzlich zum Volumen bei Kochbeginn auch die Stammwürze eintragen kann.
Schließlich ist auch bereits der Zielwert errechnet.

**Comment by BourgeoisLab** [comment]
Ich will das Programm eigentlich nicht mit Sachen überladen, die es für weitere Berechnungen gar nicht braucht. Was erhofst du dir mit dieser Information?

**Comment by maxliemant** [comment]
Das ist ein Wert den man einfach messen kann und dann auch als Anhaltspunkt zum Nachbrauen eines bestimmten Rezepts einfach benutzen kann.
Ich sammle "gerne" die Daten, die ich habe. Derzeit sammle ich sie lose auf irgendwelchen Zetteln, die hier irgendwo ungeordnet rumfliegen.
Wenn man das nicht braucht, kann man es ja auch auslassen/ausblenden lassen. Für die Berechnungen macht natürlich erst der Wert nach dem Hopfenkochen Sinn.

**Comment by BourgeoisLab** [comment]
Ich muss mir das noch überlegen. Ich will "anfänger" nicht mit "unnötigen" eingabefelder überfordern. Andererseits ist dokumentation schon auch wichtig. Ein/ausblenden wäre eine Möglichkeit. Vielleicht kann man "nötige" und "unnötige" felder farblich kennzeichnen.

Und dann sollen alle felder noch ins spickzettel:D

**Comment by maxliemant** [comment]
Du meinst nötige Felder für Berechnungen?
Das klingt gut. 
Vielleicht auch mit einem Tooltip erweitern (wenn nicht schon vorhanden) wofür der Wert benutzt wird?

**Comment by BourgeoisLab** [comment]
Eingabefeld gemacht mit 21ff284.
