### ISSUE TITLE
Ausrüstungstab: Spalte von Sudname nicht ziehbar

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#68]
![grafik](https://user-images.githubusercontent.com/33151586/72221627-df6dcd80-355c-11ea-995f-76dec16f8607.png)
Alle anderen Spalten lassen sich in der Größe verändern. Die hat aber leider keinen Anfasser.

**Comment by BourgeoisLab** [comment]
Gelöst mit 66d0686.
