### ISSUE TITLE
Refreshproblem bei Sud gebraut zurücksetzen

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#69]
Wählt man Sud/"Sud gebraut zurücksetzen" wechselt das Zusammenfassungs-Tab nicht direkt zum Spickzettel. Anderes Bier öffnen und dann das erste wieder öffnen geht als Workaorund.

**Comment by BourgeoisLab** [comment]
Gelöst mit 66d0686.
