### ISSUE TITLE
Hopfenangaben sollten wieder mindestens eine Dezimalstelle haben

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#70]
So kann der Nutzer selber entscheiden, ob ihm das wichtig ist, Bei Nanosuden ist das auch durchaus relevant. Ich vermisse das sehr.

Siehe auch:
https://hobbybrauer.de/forum/viewtopic.php?p=362528#p362528

**Comment by maxliemant** [comment]
+1

**Comment by BourgeoisLab** [comment]
Erledigt mit a99fd30ee28a6d9fcdff3fef42975f8aebd3dcf6.

**Comment by LondonRain** [comment]
Cool! Danke! Gilt das auch für die weiteren Zutaten?

**Comment by BourgeoisLab** [comment]
Ja mit 21ff284.
