### ISSUE TITLE
Rohstoffe: Kursive Schrift in Tooltip erklären

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#71]
Die kursive Schrift mancher Zutaten in der Zutatenliste sollte in einem Tooltip erklärt werden.

Siehe auch:
https://hobbybrauer.de/forum/viewtopic.php?p=363677#p363677

**Comment by BourgeoisLab** [comment]
Bereits gelöst mit 898c55293c8585aacfdc48bffa97e9467ce0aa86.
