### ISSUE TITLE
Spalten der Brauübersicht

### ISSUE THREAD

**Issue by ivh** [kleiner-brauhelfer/kleiner-brauhelfer-2#73]
In der Brauübersicht lassen sich ein paar Spalten nicht wie die anderen durch Rechtsklick auf die Titelleiste der Tabelle abschalten, u.a. SWKochbeginn, Verdampfungsrate und FaktorHauptgussEmpfehlung.

**Comment by realholgi** [comment]
Mach mal Ansicht->Wiederherstellen. Dann passt es wieder.

**Comment by realholgi** [comment]
Siehe https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/commit/3c49cfdda707b097a296e9ec6c4c3a717ac7403f#commitcomment-36756108

**Comment by ivh** [comment]
ah, danke!
