### ISSUE TITLE
Whirlpoolhopfung über Weitere Zutaten ermöglichen

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#74]
Nach gängiger Meinung trägt eine Whirlpoolhopfung bei <=80 °C,  also nach der Nachisomerisierungszeit, nicht mehr zur Bittere bei. Außerdem ist es gängig die Whirlpoolhopfung, wie beim Hopfenstopfen, in Gramm pro Liter anzugeben. Dies ist mit dem KBH zur Zeit nicht oder nur eingeschränkt möglich.

Wenn ich die Kochdauer auf das Ende der Nachisomerisierungszeit setze, rechnet er mit 0,1% (statt 0%) und man muss immer anteilig und fisselig mit den IBU oder Grammmengen herum spielen.

Ich behelfe mir zur Zeit unter _Weitere Zutaten_ so:
![grafik](https://user-images.githubusercontent.com/33151586/73206847-fe1ab980-4143-11ea-8c85-d13597469652.png)

Ich nehme an, dass jetzt neu seit KBH 2, das auch sogar schon besser funktioniert, da bei Zugabe nach 0 Tagen das beim gebraut markieren auch gleich von den Zutaten abgezogen wird? Trotzdem muss ich es dann noch entnehmen?

Hier wäre ein spezielles Flag für _Whirlpoolgabe_ sehr schön. Oder vielleicht ein weitere Zugabeart als dritter Knopf?
![grafik](https://user-images.githubusercontent.com/33151586/73207049-5baf0600-4144-11ea-84e9-38eb3ab9b3d7.png)

**Comment by BourgeoisLab** [comment]
Whirlpoolhopfung will ich lieber bei den normalen Hopfen lassen.
Ich habe die Mindestausbeute von 0.1% weggenommen. Wenn man als Zeitpunkt "Ausschlagen" wählt, ist die Ausbeute 0.0%.
Und ich habe auch ein Eingabefeld g/l hinzugefügt.

Damit sollte es eigentlich gut funktionieren.

**Comment by BourgeoisLab** [comment]
Erledigt mit 5bf4d9d41f74870d4110d5c4388c2bc3dad527cf.

**Comment by LondonRain** [comment]
Das klingt sehr gut. Danke! Bin gespannt wie es sich dann benutzt.

**Comment by BourgeoisLab** [comment]
Bei jeder änderung wird das programm automatisch kompilliert. Du kannst es hier herunterladen
https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/actions
Auf den letzten win64 eintrag klicken, dann den "artifact" (exe) herunterladen. Das sind nicht getestete versionen.

**Comment by LondonRain** [comment]
![grafik](https://user-images.githubusercontent.com/33151586/76021906-65d3d980-5f26-11ea-8226-b052ac79c503.png)
Der Vergleich mit der vorhandenen Menge scheint noch nicht zu klappen. Das Feld dürfte eigentlich doch nicht rot werden.

**Comment by BourgeoisLab** [comment]
Hast du eine zweite bavaria gabe?

**Comment by LondonRain** [comment]
Jau. Alles klar. Hatte es unter "Weiter Zutaten" noch nicht gelöscht. Danke.
