### ISSUE TITLE
Zu breit für Display

### ISSUE THREAD

**Issue by BurtMC** [kleiner-brauhelfer/kleiner-brauhelfer-2#75]
Ich habe gerade das **kleiner-brauhelfer-2-x86_64.AppImage** geöffnet und bekomme den Kleinen Brauhelfer leider zu breit angezeigt. Ich kann das Fenster nur in der Höhe verändern und minimieren.

![Bildschirmfoto vom 2020-01-27 20-51-10](https://user-images.githubusercontent.com/17658461/73208468-cc572200-4146-11ea-9c35-daaabce9deae.png)

Der Fehler besteht auch bei dem AppImage der Version 2.00.

Bei der Version 2.00 beta 5 geht es noch, da habe ich auch die Möglichkeit zu Maximieren.

**Comment by BourgeoisLab** [comment]
Erledigt mit 390ae075a74ba3a83b9525f4ebf12f2f2b19b5be.
