### ISSUE TITLE
Verdampfungsrate wird falsch berechnet

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#77]
Meine Kochdauer ist 60 Minuten.

Von 20 Litern verdampft nichts. Verdampfungsrate ist 0%. Korrekt.
![grafik](https://user-images.githubusercontent.com/33151586/73391726-ca24cd00-42d8-11ea-9c15-b676077daf80.png)

Von 20 Litern verdampfen 10. Verdampfungsrate ist 100%. Nicht korrekt. 10 Liter von 20 sind 50%.
![grafik](https://user-images.githubusercontent.com/33151586/73391799-ef194000-42d8-11ea-8590-f6173847fac9.png)

Von 20 Litern verdampfen 5. Verdampfungsrate ist 33,3%. Nicht korrekt. 5 Liter von 20 sind 25%.
![grafik](https://user-images.githubusercontent.com/33151586/73391937-2e479100-42d9-11ea-9866-d1f693fa9d68.png)

Bei 120 Minuten Kochdauer halbieren sich die Prozente der Verdampfungsraten. Das scheint immerhin richtig zu funktionieren.

Bei Verdampfung zwischen 0,1 und 10 Litern bleibt es bei den falschen 100%.

**Comment by BourgeoisLab** [comment]
Die Berechnung ist korrekt. Man muss unterscheiden zwischen Verdampfung und Verdampfungsziffer.
![img](https://hobbybrauer.de/bilder/olibaer/vzundgv.PNG)
Für die Verdampfungsziffer ist 100% die Ausschlagwürze (vor Hopfenseihen). Für die Verdampfung ist die Startmenge (Kochbeginn) 100%. Ich musste das auch wieder nachschlagen:).

Ich denke, im Programm sollte es nicht Verdampfungsrate sondern Verdampfungsziffer heissen. Und das Feld muss Werte grösser als 100% erlauben.

**Comment by LondonRain** [comment]
Der Wert der sich auf die Würzemenge (vor Hopfenseihen) bezieht ist aber doch ziemlich praxisirrelevant. Wichtig ist doch wie viel von meiner ursprünglichen Flüssigkeit in einer Stunde verdampft, damit damit die ursprünglich benötigte Wassermenge berechnet werden kann.

Die gängige Empfehlung von 10% Verdampfung pro Stunde bezieht sich doch auch darauf.

**Comment by BourgeoisLab** [comment]
Praxisrelevant ja, aber es ist nicht die Definition der Verdamfungsziffer. Zumindest nicht so wie ich sie (und kbh v1) verwende. Du redest eben von der Verdampfung:).

Hier meine Quellen:
http://www.brewrecipedeveloper.de/misc/brdh/Brew%20Recipe%20Developer%20Dokumentation%20DE.html?VerdampfungszifferuGesamtverdamp.html
und
http://www.teltschik.org/bier/kleinsud/tut7.htm

Müggeland scheint das anderes zu Berechnung (so wie du). Sie reden aber von Verdampfungsrate. Ob das ein anderer Begriff ist?
https://brauerei.mueggelland.de/maischfuehrung.html


Ich finde deine Berechnung auch logischer. Aber es entspricht nicht meine Quellen. Für das Programm ist es aber schlussendlich egal, wie gerechnet wird. Hauptsache es ist in Sich kohärent.

Wenn du andere Quellen hast gerne.

**Comment by LondonRain** [comment]
Hm, dann war mein Verständnis davon vielleicht auch immer falsch. Ich war auch fest davon überzeugt, dass das im KBH 1 so berechnet wurde, wie ich oben von ausgegangen war. Das habe ich gerade noch mal überprüft und da ist es genau so, wie es auch im KBH 2 ist.

![grafik](https://user-images.githubusercontent.com/33151586/73590554-06784900-44e4-11ea-92d6-3839eb90be4f.png)

Ich hab auch noch mal recherchiert und ich hab noch das hier gefunden, wo auch deine Formel zitiert wird. Wo ist die denn eigentlich her?
https://hobbybrauer.de/modules.php?name=eBoard&file=viewthread&tid=18136

Hier gibt es auch zwei Glossare, wo es so definiert wird, wie du angibst:
https://www.gradplato.com/bierwissen/verdampfungsziffer
https://www.hausgebraut.de/index.php?page=/Artikel/Glossar-Brauereispezifische-Fachbegriffe-fuer-Haus-und-Hobbybrauer_95&%3Bp=10&p=9

Dann würde ich dir zustimmen, dass es wichtiger ist, es so zu machen, wie es in der Fachliteratur üblich ist, als wie unser intuitives Verständnis es uns vielleicht logischer erscheinen lässt.

Ich würde dann folgendes vorschlagen:
1. Korrektur der Begrifflichkeit von Verdampfungsrate auf Verdampfungszimmer (so heißt es übrigens auch im KBH 1). Auch im Ausrüstungstab.
2. Fixen, dass es mehr als 100% anzeigen kann (geht auch im KBH 1)
3. Die untenstehenden Hilfetexte müssen angepasst werden. "Menge bei Kochende" gibt es in der Oberfläche seit 2.1 ja nicht mehr. Und auch dort sollte dann -ziffer statt -rate stehen.
4. Alle Berechnungen für Wassermengen beziehen sich dann auch auf dieses statt auf mein ursprüngliches Verständnis? Das hab ich jetzt nicht überprüft oder mit KBH 1 verglichen.

Hilfetexte:
"In diesem Feld kann die _Verdampfungsrate_ der Anlage eingegeben werden.
Der Wert selbst beschreibt die prozentuale Verdampfung pro Stunde beim Hopfenkochen bezogen auf die _Menge bei Kochende_." (Ausrüstungstab)

"Hier wird die geschätzte _Verdampfungsrate_ des Rezeptes auf der gewählten Anlage angegeben.
Der Wert wird mit jedem weiteren Sud genauer und im Tab Ausrüstung gemittelt. Üblicherweise liegt der Wert ober- oder unterhalb 10% pro Stunde." (Rezepttab, rechts die Sudspalte)

"Hier gibt der Kleine Brauhelfer die berechnete _Verdampfungsrate_ pro Stunde des Sudes aus.
Der Wert fließt in die Duchschnittsberechnung im Tab Ausrüstung ein, so er dort oder hier im Tab Braudaten nicht ignoriert wrd" (<- da fehlt auch noch ein "i" bei wird und ein "r" bei Durchschnitt)

**Comment by BourgeoisLab** [comment]
Erledigt mit c5ae934fd0bfffc2af07be8ba94c8280a872718c.
