### ISSUE TITLE
Datenbank bereinigen: Usability verbessern für "Eintrag löschen"

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#78]
![grafik](https://user-images.githubusercontent.com/33151586/73392983-22f56500-42db-11ea-9e2c-a779d87d7509.png)

1. Eintrag löschen hat keine Funktion. Es passiert nichts und beim nächsten Durchlauf der Funktion ist es immer noch da.
2. Da sind Rasten, Malzschuettung, Hopfengaben, WeitereZutatenGaben, Schnellgaerverlauf, Nachgaerverlauf, Etiketten relativ kürzlich gelöschter Sude. Die wurden offenbar nicht mitgelöscht. Das ist aber inzwischens schon gefixt?
3. Typo: "Eintrag Löschen" -> "Eintrag **l**öschen"

**Comment by BourgeoisLab** [comment]
Du musst die einträge, die du löschen willst auswählen. Hast du das gemacht?

**Comment by LondonRain** [comment]
Ah. Nein, das hat sich mir nicht erschlossen. Vielleicht Checkboxen dran machen? Oder wenn nichts markiert wurde eine Fehlermeldung nach Klick auf den Löschenknopf ausgeben?

Hat aber auf jeden Fall so geklappt. Danke!

**Comment by BourgeoisLab** [comment]
Daran habe ich auch gerade gedacht. Schliess die issue nicht, damit ich mich daran errinern kann.

**Comment by LondonRain** [comment]
Alles klar. Punkt 2 (Löschen in mit Sud verknüpften Tabellen, wenn dieser gelöscht wird) ist aber an sich bekannt und behoben? Und den Typo poste ich jetzt nicht noch mal extra in das andere Issue - das reicht ja hier, denke ich.

**Comment by BourgeoisLab** [comment]
Punkt 2 vermute ich, es kommt vom brauhelfer v1. Falls es von v2 ist, ist es nicht behoben.

Typo ok.

**Comment by LondonRain** [comment]
> Punkt 2 vermute ich, es kommt vom brauhelfer v1. Falls es von v2 ist, ist es nicht behoben.

Das kann gut sein. Zumindest funktioniert
- Sud kopieren
- Sud öffnen
- kopierten Sud löschen
- Datenbank bereinigen gibt keine neuen Fehler aus

Hier bekommt man übrigens ein leeres Fenster. Da wäre es nett wenn da stünde, dass keine Probleme gefunden wurden.

![grafik](https://user-images.githubusercontent.com/33151586/73394577-2c340100-42de-11ea-99fd-dc8c3796b17a.png)

**Comment by BourgeoisLab** [comment]
Erledigt mit f46ce17da18b1da36d90bb81ed2e52ab38ffc197.
