### ISSUE TITLE
Sudauswahl: Woche wird falsch berechnet

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#79]
![grafik](https://user-images.githubusercontent.com/33151586/73393408-e118ee80-42db-11ea-9602-b142494a4d05.png)

Das Rezept wurde ursprünglich als xsud importiert. Das Braudatum dieses Rezeptes könnte ungefähr zu den Wochen passen. Ich kann das Datum aber nirgends mehr finden.

**Comment by BourgeoisLab** [comment]
Die woche bezieht sich auf die letzte nachgärmessung und falls keine vorhanden ist auf das abfülldatum.

**Comment by LondonRain** [comment]
Ach verrückt. Da hab ich noch nie hingeklickt, weil ich das noch nie benutzt habe. Da steht tatsächlich noch ein altes Datum drin. Jetzt passt es. Sorry fürs falsches Issue einstellen. :(
