### ISSUE TITLE
kbh1 DB kann nicht konvertiert werden

### ISSUE THREAD

**Issue by Dirk23** [kleiner-brauhelfer/kleiner-brauhelfer-2#80]
Hallo,

ich habe gerade meine Datenbank versucht im kbh2 zu öffnen, leider schlägt de Konvertierung fehl:
![Bildschirmfoto 2020-02-04 um 08 25 12](https://user-images.githubusercontent.com/4200682/73723009-39128380-4728-11ea-851f-1ab19847c589.png)
Ich würde gerne schauen ob ich die kbh2 Datenbank in meinem Brauhelfer für iOS geöffnet bekomme, damit meine App auch in Zukunft funktioniert.

Gruß

Dirk

**Comment by BourgeoisLab** [comment]
Das wäre natürlich super mit der App. Falls du es aktualisiert haben willst, kann ich dir auch immer mitteilen, wenn sich an der Datenbank etwas ändert.

Du kannst hier nachschauen, was sich geändert hat:
https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/blob/master/kleiner-brauhelfer-core/database_update.cpp
Für den kbhv2 ist der Eintrag db_Version >= 2000

Eine der Hauptänderung ist das Löschen den Spalten 'BierWurdeGebraut', 'BierWurdeAbgefuellt' und 'BierWurdeVerbraucht'. Diese wurden ersetzt durch die Spalte 'Status'.
Hier hast du die Definition
https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/blob/master/kleiner-brauhelfer-core/database_defs.h

Wenn du fragen hast, kannst du mich gerne per email kontaktieren (bourgeoislab@gmail.com).


Jetzt zu deinem Problem: du hast zwei (oder mehr) Hopfeneinträge in der Rohstoffliste mit dem gleichen Name.
