### ISSUE TITLE
Usabilityidee für Sudfilter

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#81]
![grafik](https://user-images.githubusercontent.com/33151586/74590259-2db73600-500d-11ea-901c-640cfb8f396d.png)

Es wäre nett, wenn man mit Klick mit der mittleren Maustaste nur das angeklickte Kästchen selektieren (und alle anderen deselektieren) könnte.

**Comment by LondonRain** [comment]
Vielleicht auch Links/Knöpfe für "Keine", "Alle", "Umkehren".

**Comment by BourgeoisLab** [comment]
Ich habe es in der neue Version etwas angepasst. Das Checkbox "Alle" schaltet zwischen "alle" und "keine". Reicht dir das?

**Comment by LondonRain** [comment]
Ja, klingt gut. Probier ich dann beizeiten mal aus. Danke!
