### ISSUE TITLE
Schieberegler für PDF-Schriftgröße verschwunden

### ISSUE THREAD

**Issue by LondonRain** [kleiner-brauhelfer/kleiner-brauhelfer-2#82]
Wurde der entfernt? Es gab doch mal in der Nähe des PDF speichern-Knopfes so einen Schieberegler, um die Schriftgröße (und damit dann die Seitenzahl) des PDFs zu beeinflussen.

**Comment by BourgeoisLab** [comment]
Das war in Version 1.x

**Comment by LondonRain** [comment]
Ach krass, wie man sich so falsch erinnert. Ich hätte geschworen, den auch in 2 schon benutzt zu haben. 😉 Dann mach entweder zu oder betrachte es als Feature Request. Kam auf drei Seiten Ausdruck und hätte es gerne auf 2 runter skaliert, damit es doppelseitig auf ein Blatt passt.

**Comment by BourgeoisLab** [comment]
In Version 2 ist das Template frei editierbar. Deswegen kann ich die Textgrösse nicht so gut setzen.
Ich habe probierst, einen Zoomfaktor einzubauen, das ging aber auch nicht richtig (Darstellung schon, aber nicht Ausdruck).

Ich schliesse es mal, aber wenn es dir sehr wichtig ist, mach es wieder auf.

Du kannst ins Editiermodus gehen, dann auf "style_hell.css" (oder "style_dunkel.css") und dort unter "body" die "font-size" einstellen. Das ist dann aber allgemeingültig...

**Comment by LondonRain** [comment]
Alles gut. Ist mir nicht _so_ wichtig.
