### ISSUE TITLE
"Würzemenge bei Kochbeginn" ist auf 0 gesetzt

### ISSUE THREAD

**Issue by maxliemant** [kleiner-brauhelfer/kleiner-brauhelfer-2#83]
Anscheinend wurde mit dem letzten Update die "Würzemenge bei Kochbeginn" auf 0 gesetzt für bereits gebraute Sude.
Dadurch ist natürlich die Verdampfungsrate nicht berechenbar und wird schlicht als 0 angezeigt.
Sind die Daten generell noch da und können wiederhergestellt werden?
![grafik](https://user-images.githubusercontent.com/45594714/75119318-136eff00-5682-11ea-8f6d-33da3b363584.png)

**Comment by maxliemant** [comment]
Außerdem frage ich mich, ob es wirklich eine Verdampfungsrate in % sein sollte.
Generell sollte es unabhängig davon sein, wie viel Volumen es vorher war. 
Wenn ich eine Stunde koche verdampfen 3l. Egal ob es vorher 30l waren oder 10l. Bei dem selben Gerät natürlich.

**Comment by BourgeoisLab** [comment]
Für die Berechnung der verdampfungsziffer hast du vielleicht schon recht. Aber so wie implementiert, wird es in der literatur verwendet. Siehe auch diskussion https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/issues/77

**Comment by BourgeoisLab** [comment]
Und zu deinem problem, siehe https://hobbybrauer.de/forum/viewtopic.php?p=363544#p363544

**Comment by LondonRain** [comment]
![grafik](https://user-images.githubusercontent.com/33151586/76895367-25fae380-6890-11ea-83a0-d5d59905ae6c.png)

Mir hat diese Tabelle und SQLiteSpy geholfen, die Daten manuell zu korrigieren.
