### ISSUE TITLE
KBH als Web-Anwendung?

### ISSUE THREAD

**Issue by dondieselkopf** [kleiner-brauhelfer/kleiner-brauhelfer-2#84]
Hallo @BourgeoisLab !

Gibt es Überlegungen, den KBH mal als Web-Anwendung zu entwickeln? Damit würde sich der Aufwand zur Wartung der verschiedenen Plattformen reduzieren und für den User wäre es einfacher, unterschiedliche Endgeräte zu nutzen.

**Comment by BourgeoisLab** [comment]
Das wird es sehr wahrscheinlich nicht geben nein. Zumindest nicht von mir:).

Für eine Web-Anwendung braucht es einen Server und das bedeutet Kosten & Wartungsaufwand. Mit Qt ist der Aufwand für die verschiedenenen Platformen eher gering (wenn es einmal läuft).

Und zudem bin ich in HTML / CSS / Javascript nicht sehr fit und will es auch nicht gross vertiefen.

**Comment by dondieselkopf** [comment]
Mir würde es in den Fingern jucken, sowas mal anzugehen. Was die Serverkosten betrifft, die wären sicherlich leicht über Werbung oder Partnerprogramme abzudecken. Die Wartung ist durchaus ein Thema, aber wir sprechen ja hier nicht über Banking-Software ;) 

Eine Parallelentwicklung zu dem, was du aktuell machst, sehe ich aber nicht als sinnvoll an. Da sollte man seine Kräfte schon bündeln. Kannst du dir vorstellen, dich an so einem Projekt irgendwie zu beteiligen oder ist das eher ausgeschlossen?

**Comment by BourgeoisLab** [comment]
Es würde mich freuen, wenn weitere Leute am brauhelfer arbeiten würden. Egal in welcher Form / Platform / Programm. Unterstüzten würde ich es auf jeden Fall, aber eher nicht als aktiver Entwickler. Der Zeitaufwand war in letzter Zeit ziemlich gross und ich brauche jetzt Zeit für andere Projekte:)

Beim jetzigen Code ist die Trennung zwischen GUI und Berechnungen strikt getrennt. Das erlaubt mir den gleichen Code für das Hauptprogramm und die Android App zu nutzen. Es wäre sinnvoll auch hier den gleichen Berechnungscode zu benutzen.  Dies ist mit C++ / Qt geschrieben. Das heisst, man müsste optimalerweise ein C++ Backendprogramm haben.

Wie gesagt, ich bin in der WebApp Welt nicht ganz zuhause und kenne die modernen Möglichkeiten wenig. Hast du eine Idee/Vorstellung, wie es aussehen könnte?

**Comment by dondieselkopf** [comment]
Die Optionen für eine Web-App sind vielfältig. Wenn wir den C++-Code wiederverwenden wollen, muss ich allerdings nochmal schauen, welcher Weg sich da anbietet. Eine Möglichkeit könnte Qt WebChannel [1] sein, aber benutzt habe ich das selbst noch nicht.  Ich werde mich auch mal bei einem Bekannten erkundigen, welche Idee er hätte. Dann melde ich mich wieder.

[1] https://doc.qt.io/qt-5/qtwebchannel-javascript.html

**Comment by a5a351e7** [comment]
Hallo zusammen, ich verfolge dieses Projekt jetzt schon eine Weile und lese den Issue-Tracker mit. Mir fehlt es aktuell an einem Tool, mit dem ich Lager, Rezepte und Sude sinnvoll verwalten kann. Bisher nutze ich dafür Braureka, allerdings ist meine Vorstellung, dass ich eine Software auf einem eigenen Server betreiben kann.

Die Frage der Technologie ist schwierig und meistens dem Geschmack der Entwickler zugeneigt.

Was ich auf jeden Fall sehe ist die Notwendigkeit eines MVC-Models, sowie einem ORM. Ich bin erstmal in alle Richtungen offen, möchte aber C# mit ASP.NET in den Raum werfen. Eine andere einfache alternative wäre PHP, aber da bin ich persönlich etwas voreingenommen...

Wie steht es bei euch mit den Technologien?

**Comment by BourgeoisLab** [comment]
> 
> 
> Die Optionen für eine Web-App sind vielfältig. Wenn wir den C++-Code wiederverwenden wollen, muss ich allerdings nochmal schauen, welcher Weg sich da anbietet. Eine Möglichkeit könnte Qt WebChannel [1] sein, aber benutzt habe ich das selbst noch nicht. Ich werde mich auch mal bei einem Bekannten erkundigen, welche Idee er hätte. Dann melde ich mich wieder.
> 
> [1] https://doc.qt.io/qt-5/qtwebchannel-javascript.html

Eine weitere Möglichkeit, wäre es den Berechnungscode + API in einer Library zu packen, welche JSON Dateien generiert beziehungsweise einlesen kann (um Werte zu schreiben). Backend-mässig braucht es dann nur ein mehr oder weniger standard Webserver. Interpretation der JSON und Darstellung wäre dann über HTML und Javascript.

**Comment by dondieselkopf** [comment]
> Eine weitere Möglichkeit, wäre es den Berechnungscode + API in einer Library zu packen, welche JSON Dateien generiert beziehungsweise einlesen kann (um Werte zu schreiben). Backend-mässig braucht es dann nur ein mehr oder weniger standard Webserver. Interpretation der JSON und Darstellung wäre dann über HTML und Javascript.

Ich würde schätzen, dass Qt WebChannel genau das im Hintergrund macht, dem Entwickler dabei aber die Arbeit mit JSON etc. abnimmt. Jedenfalls ist die Sache lösbar. Ich schau mir das mal an. Bleibt immer noch die Frage, welche Technologie sonst zum Einsatz kommen könnte. Hier ist sowohl die Sprache als auch das Framework zu wählen. Da werde ich mich mal bei den Profis erkundigen. Hier wird man aber verschiedene Meinungen bekommen.

**Comment by dondieselkopf** [comment]
Ich bin mal in mich gegangen. Einen Qt WebChannel in den vorhandenen Code einzubauen, ist vermutlich nicht der leichteste Weg, da man sich um viele Sachen wie Authentifizierung und Sicherheit selbst kümmern müsste. Hier sollte man auf eine stabile Lösung zu setzen. Da könnte man ASP.NET nehmen, aber das wäre für mich ziemlich neu. Mein Vorschlag wäre:

- Backend: Python mit Django
- Frontend: Vue.js [2] oder BootstrapVue [3] oder React [4]
- Einbindung des Qt-Codes: Python extension modules [5]

Django ist ein robustes, agiles Framework, das alles hat, was man braucht (Authentifizierung, User-Verwaltung, OMR, MVC, Templating, ...). Vorteil ist auch, dass C++ einfach eingebunden werden kann. PHP wäre sicher auch eine Option, aber da kenne ich nur das Symfony-Framework und das ist doch recht komplex. Mit der Nutzung eines Frontend-Frameworks könnte man eine schöne Sinlge-Page-App (SPA) bauen. Dann müsste man die Kommunikation komplett über eine REST-API machen, z.B. Djano-REST [6]. Bin noch nicht so sicher, ob sich das lohnt. Die Web-App würde sich dann aber sicher mehr nach einer echten Anwendung anfühlen.

Was meint ihr dazu?

[1] https://www.djangoproject.com/
[2] https://vuejs.org/
[3] https://bootstrap-vue.js.org/
[4] https://reactjs.org/
[5] https://docs.python.org/2/extending/extending.html
[6] https://www.django-rest-framework.org/

**Comment by BourgeoisLab** [comment]
Es macht Sinn ein Framework wie Django zu benutzen. Die Codeeinbindung in Python ist sicher auch kein Problem. Zur Frontend kann ich nicht viel sagen.

Ich würde mir noch die Frage stellen, wie viel Energie du im Projekt investieren willst. Ich denke, etwas anzeigen wird man relativ schnell. Viel Arbeit werden die Details verursachen... Die Umschreibung vom kbh v1 zu v2 (release) hat ziemlich genau 1 Jahr gedauert. Klar das hier ist komplett etwas anders, aber man ist immer viel zu optimistisch.

Ich kann dir beim Pythonteil aktiv helfen. Für die anderen Themen habe ich zurzeit keine Zeit.

**Comment by dondieselkopf** [comment]
Ja, man sollte die Arbeit nicht unterschätzen. Ein Jahr würde ich schon einplanen. Aber wir haben ja keine Eile. Das Gute ist, dass man mit deiner Version eine schöne Vorlage hat, an der man sich orientieren kann. Bedienkonzept, Datenbankstruktur, etc. ist ja bereits vorhanden. Was mich noch beschäftigt ist die Frage, ob der Bedarf für eine WebApp überhaupt da ist, wo es ähnliche bereits gibt:

- https://brauerei.mueggelland.de/rezeptkalkulator.html
- https://www.brewersfriend.com/homebrew/recipe/calculator

Was für ein neues Tool spricht: Nur der Kalkulator von Müggelland scheint auf Deutsch zu sein. Und bei dem fehlen einige Features, die es im Brauhelfer gibt. Außerdem ist die Usability nicht so berauschend. Zudem würde ich mir die Einbindung eines (deutschsprachigen) Braushops wünschen, bei dem man direkt die Zutaten bestellen kann. Aber sind das auch Features, die genutzt werden und den Aufwand rechtfertigen? Wie sind deine Erfahrungen, was die User eigentlich möchten?

**Comment by BourgeoisLab** [comment]
> Wie sind deine Erfahrungen, was die User eigentlich möchten?

Gute Frage:). Die allermeisten Feedbacks erhalte ich hier über die Issues oder den Diskussionsthread auf hobbybrauer.de. Vorteil der Webanwendung sehe ich persönlich am Brautag und für die Eingabe der Gärdaten. Oder wenn man unterwegs etwas nachschauen muss. Für Rezeptgestaltung ist es nicht so wichtig.

**Comment by LondonRain** [comment]
> 
> 
> > Wie sind deine Erfahrungen, was die User eigentlich möchten?
> 
> Gute Frage:). Die allermeisten Feedbacks erhalte ich hier über die Issues oder den Diskussionsthread auf hobbybrauer.de. Vorteil der Webanwendung sehe ich persönlich am Brautag und für die Eingabe der Gärdaten. Oder wenn man unterwegs etwas nachschauen muss. Für Rezeptgestaltung ist es nicht so wichtig.

Aus meiner Sicht wäre da Manpower aber viel sinnvoller darin investiert, das Zusammenspiel mit der schon bestehenden App zu verbessern.

- Vereinfachen des Einrichtungsprozesses ohne dass jeder einen Dropboxdeveleoperaccount anlegen muss
- Bereitstellen der App im Play Store für Aktualisierungen
- Ermöglichen einer iOS-Version

Ich persönlich brauche keine Webapplikation als dritte Plattform und befürchte eher dass da viel Zeit für Technologietransfer und -umstellungen drauf gehen wird, anstatt sie in Bugfixing und Feature-Entwicklung für das bestehende investieren zu können.

**Comment by dondieselkopf** [comment]
Also ich sehe durchaus einige Vorteile einer Web-App für den User:

1. Aktualisierungen sind kein Thema mehr, da man stets mit der aktuellsten Version arbeitet.
1. Der User hat mehr Flexibilität beim Endgerät. Ich nutze zwei Laptops plus Handy und möchte nicht überall das Tool plus Dropbox installieren.
1. Die Erfassung von Gärdaten wird einfacher.

Für die Entwicklung vereinfacht sich auch einiges:

1. Der Release- bzw. Bugfix-Prozess wird quasi zu einem git-merge.
1. Der Aufwand für weitere Betriebssysteme (wie z.B. iOS) fällt weg.
1. Pflege von verschiedenen App-Stores (Windows, Android, iOS) fällt weg. Insbesondere bei iOS ist das wohl ein ziemlicher Pain.

Für mich eigentlich genug Argumente für eine Web-Version.

**Comment by BourgeoisLab** [comment]
Vorteile gibt es schon. Das ist klar. Ich habe mich damals beim Umschreiben auf v2 aus 2 Gründe bewusst gegen ein Webapp entschieden
1. ich wollte keinen Server betreiben
2. ich mag javascript nicht

Meine Erfahrung ist, dass es (leider) wenige Bierbrauer gibt, welche auch in der Freizeit programmieren. Sprich, du wirst das meiste selber machen müssen. Die Entscheidung liegt also bei dir...

Kannst du mir mal eine email schreiben? (bourgeoislab@gmail.com)

**Comment by dondieselkopf** [comment]
Nach einigen Diskussionen bin ich nun von der Idee abgekommen, da es doch schon ein paar Lösungen sowohl als Desktop- als auch Web-App gibt. Ich schließe diese Diskussion damit mal ab.
