### ISSUE TITLE
Nachisomerisierungszeit > 30 Minuten

### ISSUE THREAD

**Issue by hkristen** [kleiner-brauhelfer/kleiner-brauhelfer-2#86]
Ich bin gerade dabei ein Rezept von einer kleinen Anlage mit 10 Minuten Nachisomerisierungszeit auf eine große Anlage mit 50 Minuten Nachisomerisierungszeit (im Whirlpool) zu skalieren. 

Leider lässt der Brauhelfer nur 30 Minuten als maximale Nachisomerisierungszeit zu. Kann man das ändern?

Cheers,
Harald

**Comment by BourgeoisLab** [comment]
Erledigt mit 717e81e.
