### ISSUE TITLE
Falsche Berechnung der Reifezeit

### ISSUE THREAD

**Issue by BurtMC** [kleiner-brauhelfer/kleiner-brauhelfer-2#87]
In der aktuellen Version ist mir bei meinem aktuellen Sud aufgefallen, dass die Reifezeit nicht beginnend mit dem Abfülldatum sondern dem Braudatum berechnet wird.

**Comment by BourgeoisLab** [comment]
Die Reifezeit beginnt ab dem letzten Eintrag der Nachgärung.

**Comment by LondonRain** [comment]
> Die Reifezeit beginnt ab dem letzten Eintrag der Nachgärung.

Was meiner Meinung nach keinen Sinn macht, weil es beim selben Bier zu unterschiedlichen Berechnungen der Woche führt, je nachdem ob derjenige die Nachgärung erfasst, oder erfassen kann, oder eben nicht. 

Zumindest sollte es konfigurierbar sein, dass die Woche sich alternativ aufs Abfülldatum beziehen kann.
