### ISSUE TITLE
2.1.2 OSX - Error Code: 0x00000004 (no mapping for user data read)

### ISSUE THREAD

**Issue by ollinator2000** [kleiner-brauhelfer/kleiner-brauhelfer-2#90]
Wenn ein spezieller Sud ( Sud Nr. 6 ) ausgewählt wird bricht der kbh2 mit einem Fault ab. 

Anbei der Link Crashlog .
https://cloudy.van-der-velde.net/s/2ykS2xZ7mLJoAG3

Version 2.1.1 hat diese Problem nicht . 

Gruss
Olli

**Comment by realholgi** [comment]
Guckst du #89

**Comment by ollinator2000** [comment]
Augen auf , beim testen ... 😀
