### ISSUE TITLE
English language

### ISSUE THREAD

**Issue by jarno83** [kleiner-brauhelfer/kleiner-brauhelfer-2#91]
Hi, I pushed almost every button but didn't find a place where I could change the language to english.
Or there is only German language, but in files I see a folder translations.

Thanks,
Jarno

**Comment by BourgeoisLab** [comment]
Only German is available at the moment. The translations folder is autogenerated by the Qt framework and is not used.

There may be an english version at some point but it is not my top priority.

**Comment by BourgeoisLab** [comment]
First draft ist done and will come in the next release. Although it will not be 100% finished.
