### ISSUE TITLE
Download-Link

### ISSUE THREAD

**Issue by Rasinari** [kleiner-brauhelfer/kleiner-brauhelfer-2#92]
Ich verlinke gerade den KBH auf meiner Website und muss feststellen, dass der Download-Link der letzten Version sehr versteckt ist. Sollte man prominenter "auf den ersten Blick" lösen.

> Download letzte Version
> Version 2.1.2
>

**Comment by BourgeoisLab** [comment]
Sehe ich nicht so. Vorschlag?

Du kannst auch auf diese Seite verlinken:
https://github.com/kleiner-brauhelfer/kleiner-brauhelfer-2/releases/latest

**Comment by Rasinari** [comment]
Ja viel besser! Warum fand ich das nicht? Bedankt!
