### ISSUE TITLE
Manjaro Linux (Arch) Programm startet nicht (Speicherzugriffsfehler)

### ISSUE THREAD

**Issue by svenp** [kleiner-brauhelfer/kleiner-brauhelfer-2#93]
Beim Programmstart kommt es zu folgendem Fehler.
Aktuelle Git Version, das Problem bestand aber auch schon in Version 2.1.2.
Aufgrund der Fehlermeldung ..libQt5Core.so.5.14.2.. vermute es könnte evtl. mit der Qt Version zu tun haben. 

$ ./kleiner-brauhelfer-2 
--- Application start ---
Version: "2.1.3"
Brauhelfer::connectDatabase(): "/home/sven/Dokumente/.kleiner-brauhelfer/kb_daten.sqlite"
Brauhelfer::connectDatabase() version: 2003
SudObject::init()
Speicherzugriffsfehler (Speicherabzug geschrieben)

$ sudo dmesg 
[ 93.276389] kleiner-brauhel[2441]: segfault at 55b5ac350a70 ip 00007f690574b847 sp 00007ffff7f52a08 error 4 in libQt5Core.so.5.14.2[7f69054f5000+2f9000]
[   93.276402] Code: 8b 02 83 c0 01 83 f8 01 77 09 80 67 0b bf c3 0f 1f 40 00 f0 83 02 01 80 67 0b bf c3 90 66 0f 1f 44 00 00 c7 47 08 0a 00 00 00 <48> 8b 16 48 89 17 8b 02 83 c0 01 83 f8 01 77 09 80 67 0b bf c3 0f
[   93.276473] audit: type=1701 audit(1588659571.038:115): auid=1000 uid=1000 gid=1000 ses=2 pid=2441 comm="kleiner-brauhel" exe="/home/sven/Projekte/kleiner-brauhelfer-2/bin/kleiner-brauhelfer-2" sig=11 res=1

$git show
commit b4af4318af3f9e8f126c79890a5d7aa7dc036e41 (HEAD -> master, tag: v2.1.3, origin/master, origin/HEAD)
Author: Frédéric Bourgeois <bourgeoislab@gmail.com>
Date:   Sat May 2 11:27:30 2020 +0200
 v2.1.3

Gruß
Sven

**Comment by BourgeoisLab** [comment]
Der kbh wird mit qt 5.13.2 kompiliert. Du hast 5.14.2 installiert. Eventuell ist das das problem.

Du kannst die portable version (appimage) ausprobieren. Dort ist qt integriert. Dann siehst du, ob das problem von der unterschiedlichen version kommt.

**Comment by svenp** [comment]
Nachdem ich das AppImage erfolgreich mit einer neu angelegten Datenbank getestet habe, habe ich meine "aktuelle" Datenbank in den AppImage config Ordner kopiert. 
Dann kam es auch mit der App Version  zum Speicherzugriffsfehler. 

Folglich lag das Problem eher bei der Datenbank. 

Aktuelle Datenbank leider etwas voreillig mit einem Backup überschrieben.
Nun startet auch die Git Version wieder.
Aufgrund des überschreibens kann ich die Datenbank leider nicht mehr analysieren wo das Problem genau war.

Also doch kein Problem mit der Qt Version. 
Danke für den Tipp mit der App Version
Gruß
Sven

**Comment by BourgeoisLab** [comment]
Gut. Wahrscheinlich lag es an diesem problem #89 .
Führ eine Datenbankreinigung aus (menu file/reinigen).
