### ISSUE TITLE
Neue Hopfenberechnung - Stammwürze

### ISSUE THREAD

**Issue by S1WL** [kleiner-brauhelfer/kleiner-brauhelfer-2#94]
Hallo,
Ich bin seit kurzem am Testen des KBH. Ist schon echt schicker als meine Excel Tabellen ;-). Jetzt bin ich über die Version 2 gestolpert und habe gleich mal die Hopfenberechnung ausprobiert, da ich dort immer Unterschiede in der Berechnung hatte. Mit der neuesten Version kann ich die Berechnung nun besser nachvollziehen (jetzt ist die Nachisomieriezeit offensichtlich auch nicht mehr "nur" die zugerechnete Kochzeit). 
Ich bin kein Fachmann, wollte aber mal anmerken, dass die ganze Hopfenberechnung scheinbar mit der Ziel-Stammwürze kalkuliert wird. Ich bin der Meinung, dass hier eigentlich der unterschiedliche Stammwürze-Wert ab Beginn des Kochens angenommen werden müsste. Als Annäherung könnte ja beispielsweise der Mittelwert von Beginn und Ende des Kochens verwendet werden.
Liege ich da falsch, oder kann das in eine spätere Optimierung einfließen?

**Comment by BourgeoisLab** [comment]
Ich weiss nicht genau, wie Tinseth auf die Formel gekommen ist. Man müsste nachforschen, was er genau gemacht hat und welche Wert er genommen hat.

Noch besser wäre statt den Wert bei Kochbeginn, den Wert bei Zugabe des Hopfens zu nehmen (abgeschätz über die Zeit). Dann zusammen mit dem Wert bei Kochende mitteln.

**Comment by BourgeoisLab** [comment]
Laut https://realbeer.com/hops/research.html wird tatsächlich von einer mittleren Stammwürze ausgegangen.

> Use an average gravity value for the entire boil to account for changes in the wort volume.

**Comment by S1WL** [comment]
Ich hatte auch den Mittelwert von Anfang-Ende drin, was ja auch nur eine Annäherung ist. Ich habe in meiner Tabelle jetzt mal für jede Gabe den gemittelten Stammwürzegehalt der jeweils restlichen Kochzeit in die Rechnung reingenommen. Der Ansatz ist im Grunde ja wirklich simpel, aber bring vielleicht noch ein Promille Genauigkeit ;-)

**Comment by BourgeoisLab** [comment]
Erledigt mit 9117bacfbb604c017a4e16921dd6a3395c7ed28f.
