### ISSUE TITLE
Extraktpotential der Malze berücksichtigen

### ISSUE THREAD

**Issue by BourgeoisLab** [kleiner-brauhelfer/kleiner-brauhelfer-2#96]
Datenbankstruktur wurde bereits angepasst.

**Comment by BurtMC** [comment]
Die Datenbank lässt bei der Eingabe des Extraktpotentials leider nur zwei Nachkommatsellen zu. Da die meisten Angaben aber drei Nachkommastellen haben müsste dies noch angepasst werden.

**Comment by Rasinari** [comment]
> Die Datenbank lässt bei der händischen Eingabe des Extraktpotentials leider nur zwei Nachkommatsellen zu.
> Werden die Malz über die ObraMa angelegt, stehen dort die richtigen Werte mit drei Nachkommastellen drin.

Das ist richtig. Diese Werte sind aber in der Einheit SG (Special Gravity) angegeben, also im amerikanischen System. Das amerikanische System hat eigentlich auch zwei Nachkommastellen - 1.0 wird immer vornean gestellt; üblicherweise wird auf eine Nachkommastelle nach °Plato umgerechnet; wenn der KBH hier mit zwei Nachkommastellen arbeitet, ist das meiner Meinung nach genau genug.

Kann wohl geschlossen werden.
