### ISSUE TITLE
Abzug von Rohstoffen funktioniert nicht bei Hopfenstopfen

### ISSUE THREAD

**Issue by patman081** [kleiner-brauhelfer/kleiner-brauhelfer-2#98]
Der automatische Abzug von Rohstoffen funktioniert nicht für "weitere Zutaten", z.B. Hopfenstopfen.
Zumindest auf MacOS popped nur ein leerer Frame auf, nachdem die Zutat hinzugeben "Zugeben" wurde.

**Comment by BourgeoisLab** [comment]
Das sollte mit 2.1.3 behoben worden sein.
